
# Copyright(c) 2018 Intel Corporation

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files(the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and / or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
    agnostic/common/cm/cm_array.cpp \
    agnostic/common/cm/cm_buffer_rt.cpp \
    agnostic/common/cm/cm_def.cpp \
    agnostic/common/cm/cm_device_rt.cpp \
    agnostic/common/cm/cm_event_rt.cpp \
    agnostic/common/cm/cm_global_api.cpp \
    agnostic/common/cm/cm_group_space.cpp \
    agnostic/common/cm/cm_hal.cpp \
    agnostic/common/cm/cm_hal_dump.cpp \
    agnostic/common/cm/cm_hal_hashtable.cpp \
    agnostic/common/cm/cm_hal_vebox.cpp \
    agnostic/common/cm/cm_kernel_data.cpp \
    agnostic/common/cm/cm_kernel_rt.cpp \
    agnostic/common/cm/cm_log.cpp \
    agnostic/common/cm/cm_perf.cpp \
    agnostic/common/cm/cm_printf_host.cpp \
    agnostic/common/cm/cm_program.cpp \
    agnostic/common/cm/cm_queue_rt.cpp \
    agnostic/common/cm/cm_sampler8x8_state_rt.cpp \
    agnostic/common/cm/cm_sampler_rt.cpp \
    agnostic/common/cm/cm_state_buffer.cpp \
    agnostic/common/cm/cm_surface.cpp \
    agnostic/common/cm/cm_surface_2d_rt.cpp \
    agnostic/common/cm/cm_surface_2d_up_rt.cpp \
    agnostic/common/cm/cm_surface_3d_rt.cpp \
    agnostic/common/cm/cm_surface_manager.cpp \
    agnostic/common/cm/cm_surface_sampler.cpp \
    agnostic/common/cm/cm_surface_sampler8x8.cpp \
    agnostic/common/cm/cm_surface_vme.cpp \
    agnostic/common/cm/cm_task_internal.cpp \
    agnostic/common/cm/cm_task_rt.cpp \
    agnostic/common/cm/cm_thread_space_rt.cpp \
    agnostic/common/cm/cm_vebox_data.cpp \
    agnostic/common/cm/cm_vebox_rt.cpp \
    agnostic/common/cm/cm_visa.cpp \
    agnostic/common/cm/cm_wrapper.cpp \
    agnostic/common/codec/hal/codechal.cpp \
    agnostic/common/codec/hal/codechal_allocator.cpp \
    agnostic/common/codec/hal/codechal_debug.cpp \
    agnostic/common/codec/hal/codechal_debug_config_manager.cpp \
    agnostic/common/codec/hal/codechal_debug_encode_par.cpp \
    agnostic/common/codec/hal/codechal_decode_avc.cpp \
    agnostic/common/codec/hal/codechal_decode_downsampling.cpp \
    agnostic/common/codec/hal/codechal_decode_hevc.cpp \
    agnostic/common/codec/hal/codechal_decode_histogram.cpp \
    agnostic/common/codec/hal/codechal_decode_histogram_vebox.cpp \
    agnostic/common/codec/hal/codechal_decode_jpeg.cpp \
    agnostic/common/codec/hal/codechal_decode_mpeg2.cpp \
    agnostic/common/codec/hal/codechal_decode_nv12top010.cpp \
    agnostic/common/codec/hal/codechal_decode_sfc.cpp \
    agnostic/common/codec/hal/codechal_decode_sfc_avc.cpp \
    agnostic/common/codec/hal/codechal_decode_sfc_hevc.cpp \
    agnostic/common/codec/hal/codechal_decode_sfc_jpeg.cpp \
    agnostic/common/codec/hal/codechal_decode_vc1.cpp \
    agnostic/common/codec/hal/codechal_decode_vp8.cpp \
    agnostic/common/codec/hal/codechal_decode_vp9.cpp \
    agnostic/common/codec/hal/codechal_decoder.cpp \
    agnostic/common/codec/hal/codechal_encode_allocator.cpp \
    agnostic/common/codec/hal/codechal_encode_avc.cpp \
    agnostic/common/codec/hal/codechal_encode_avc_base.cpp \
    agnostic/common/codec/hal/codechal_encode_csc_ds.cpp \
    agnostic/common/codec/hal/codechal_encode_hevc.cpp \
    agnostic/common/codec/hal/codechal_encode_hevc_base.cpp \
    agnostic/common/codec/hal/codechal_encode_jpeg.cpp \
    agnostic/common/codec/hal/codechal_encode_mpeg2.cpp \
    agnostic/common/codec/hal/codechal_encode_sfc.cpp \
    agnostic/common/codec/hal/codechal_encode_tracked_buffer.cpp \
    agnostic/common/codec/hal/codechal_encode_tracked_buffer_hevc.cpp \
    agnostic/common/codec/hal/codechal_encode_vp8.cpp \
    agnostic/common/codec/hal/codechal_encode_wp.cpp \
    agnostic/common/codec/hal/codechal_encoder_base.cpp \
    agnostic/common/codec/hal/codechal_huc_cmd_initializer.cpp \
    agnostic/common/codec/hal/codechal_hw.cpp \
    agnostic/common/codec/hal/codechal_kernel_base.cpp \
    agnostic/common/codec/hal/codechal_kernel_hme.cpp \
    agnostic/common/codec/hal/codechal_kernel_intra_dist.cpp \
    agnostic/common/codec/hal/codechal_memdecomp.cpp \
    agnostic/common/codec/hal/codechal_mmc.cpp \
    agnostic/common/codec/hal/codechal_mmc_decode_avc.cpp \
    agnostic/common/codec/hal/codechal_mmc_decode_hevc.cpp \
    agnostic/common/codec/hal/codechal_mmc_decode_jpeg.cpp \
    agnostic/common/codec/hal/codechal_mmc_decode_mpeg2.cpp \
    agnostic/common/codec/hal/codechal_mmc_decode_vc1.cpp \
    agnostic/common/codec/hal/codechal_mmc_decode_vp8.cpp \
    agnostic/common/codec/hal/codechal_mmc_decode_vp9.cpp \
    agnostic/common/codec/hal/codechal_mmc_encode_avc.cpp \
    agnostic/common/codec/hal/codechal_mmc_encode_hevc.cpp \
    agnostic/common/codec/hal/codechal_mmc_encode_mpeg2.cpp \
    agnostic/common/codec/hal/codechal_mmc_encode_vp8.cpp \
    agnostic/common/codec/hal/codechal_mmc_encode_vp9.cpp \
    agnostic/common/codec/hal/codechal_setting.cpp \
    agnostic/common/codec/hal/codechal_utilities.cpp \
    agnostic/common/codec/hal/codechal_vdenc_avc.cpp \
    agnostic/common/codec/hal/codechal_vdenc_hevc.cpp \
    agnostic/common/codec/hal/codechal_vdenc_vp9_base.cpp \
    agnostic/common/heap_manager/heap.cpp \
    agnostic/common/heap_manager/heap_manager.cpp \
    agnostic/common/heap_manager/memory_block.cpp \
    agnostic/common/heap_manager/memory_block_manager.cpp \
    agnostic/common/hw/mhw_block_manager.c \
    agnostic/common/hw/mhw_memory_pool.c \
    agnostic/common/hw/mhw_mi.cpp \
    agnostic/common/hw/mhw_render.c \
    agnostic/common/hw/mhw_sfc.cpp \
    agnostic/common/hw/mhw_state_heap.c \
    agnostic/common/hw/mhw_utilities.c \
    agnostic/common/hw/mhw_vebox.cpp \
    agnostic/common/hw/vdbox/mhw_vdbox_hcp_interface.cpp \
    agnostic/common/hw/vdbox/mhw_vdbox_huc_interface.cpp \
    agnostic/common/hw/vdbox/mhw_vdbox_mfx_interface.cpp \
    agnostic/common/hw/vdbox/mhw_vdbox_vdenc_interface.cpp \
    agnostic/common/os/mos_cmdbufmgr.cpp \
    agnostic/common/os/mos_commandbuffer.cpp \
    agnostic/common/os/mos_context.cpp \
    agnostic/common/os/mos_gpucontext.cpp \
    agnostic/common/os/mos_gpucontextmgr.cpp \
    agnostic/common/os/mos_graphicsresource.cpp \
    agnostic/common/os/mos_os.c \
    agnostic/common/os/mos_util_debug.c \
    agnostic/common/os/mos_util_user_interface.cpp \
    agnostic/common/os/mos_utilities.c \
    agnostic/common/renderhal/renderhal.cpp \
    agnostic/common/renderhal/renderhal_common.cpp \
    agnostic/common/renderhal/renderhal_dsh.cpp \
    agnostic/common/shared/media_perf_profiler.cpp \
    agnostic/common/shared/mediamemdecomp.cpp \
    agnostic/common/vp/hal/vphal.cpp \
    agnostic/common/vp/hal/vphal_common.c \
    agnostic/common/vp/hal/vphal_ddi.c \
    agnostic/common/vp/hal/vphal_debug.c \
    agnostic/common/vp/hal/vphal_render_common.c \
    agnostic/common/vp/hal/vphal_render_composite.cpp \
    agnostic/common/vp/hal/vphal_render_ief.cpp \
    agnostic/common/vp/hal/vphal_render_renderstate.cpp \
    agnostic/common/vp/hal/vphal_render_sfc_base.cpp \
    agnostic/common/vp/hal/vphal_render_vebox_base.cpp \
    agnostic/common/vp/hal/vphal_render_vebox_iecp.cpp \
    agnostic/common/vp/hal/vphal_render_vebox_procamp.cpp \
    agnostic/common/vp/hal/vphal_render_vebox_ste.cpp \
    agnostic/common/vp/hal/vphal_render_vebox_tcc.cpp \
    agnostic/common/vp/hal/vphal_render_vebox_util_base.c \
    agnostic/common/vp/hal/vphal_renderer.cpp \
    agnostic/common/vp/kdll/hal_kerneldll.c \
    agnostic/gen10/cm/cm_hal_g10.cpp \
    agnostic/gen10/codec/hal/codechal_debug_encode_par_g10.cpp \
    agnostic/gen10/codec/hal/codechal_decode_downsampling_g10.cpp \
    agnostic/gen10/codec/hal/codechal_decode_histogram_vebox_g10.cpp \
    agnostic/gen10/codec/hal/codechal_decode_nv12top010_g10.cpp \
    agnostic/gen10/codec/hal/codechal_decode_nv12top010_kernel_g10.cpp \
    agnostic/gen10/codec/hal/codechal_decode_vc1_g10.cpp \
    agnostic/gen10/codec/hal/codechal_encode_avc_g10.cpp \
    agnostic/gen10/codec/hal/codechal_encode_csc_ds_g10.cpp \
    agnostic/gen10/codec/hal/codechal_encode_hevc_g10.cpp \
    agnostic/gen10/codec/hal/codechal_encode_hevc_table_g10.cpp \
    agnostic/gen10/codec/hal/codechal_encode_mpeg2_g10.cpp \
    agnostic/gen10/codec/hal/codechal_encode_vp8_g10.cpp \
    agnostic/gen10/codec/hal/codechal_encode_wp_g10.cpp \
    agnostic/gen10/codec/hal/codechal_hw_g10_X.cpp \
    agnostic/gen10/codec/hal/codechal_kernel_hme_g10.cpp \
    agnostic/gen10/codec/hal/codechal_memdecomp_g10.cpp \
    agnostic/gen10/codec/hal/codechal_vdenc_avc_g10.cpp \
    agnostic/gen10/codec/hal/codechal_vdenc_hevc_g10.cpp \
    agnostic/gen10/codec/hal/codechal_vdenc_vp9_g10.cpp \
    agnostic/gen10/codec/kernel/igcodeckrn_g10.c \
    agnostic/gen10/hw/mhw_mi_g10_X.cpp \
    agnostic/gen10/hw/mhw_mi_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/mhw_render_g10_X.cpp \
    agnostic/gen10/hw/mhw_render_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/mhw_sfc_g10_X.cpp \
    agnostic/gen10/hw/mhw_sfc_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/mhw_state_heap_g10.c \
    agnostic/gen10/hw/mhw_state_heap_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/mhw_vebox_g10_X.cpp \
    agnostic/gen10/hw/mhw_vebox_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_hcp_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_hcp_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_huc_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_huc_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_mfx_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_mfx_hwcmd_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_vdenc_g10_X.cpp \
    agnostic/gen10/hw/vdbox/mhw_vdbox_vdenc_hwcmd_g10_X.cpp \
    agnostic/gen10/renderhal/renderhal_g10.cpp \
    agnostic/gen10/vp/hal/vphal_g10.cpp \
    agnostic/gen10/vp/hal/vphal_render_composite_g10.cpp \
    agnostic/gen10/vp/hal/vphal_render_sfc_g10_base.cpp \
    agnostic/gen10/vp/hal/vphal_render_vebox_g10_base.cpp \
    agnostic/gen10/vp/hal/vphal_renderer_g10.cpp \
    agnostic/gen10/vp/kdll/hal_kernelrules_g10.c \
    agnostic/gen10/vp/kernel/igvpkrn_g10.c \
    agnostic/gen10_cnl/media_interfaces/media_interfaces_g10_cnl.cpp \
    agnostic/gen8/cm/cm_hal_g8.cpp \
    agnostic/gen8/codec/hal/codechal_decode_vc1_g8.cpp \
    agnostic/gen8/codec/hal/codechal_encode_avc_g8.cpp \
    agnostic/gen8/codec/hal/codechal_encode_csc_ds_g8.cpp \
    agnostic/gen8/codec/hal/codechal_encode_mpeg2_g8.cpp \
    agnostic/gen8/codec/hal/codechal_encode_wp_g8.cpp \
    agnostic/gen8/codec/hal/codechal_fei_avc_g8.cpp \
    agnostic/gen8/codec/hal/codechal_hw_g8_X.cpp \
    agnostic/gen8/codec/hal/codechal_kernel_hme_g8.cpp \
    agnostic/gen8/codec/kernel/igcodeckrn_g8.c \
    agnostic/gen8/hw/mhw_mi_g8_X.cpp \
    agnostic/gen8/hw/mhw_mi_hwcmd_g8_X.cpp \
    agnostic/gen8/hw/mhw_render_g8_X.cpp \
    agnostic/gen8/hw/mhw_render_hwcmd_g8_X.cpp \
    agnostic/gen8/hw/mhw_state_heap_g8.c \
    agnostic/gen8/hw/mhw_state_heap_hwcmd_g8_X.cpp \
    agnostic/gen8/hw/mhw_vebox_g8_X.cpp \
    agnostic/gen8/hw/mhw_vebox_hwcmd_g8_X.cpp \
    agnostic/gen8/renderhal/renderhal_g8.cpp \
    agnostic/gen8/vp/hal/vphal_g8.cpp \
    agnostic/gen8/vp/hal/vphal_render_composite_g8.cpp \
    agnostic/gen8/vp/hal/vphal_render_vebox_g8_base.cpp \
    agnostic/gen8/vp/hal/vphal_renderer_g8.cpp \
    agnostic/gen8/vp/kdll/hal_kerneldll_g8.c \
    agnostic/gen8/vp/kdll/hal_kernelrules_g8.c \
    agnostic/gen8/vp/kernel/igvpkrn_g8.c \
    agnostic/gen8_bdw/hw/vdbox/mhw_vdbox_mfx_g8_bdw.cpp \
    agnostic/gen8_bdw/hw/vdbox/mhw_vdbox_mfx_hwcmd_g8_bdw.cpp \
    agnostic/gen8_bdw/media_interfaces/media_interfaces_g8_bdw.cpp \
    agnostic/gen9/cm/cm_hal_g9.cpp \
    agnostic/gen9/codec/hal/codechal_debug_encode_par_g9.cpp \
    agnostic/gen9/codec/hal/codechal_decode_downsampling_g9.cpp \
    agnostic/gen9/codec/hal/codechal_decode_histogram_vebox_g9.cpp \
    agnostic/gen9/codec/hal/codechal_decode_nv12top010_g9.cpp \
    agnostic/gen9/codec/hal/codechal_decode_nv12top010_kernel_g9.cpp \
    agnostic/gen9/codec/hal/codechal_decode_vc1_g9.cpp \
    agnostic/gen9/codec/hal/codechal_encode_avc_g9.cpp \
    agnostic/gen9/codec/hal/codechal_encode_csc_ds_g9.cpp \
    agnostic/gen9/codec/hal/codechal_encode_hevc_g9.cpp \
    agnostic/gen9/codec/hal/codechal_encode_mpeg2_g9.cpp \
    agnostic/gen9/codec/hal/codechal_encode_wp_g9.cpp \
    agnostic/gen9/codec/hal/codechal_fei_avc_g9.cpp \
    agnostic/gen9/codec/hal/codechal_hw_g9_X.cpp \
    agnostic/gen9/codec/hal/codechal_kernel_hme_g9.cpp \
    agnostic/gen9/codec/hal/codechal_memdecomp_g9.cpp \
    agnostic/gen9/codec/hal/codechal_vdenc_avc_g9.cpp \
    agnostic/gen9/codec/kernel/igcodeckrn_g9.c \
    agnostic/gen9/hw/mhw_mi_g9_X.cpp \
    agnostic/gen9/hw/mhw_mi_hwcmd_g9_X.cpp \
    agnostic/gen9/hw/mhw_render_g9_X.cpp \
    agnostic/gen9/hw/mhw_render_hwcmd_g9_X.cpp \
    agnostic/gen9/hw/mhw_sfc_g9_X.cpp \
    agnostic/gen9/hw/mhw_sfc_hwcmd_g9_X.cpp \
    agnostic/gen9/hw/mhw_state_heap_g9.c \
    agnostic/gen9/hw/mhw_state_heap_hwcmd_g9_X.cpp \
    agnostic/gen9/hw/mhw_vebox_g9_X.cpp \
    agnostic/gen9/hw/mhw_vebox_hwcmd_g9_X.cpp \
    agnostic/gen9/renderhal/renderhal_g9.cpp \
    agnostic/gen9/vp/hal/vphal_g9.cpp \
    agnostic/gen9/vp/hal/vphal_render_composite_g9.cpp \
    agnostic/gen9/vp/hal/vphal_render_sfc_g9_base.cpp \
    agnostic/gen9/vp/hal/vphal_render_vebox_g9_base.cpp \
    agnostic/gen9/vp/hal/vphal_renderer_g9.cpp \
    agnostic/gen9/vp/kdll/hal_kernelrules_g9.c \
    agnostic/gen9/vp/kernel/igvpkrn_g9.c \
    agnostic/gen9_bxt/codec/hal/codechal_decode_nv12top010_g9_bxt.cpp \
    agnostic/gen9_bxt/codec/hal/codechal_decode_nv12top010_kernel_g9_bxt.cpp \
    agnostic/gen9_bxt/codec/hal/codechal_encode_avc_g9_bxt.cpp \
    agnostic/gen9_bxt/codec/hal/codechal_encode_hevc_g9_bxt.cpp \
    agnostic/gen9_bxt/codec/hal/codechal_hw_g9_bxt.cpp \
    agnostic/gen9_bxt/codec/hal/codechal_vdenc_avc_g9_bxt.cpp \
    agnostic/gen9_bxt/codec/kernel/igcodeckrn_g9_bxt.c \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_hcp_g9_bxt.cpp \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_hcp_hwcmd_g9_bxt.cpp \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_huc_g9_bxt.cpp \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_huc_hwcmd_g9_bxt.cpp \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_mfx_g9_bxt.cpp \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_mfx_hwcmd_g9_bxt.cpp \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_vdenc_g9_bxt.cpp \
    agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_vdenc_hwcmd_g9_bxt.cpp \
    agnostic/gen9_bxt/media_interfaces/media_interfaces_g9_bxt.cpp \
    agnostic/gen9_bxt/vp/hal/vphal_g9_bxt.cpp \
    agnostic/gen9_cfl/media_interfaces/media_interfaces_g9_cfl.cpp \
    agnostic/gen9_glk/codec/hal/codechal_decode_nv12top010_g9_glk.cpp \
    agnostic/gen9_glk/codec/hal/codechal_decode_nv12top010_kernel_g9_glk.cpp \
    agnostic/gen9_glk/codec/hal/codechal_encode_hevc_g9_glk.cpp \
    agnostic/gen9_glk/hw/vdbox/mhw_vdbox_hcp_hwcmd_g9_glk.cpp \
    agnostic/gen9_glk/hw/vdbox/mhw_vdbox_huc_hwcmd_g9_glk.cpp \
    agnostic/gen9_glk/media_interfaces/media_interfaces_g9_glk.cpp \
    agnostic/gen9_glk/vp/hal/vphal_g9_glk.cpp \
    agnostic/gen9_kbl/codec/hal/codechal_encode_avc_g9_kbl.cpp \
    agnostic/gen9_kbl/codec/hal/codechal_encode_hevc_g9_kbl.cpp \
    agnostic/gen9_kbl/codec/hal/codechal_hw_g9_kbl.cpp \
    agnostic/gen9_kbl/codec/hal/codechal_vdenc_avc_g9_kbl.cpp \
    agnostic/gen9_kbl/codec/kernel/igcodeckrn_g9_kbl.c \
    agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_hcp_g9_kbl.cpp \
    agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_hcp_hwcmd_g9_kbl.cpp \
    agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_huc_hwcmd_g9_kbl.cpp \
    agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_mfx_g9_kbl.cpp \
    agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_mfx_hwcmd_g9_kbl.cpp \
    agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_vdenc_g9_kbl.cpp \
    agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_vdenc_hwcmd_g9_kbl.cpp \
    agnostic/gen9_kbl/media_interfaces/media_interfaces_g9_kbl.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/AvcEncFei_Mfe_gen9.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernelBase.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_DownScaling.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_I_16x16Mode.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_I_16x16Sad.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_I_32x32.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_I_8x8.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_I_8x8Mode.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_PB_32x32.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_PB_8x8MbEnc.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/CMRTKernel_PB_8x8Pak.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/HevcEncFei_I_gen9.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/HevcEncFei_PB_gen9.cpp \
    agnostic/gen9_skl/codec/cmrt_kernel/Hme_Downscale_gen9.cpp \
    agnostic/gen9_skl/codec/hal/codechal_encode_avc_g9_skl.cpp \
    agnostic/gen9_skl/codec/hal/codechal_encode_hevc_g9_skl.cpp \
    agnostic/gen9_skl/codec/hal/codechal_encode_mpeg2_g9_skl.cpp \
    agnostic/gen9_skl/codec/hal/codechal_fei_avc_g9_skl.cpp \
    agnostic/gen9_skl/codec/hal/codechal_fei_hevc_g9_skl.cpp \
    agnostic/gen9_skl/codec/hal/codechal_vdenc_avc_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_hcp_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_hcp_hwcmd_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_huc_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_huc_hwcmd_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_mfx_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_mfx_hwcmd_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_vdenc_g9_skl.cpp \
    agnostic/gen9_skl/hw/vdbox/mhw_vdbox_vdenc_hwcmd_g9_skl.cpp \
    agnostic/gen9_skl/media_interfaces/media_interfaces_g9_skl.cpp \
    linux/common/cm/cm_device_rt_os.cpp \
    linux/common/cm/cm_event_rt_os.cpp \
    linux/common/cm/cm_ftrace.cpp \
    linux/common/cm/cm_global_api_os.cpp \
    linux/common/cm/cm_hal_os.cpp \
    linux/common/cm/cm_surface_2d_rt_os.cpp \
    linux/common/cm/cm_surface_manager_os.cpp \
    linux/common/cm/cm_task_internal_os.cpp \
    linux/common/cm/cm_task_rt_os.cpp \
    linux/common/cm/cm_wrapper_os.cpp \
    linux/common/cm/media_libva_cm.c \
    linux/common/codec/ddi/media_ddi_decode_avc.cpp \
    linux/common/codec/ddi/media_ddi_decode_base.cpp \
    linux/common/codec/ddi/media_ddi_decode_hevc.cpp \
    linux/common/codec/ddi/media_ddi_decode_jpeg.cpp \
    linux/common/codec/ddi/media_ddi_decode_mpeg2.cpp \
    linux/common/codec/ddi/media_ddi_decode_vc1.cpp \
    linux/common/codec/ddi/media_ddi_decode_vp8.cpp \
    linux/common/codec/ddi/media_ddi_decode_vp9.cpp \
    linux/common/codec/ddi/media_ddi_encode_avc.cpp \
    linux/common/codec/ddi/media_ddi_encode_base.cpp \
    linux/common/codec/ddi/media_ddi_encode_fei_avc.cpp \
    linux/common/codec/ddi/media_ddi_encode_fei_hevc.cpp \
    linux/common/codec/ddi/media_ddi_encode_hevc.cpp \
    linux/common/codec/ddi/media_ddi_encode_jpeg.cpp \
    linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp \
    linux/common/codec/ddi/media_ddi_encode_vp8.cpp \
    linux/common/codec/ddi/media_ddi_encode_vp9.cpp \
    linux/common/codec/ddi/media_libva_decoder.cpp \
    linux/common/codec/ddi/media_libva_encoder.cpp \
    linux/common/codec/ddi/media_libvpx_vp9.cpp \
    linux/common/cp/ddi/media_libva_cp.cpp \
    linux/common/cp/hw/mhw_cp.cpp \
    linux/common/cp/os/mos_os_cp_specific.cpp \
    linux/common/ddi/media_ddi_base.cpp \
    linux/common/ddi/media_libva.cpp \
    linux/common/ddi/media_libva_caps.cpp \
    linux/common/ddi/media_libva_common.cpp \
    linux/common/ddi/media_libva_util.cpp \
    linux/common/media_interfaces/media_interfaces.cpp \
    linux/common/os/hwinfo_linux.c \
    linux/common/os/libdrm/mos_bufmgr.c \
    linux/common/os/libdrm/mos_bufmgr_api.c \
    linux/common/os/libdrm/xf86drm.c \
    linux/common/os/libdrm/xf86drmHash.c \
    linux/common/os/libdrm/xf86drmMode.c \
    linux/common/os/libdrm/xf86drmRandom.c \
    linux/common/os/mos_commandbuffer_specific.cpp \
    linux/common/os/mos_context_specific.cpp \
    linux/common/os/mos_gpucontext_specific.cpp \
    linux/common/os/mos_graphicsresource_specific.cpp \
    linux/common/os/mos_os_specific.c \
    linux/common/os/mos_util_debug_specific.c \
    linux/common/os/mos_util_user_interface_specific.cpp \
    linux/common/os/mos_utilities_specific.c \
    linux/common/renderhal/renderhal_dsh_specific.c \
    linux/common/renderhal/renderhal_linux.cpp \
    linux/common/vp/ddi/media_libva_vp.c \
    linux/common/vp/ddi/media_libva_vp_tools.c \
    linux/common/vp/hal/vphal_common_specific.c \
    linux/common/vp/hal/vphal_render_common_specific.c \
    linux/gen10/ddi/media_libva_caps_g10.cpp \
    linux/gen10/ddi/media_sku_wa_g10.cpp \
    linux/gen10/ddi/media_sysinfo_g10.cpp \
    linux/gen10_cnl/ddi/media_libva_caps_g10_cnl.cpp \
    linux/gen8/ddi/media_libva_caps_g8.cpp \
    linux/gen8/ddi/media_sku_wa_g8.cpp \
    linux/gen8/ddi/media_sysinfo_g8.cpp \
    linux/gen9/ddi/media_libva_caps_g9.cpp \
    linux/gen9/ddi/media_sku_wa_g9.cpp \
    linux/gen9/ddi/media_sysinfo_g9.cpp \
    linux/gen9_bxt/ddi/media_libva_caps_g9_bxt.cpp \
    linux/gen9_cfl/ddi/media_libva_caps_g9_cfl.cpp \
    linux/gen9_glk/ddi/media_libva_caps_g9_glk.cpp \
    linux/gen9_kbl/ddi/media_libva_caps_g9_kbl.cpp \
    linux/gen9_skl/ddi/media_libva_caps_g9_skl.cpp \

LOCAL_SHARED_LIBRARIES += libsync
LOCAL_SHARED_LIBRARIES += libbinder
LOCAL_SHARED_LIBRARIES += libcutils
LOCAL_SHARED_LIBRARIES += libutils
LOCAL_SHARED_LIBRARIES += libdrm
LOCAL_SHARED_LIBRARIES += libva
LOCAL_SHARED_LIBRARIES += liblog
LOCAL_SHARED_LIBRARIES += libpciaccess

LOCAL_STATIC_LIBRARIES = \
    libgmm_umd \

LOCAL_CPPFLAGS = \
    -DDRV_I915 \
    -DOTC_GRALLOC \
    -DANDROID_VERSION=800 \
    -fexceptions \
    -frtti \
    -std=c++14 \
    -DHEVC_FEI_ENABLE_CMRT \
    -DIGFX_GEN10_CNL_SUPPORTED \
    -DIGFX_GEN10_SUPPORTED \
    -DIGFX_GEN8_BDW_SUPPORTED \
    -DIGFX_GEN8_SUPPORTED \
    -DIGFX_GEN9_BXT_SUPPORTED \
    -DIGFX_GEN9_CFL_SUPPORTED \
    -DIGFX_GEN9_GLK_SUPPORTED \
    -DIGFX_GEN9_KBL_SUPPORTED \
    -DIGFX_GEN9_SKL_SUPPORTED \
    -DIGFX_GEN9_SUPPORTED \
    -DUFO_VERSION=\"2.0.0\" \
    -DVEBOX_AUTO_DENOISE_SUPPORTED=1 \
    -D_AVC_DECODE_SUPPORTED \
    -D_AVC_ENCODE_SUPPORTED \
    -D_COMMON_ENCODE_SUPPORTED \
    -D_DECODE_PROCESSING_SUPPORTED \
    -D_HEVC_DECODE_SUPPORTED \
    -D_HEVC_ENCODE_SUPPORTED \
    -D_JPEG_DECODE_SUPPORTED \
    -D_JPEG_ENCODE_SUPPORTED \
    -D_MMC_SUPPORTED \
    -D_MPEG2_DECODE_SUPPORTED \
    -D_MPEG2_ENCODE_SUPPORTED \
    -D_RELEASE \
    -D_VC1_DECODE_SUPPORTED \
    -D_VP8_DECODE_SUPPORTED \
    -D_VP8_ENCODE_SUPPORTED \
    -D_VP9_DECODE_SUPPORTED \
    -D_VP9_ENCODE_SUPPORTED \
    -D__STDC_CONSTANT_MACROS \
    -D__STDC_LIMIT_MACROS \
    -D__VPHAL_SFC_SUPPORTED=1 \
    -DiHD_drv_video_EXPORTS \
	-Wno-error


LOCAL_CONLYFLAGS = -x c++
LOCAL_CFLAGS = $(LOCAL_CPPFLAGS)

LOCAL_C_INCLUDES  = \
    $(TARGET_OUT_HEADERS)/libva \
    $(TARGET_OUT_HEADERS)/ufo \
    $(LOCAL_PATH)/linux/common/os/libdrm/include \
    $(LOCAL_PATH)/agnostic/common/cm \
    $(LOCAL_PATH)/agnostic/common/codec/hal \
    $(LOCAL_PATH)/agnostic/common/codec/kernel \
    $(LOCAL_PATH)/agnostic/common/codec/shared \
    $(LOCAL_PATH)/agnostic/common/heap_manager \
    $(LOCAL_PATH)/agnostic/common/hw/vdbox \
    $(LOCAL_PATH)/agnostic/common/hw \
    $(LOCAL_PATH)/agnostic/common/media_interfaces \
    $(LOCAL_PATH)/agnostic/common/os \
    $(LOCAL_PATH)/agnostic/common/renderhal \
    $(LOCAL_PATH)/agnostic/common/shared \
    $(LOCAL_PATH)/agnostic/common/vp/hal \
    $(LOCAL_PATH)/agnostic/common/vp/kdll \
    $(LOCAL_PATH)/agnostic/common/vp/kernel \
    $(LOCAL_PATH)/agnostic/gen8/cm \
    $(LOCAL_PATH)/agnostic/gen8/codec/hal \
    $(LOCAL_PATH)/agnostic/gen8/codec/kernel \
    $(LOCAL_PATH)/agnostic/gen8/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen8/hw \
    $(LOCAL_PATH)/agnostic/gen8/renderhal \
    $(LOCAL_PATH)/agnostic/gen8/vp/hal \
    $(LOCAL_PATH)/agnostic/gen8/vp/kernel \
    $(LOCAL_PATH)/agnostic/gen8_bdw/codec/hal \
    $(LOCAL_PATH)/agnostic/gen8_bdw/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen8_bdw/media_interfaces \
    $(LOCAL_PATH)/agnostic/gen8_bdw/renderhal \
    $(LOCAL_PATH)/agnostic/gen9/cm \
    $(LOCAL_PATH)/agnostic/gen9/codec/hal \
    $(LOCAL_PATH)/agnostic/gen9/codec/kernel \
    $(LOCAL_PATH)/agnostic/gen9/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen9/hw \
    $(LOCAL_PATH)/agnostic/gen9/renderhal \
    $(LOCAL_PATH)/agnostic/gen9/vp/hal \
    $(LOCAL_PATH)/agnostic/gen9/vp/kernel \
    $(LOCAL_PATH)/agnostic/gen9_bxt/codec/hal \
    $(LOCAL_PATH)/agnostic/gen9_bxt/codec/kernel \
    $(LOCAL_PATH)/agnostic/gen9_bxt/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen9_bxt/media_interfaces \
    $(LOCAL_PATH)/agnostic/gen9_bxt/vp/hal \
    $(LOCAL_PATH)/agnostic/gen9_skl/codec/hal \
    $(LOCAL_PATH)/agnostic/gen9_skl/codec/cmrt_kernel \
    $(LOCAL_PATH)/agnostic/gen9_skl/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen9_skl/media_interfaces \
    $(LOCAL_PATH)/agnostic/gen9_cfl/media_interfaces \
    $(LOCAL_PATH)/agnostic/gen9_glk/codec/hal \
    $(LOCAL_PATH)/agnostic/gen9_glk/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen9_glk/media_interfaces \
    $(LOCAL_PATH)/agnostic/gen9_glk/vp/hal \
    $(LOCAL_PATH)/agnostic/gen9_kbl/codec/hal \
    $(LOCAL_PATH)/agnostic/gen9_kbl/codec/kernel \
    $(LOCAL_PATH)/agnostic/gen9_kbl/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen9_kbl/media_interfaces \
    $(LOCAL_PATH)/agnostic/gen10/cm \
    $(LOCAL_PATH)/agnostic/gen10/codec/hal \
    $(LOCAL_PATH)/agnostic/gen10/codec/kernel \
    $(LOCAL_PATH)/agnostic/gen10/codec/share \
    $(LOCAL_PATH)/agnostic/gen10/hw/vdbox \
    $(LOCAL_PATH)/agnostic/gen10/hw \
    $(LOCAL_PATH)/agnostic/gen10/renderhal \
    $(LOCAL_PATH)/agnostic/gen10/vp/hal \
    $(LOCAL_PATH)/agnostic/gen10/vp/kernel \
    $(LOCAL_PATH)/agnostic/gen10_cnl/media_interfaces \
    $(LOCAL_PATH)/linux/common/cm \
    $(LOCAL_PATH)/linux/common/codec/ddi \
    $(LOCAL_PATH)/linux/common/codec/hal \
    $(LOCAL_PATH)/linux/common/cp/ddi \
    $(LOCAL_PATH)/linux/common/cp/hw \
    $(LOCAL_PATH)/linux/common/cp/os \
    $(LOCAL_PATH)/linux/common/ddi \
    $(LOCAL_PATH)/linux/common/os \
    $(LOCAL_PATH)/linux/common/vp/ddi \
    $(LOCAL_PATH)/linux/gen8/ddi \
    $(LOCAL_PATH)/linux/gen9/ddi \
    $(LOCAL_PATH)/linux/gen9_bxt/ddi \
    $(LOCAL_PATH)/linux/gen9_skl/ddi \
    $(LOCAL_PATH)/linux/gen9_kbl/ddi \
    $(LOCAL_PATH)/linux/gen9_glk/ddi \
    $(LOCAL_PATH)/linux/gen9_cfl/ddi \
    $(LOCAL_PATH)/linux/gen10/ddi \
    $(LOCAL_PATH)/linux/gen10_cnl/ddi \
    $(LOCAL_PATH)/../../gmmlib/Source/inc/common \


#LOCAL_HEADER_LIBRARIES := ufo_inc_headers libgui_headers

#LOCAL_CPP_FEATURES := rtti exceptions

LOCAL_MODULE := i965_drv_video
LOCAL_PROPRIETARY_MODULE := true

include $(BUILD_SHARED_LIBRARY)
