/*
* Copyright (c) 2017, Intel Corporation
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
* OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*/
                                                                                       
////////////////////////////////////////////////////////////////////////////////       
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!                        
// Generated by GenKrnBin.exe tool                                                     
////////////////////////////////////////////////////////////////////////////////       
#ifndef __VPKRNHEADER_H__
#define __VPKRNHEADER_H__

#define IDR_VP_LINKFILE_VERSION 65536
#define IDR_VP_LINKFILE_HEADER 16

#define IDR_VP_3DLUT 0
#define IDR_VP_AlphaSrcBlendG 1
#define IDR_VP_ByteCopy 2
#define IDR_VP_ByteCopy_MediaWalker 3
#define IDR_VP_CSC_444_16 4
#define IDR_VP_CSC_Premultiplied_444_16 5
#define IDR_VP_Call_AlphaSrcBlendG 6
#define IDR_VP_Call_CSC 7
#define IDR_VP_Call_CSC_Premultiplied 8
#define IDR_VP_Call_ColorE 9
#define IDR_VP_Call_Composite 10
#define IDR_VP_Call_ConstBlend 11
#define IDR_VP_Call_ConstSrcBlend 12
#define IDR_VP_Call_GammaC 13
#define IDR_VP_Call_Mirror_H_YUV 14
#define IDR_VP_Call_Mirror_H_YUVA 15
#define IDR_VP_Call_PartBlend 16
#define IDR_VP_Call_SrcBlend 17
#define IDR_VP_Call_SrcBlend_4bits 18
#define IDR_VP_ColorE 19
#define IDR_VP_Colorfill_444AVS16 20
#define IDR_VP_Colorfill_444AVS16_ConstBlend 21
#define IDR_VP_Colorfill_444AVS16_ConstSrcBlend 22
#define IDR_VP_Colorfill_444AVS16_PartBlend 23
#define IDR_VP_Colorfill_444AVS16_SrcBlend 24
#define IDR_VP_Colorfill_444Scale16 25
#define IDR_VP_Colorfill_444Scale16_ConstBlend 26
#define IDR_VP_Colorfill_444Scale16_ConstSrcBlend 27
#define IDR_VP_Colorfill_444Scale16_PartBlend 28
#define IDR_VP_Colorfill_444Scale16_SrcBlend 29
#define IDR_VP_Composite_444_16 30
#define IDR_VP_Compute_Lumakey 31
#define IDR_VP_Compute_Lumakey_Buf0123 32
#define IDR_VP_ConstBlend_444_16 33
#define IDR_VP_ConstSrcBlend_444_16 34
#define IDR_VP_Crypto_Block_Copy 35
#define IDR_VP_EOT 36
#define IDR_VP_FMD_Summation 37
#define IDR_VP_FRC_Clean_Map 38
#define IDR_VP_FRC_GMV_Detection 39
#define IDR_VP_FRC_GMV_Sanity_Check 40
#define IDR_VP_FRC_GradUV 41
#define IDR_VP_FRC_GradY 42
#define IDR_VP_FRC_MC 43
#define IDR_VP_FRC_ME_Level1 44
#define IDR_VP_FRC_ME_Level2 45
#define IDR_VP_FRC_ME_Level3 46
#define IDR_VP_FRC_MV_Level1 47
#define IDR_VP_FRC_MV_Level2 48
#define IDR_VP_FRC_MV_Level3 49
#define IDR_VP_FRC_PS 50
#define IDR_VP_FRC_SPD_Map 51
#define IDR_VP_FRC_TempDiff 52
#define IDR_VP_FRC_TempDiff_HD 53
#define IDR_VP_FRC_WSD 54
#define IDR_VP_GammaC 55
#define IDR_VP_GeoCorrection 56
#define IDR_VP_HDR_mandatory 57
#define IDR_VP_HDR_per_frame_stat 58
#define IDR_VP_IS_DS 59
#define IDR_VP_IS_FW 60
#define IDR_VP_IS_GMC 61
#define IDR_VP_IS_ME 62
#define IDR_VP_Interlace_420_16_Buf_0 63
#define IDR_VP_Interlace_420_16_Buf_1 64
#define IDR_VP_Interlace_420_16_Buf_2 65
#define IDR_VP_Interlace_420_16_Buf_3 66
#define IDR_VP_Interlace_444AVS16_Buf_0 67
#define IDR_VP_Interlace_444AVS16_Buf_1 68
#define IDR_VP_Interlace_444AVS16_Buf_2 69
#define IDR_VP_Interlace_444AVS16_Buf_3 70
#define IDR_VP_Interlace_444_16_Buf_0 71
#define IDR_VP_Interlace_444_16_Buf_1 72
#define IDR_VP_Interlace_444_16_Buf_2 73
#define IDR_VP_Interlace_444_16_Buf_3 74
#define IDR_VP_LACE_HIST_SUM 75
#define IDR_VP_LACE_LUT 76
#define IDR_VP_LACE_PWLF 77
#define IDR_VP_LACE_STD 78
#define IDR_VP_LinkFile 79
#define IDR_VP_Mirror_AVS_H_L0 80
#define IDR_VP_Mirror_AVS_V_L0 81
#define IDR_VP_Mirror_H_YUV 82
#define IDR_VP_Mirror_H_YUVA 83
#define IDR_VP_Mirror_scale_H_L0 84
#define IDR_VP_Mirror_scale_V_L0 85
#define IDR_VP_NV12_DP_rotation_avg 86
#define IDR_VP_NV12_DP_rotation_nv12 87
#define IDR_VP_NV12_DP_rotation_rep 88
#define IDR_VP_P010_444Dscale16_Buf_0 89
#define IDR_VP_P010_444Dscale16_Buf_0_Rot_180 90
#define IDR_VP_P010_444Dscale16_Buf_0_Rot_270 91
#define IDR_VP_P010_444Dscale16_Buf_0_Rot_90 92
#define IDR_VP_P010_444Dscale16_Buf_1 93
#define IDR_VP_P010_444Dscale16_Buf_1_Rot_180 94
#define IDR_VP_P010_444Dscale16_Buf_1_Rot_270 95
#define IDR_VP_P010_444Dscale16_Buf_1_Rot_90 96
#define IDR_VP_P010_444Dscale16_Buf_2 97
#define IDR_VP_P010_444Dscale16_Buf_2_Rot_180 98
#define IDR_VP_P010_444Dscale16_Buf_2_Rot_270 99
#define IDR_VP_P010_444Dscale16_Buf_2_Rot_90 100
#define IDR_VP_P010_444Dscale16_Buf_3 101
#define IDR_VP_P010_444Dscale16_Buf_3_Rot_180 102
#define IDR_VP_P010_444Dscale16_Buf_3_Rot_270 103
#define IDR_VP_P010_444Dscale16_Buf_3_Rot_90 104
#define IDR_VP_PA_444AVS16_Buf_0 105
#define IDR_VP_PA_444AVS16_Buf_0_Rot_180 106
#define IDR_VP_PA_444AVS16_Buf_0_Rot_270 107
#define IDR_VP_PA_444AVS16_Buf_0_Rot_90 108
#define IDR_VP_PA_444AVS16_Buf_1 109
#define IDR_VP_PA_444AVS16_Buf_1_Rot_180 110
#define IDR_VP_PA_444AVS16_Buf_1_Rot_270 111
#define IDR_VP_PA_444AVS16_Buf_1_Rot_90 112
#define IDR_VP_PA_444AVS16_Buf_2 113
#define IDR_VP_PA_444AVS16_Buf_2_Rot_180 114
#define IDR_VP_PA_444AVS16_Buf_2_Rot_270 115
#define IDR_VP_PA_444AVS16_Buf_2_Rot_90 116
#define IDR_VP_PA_444AVS16_Buf_3 117
#define IDR_VP_PA_444AVS16_Buf_3_Rot_180 118
#define IDR_VP_PA_444AVS16_Buf_3_Rot_270 119
#define IDR_VP_PA_444AVS16_Buf_3_Rot_90 120
#define IDR_VP_PA_444AVS16_Buf_4 121
#define IDR_VP_PA_444AVS16_Buf_4_Rot_180 122
#define IDR_VP_PA_444AVS16_Buf_4_Rot_270 123
#define IDR_VP_PA_444AVS16_Buf_4_Rot_90 124
#define IDR_VP_PA_444AVS16_Buf_5 125
#define IDR_VP_PA_444AVS16_Buf_5_Rot_180 126
#define IDR_VP_PA_444AVS16_Buf_5_Rot_270 127
#define IDR_VP_PA_444AVS16_Buf_5_Rot_90 128
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_0 129
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_1 130
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_2 131
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_3 132
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_0 133
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_1 134
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_2 135
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_3 136
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_0 137
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_1 138
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_2 139
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_3 140
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_0 141
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_1 142
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_2 143
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_3 144
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_0 145
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_1 146
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_2 147
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_3 148
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_0 149
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_1 150
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_2 151
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_3 152
#define IDR_VP_PA_444DScale16_Buf_0 153
#define IDR_VP_PA_444DScale16_Buf_1 154
#define IDR_VP_PA_444DScale16_Buf_2 155
#define IDR_VP_PA_444DScale16_Buf_3 156
#define IDR_VP_PA_444DScale16_Buf_4 157
#define IDR_VP_PA_444DScale16_Buf_5 158
#define IDR_VP_PA_444Dscale16_Buf_0_Rot_180 159
#define IDR_VP_PA_444Dscale16_Buf_0_Rot_270 160
#define IDR_VP_PA_444Dscale16_Buf_0_Rot_90 161
#define IDR_VP_PA_444Dscale16_Buf_1_Rot_180 162
#define IDR_VP_PA_444Dscale16_Buf_1_Rot_270 163
#define IDR_VP_PA_444Dscale16_Buf_1_Rot_90 164
#define IDR_VP_PA_444Dscale16_Buf_2_Rot_180 165
#define IDR_VP_PA_444Dscale16_Buf_2_Rot_270 166
#define IDR_VP_PA_444Dscale16_Buf_2_Rot_90 167
#define IDR_VP_PA_444Dscale16_Buf_3_Rot_180 168
#define IDR_VP_PA_444Dscale16_Buf_3_Rot_270 169
#define IDR_VP_PA_444Dscale16_Buf_3_Rot_90 170
#define IDR_VP_PA_444Scale16_Buf_0 171
#define IDR_VP_PA_444Scale16_Buf_0_Rot_180 172
#define IDR_VP_PA_444Scale16_Buf_0_Rot_270 173
#define IDR_VP_PA_444Scale16_Buf_0_Rot_90 174
#define IDR_VP_PA_444Scale16_Buf_1 175
#define IDR_VP_PA_444Scale16_Buf_1_Rot_180 176
#define IDR_VP_PA_444Scale16_Buf_1_Rot_270 177
#define IDR_VP_PA_444Scale16_Buf_1_Rot_90 178
#define IDR_VP_PA_444Scale16_Buf_2 179
#define IDR_VP_PA_444Scale16_Buf_2_Rot_180 180
#define IDR_VP_PA_444Scale16_Buf_2_Rot_270 181
#define IDR_VP_PA_444Scale16_Buf_2_Rot_90 182
#define IDR_VP_PA_444Scale16_Buf_3 183
#define IDR_VP_PA_444Scale16_Buf_3_Rot_180 184
#define IDR_VP_PA_444Scale16_Buf_3_Rot_270 185
#define IDR_VP_PA_444Scale16_Buf_3_Rot_90 186
#define IDR_VP_PA_444Scale16_Buf_4 187
#define IDR_VP_PA_444Scale16_Buf_4_Rot_180 188
#define IDR_VP_PA_444Scale16_Buf_4_Rot_270 189
#define IDR_VP_PA_444Scale16_Buf_4_Rot_90 190
#define IDR_VP_PA_444Scale16_Buf_5 191
#define IDR_VP_PA_444Scale16_Buf_5_Rot_180 192
#define IDR_VP_PA_444Scale16_Buf_5_Rot_270 193
#define IDR_VP_PA_444Scale16_Buf_5_Rot_90 194
#define IDR_VP_PA_444iAVS16_Buf_0 195
#define IDR_VP_PA_444iAVS16_Buf_1 196
#define IDR_VP_PA_444iAVS16_Buf_2 197
#define IDR_VP_PA_444iAVS16_Buf_3 198
#define IDR_VP_PA_444iDScale16_Buf_0 199
#define IDR_VP_PA_444iDScale16_Buf_1 200
#define IDR_VP_PA_444iDScale16_Buf_2 201
#define IDR_VP_PA_444iDScale16_Buf_3 202
#define IDR_VP_PA_444iScale16_Buf_0 203
#define IDR_VP_PA_444iScale16_Buf_0_Rot_180 204
#define IDR_VP_PA_444iScale16_Buf_0_Rot_270 205
#define IDR_VP_PA_444iScale16_Buf_0_Rot_90 206
#define IDR_VP_PA_444iScale16_Buf_1 207
#define IDR_VP_PA_444iScale16_Buf_1_Rot_180 208
#define IDR_VP_PA_444iScale16_Buf_1_Rot_270 209
#define IDR_VP_PA_444iScale16_Buf_1_Rot_90 210
#define IDR_VP_PA_444iScale16_Buf_2 211
#define IDR_VP_PA_444iScale16_Buf_2_Rot_180 212
#define IDR_VP_PA_444iScale16_Buf_2_Rot_270 213
#define IDR_VP_PA_444iScale16_Buf_2_Rot_90 214
#define IDR_VP_PA_444iScale16_Buf_3 215
#define IDR_VP_PA_444iScale16_Buf_3_Rot_180 216
#define IDR_VP_PA_444iScale16_Buf_3_Rot_270 217
#define IDR_VP_PA_444iScale16_Buf_3_Rot_90 218
#define IDR_VP_PA_AVS_Mirror_H_L0 219
#define IDR_VP_PA_AVS_Mirror_V_L0 220
#define IDR_VP_PA_AVS_Rotate_90_Mirror_H_L0 221
#define IDR_VP_PA_AVS_Rotate_90_Mirror_V_L0 222
#define IDR_VP_PA_AVS_Rotate_L0_180 223
#define IDR_VP_PA_AVS_Rotate_L0_270 224
#define IDR_VP_PA_AVS_Rotate_L0_90 225
#define IDR_VP_PA_Copy 226
#define IDR_VP_PA_Scale_Mirror_H_L0 227
#define IDR_VP_PA_Scale_Mirror_V_L0 228
#define IDR_VP_PA_Scale_Rotate90_Mirror_H_L0 229
#define IDR_VP_PA_Scale_Rotate90_Mirror_V_L0 230
#define IDR_VP_PA_Scale_Rotate_L0_180 231
#define IDR_VP_PA_Scale_Rotate_L0_270 232
#define IDR_VP_PA_Scale_Rotate_L0_90 233
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_0 234
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_1 235
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_2 236
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_3 237
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_4 238
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_5 239
#define IDR_VP_PL2_444AVS16_Buf_0 240
#define IDR_VP_PL2_444AVS16_Buf_0_Rot_180 241
#define IDR_VP_PL2_444AVS16_Buf_0_Rot_270 242
#define IDR_VP_PL2_444AVS16_Buf_0_Rot_90 243
#define IDR_VP_PL2_444AVS16_Buf_1 244
#define IDR_VP_PL2_444AVS16_Buf_1_Rot_180 245
#define IDR_VP_PL2_444AVS16_Buf_1_Rot_270 246
#define IDR_VP_PL2_444AVS16_Buf_1_Rot_90 247
#define IDR_VP_PL2_444AVS16_Buf_2 248
#define IDR_VP_PL2_444AVS16_Buf_2_Rot_180 249
#define IDR_VP_PL2_444AVS16_Buf_2_Rot_270 250
#define IDR_VP_PL2_444AVS16_Buf_2_Rot_90 251
#define IDR_VP_PL2_444AVS16_Buf_3 252
#define IDR_VP_PL2_444AVS16_Buf_3_Rot_180 253
#define IDR_VP_PL2_444AVS16_Buf_3_Rot_270 254
#define IDR_VP_PL2_444AVS16_Buf_3_Rot_90 255
#define IDR_VP_PL2_444AVS16_Buf_4 256
#define IDR_VP_PL2_444AVS16_Buf_4_Rot_180 257
#define IDR_VP_PL2_444AVS16_Buf_4_Rot_270 258
#define IDR_VP_PL2_444AVS16_Buf_4_Rot_90 259
#define IDR_VP_PL2_444AVS16_Buf_5 260
#define IDR_VP_PL2_444AVS16_Buf_5_Rot_180 261
#define IDR_VP_PL2_444AVS16_Buf_5_Rot_270 262
#define IDR_VP_PL2_444AVS16_Buf_5_Rot_90 263
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4 264
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4_Rot_180 265
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4_Rot_270 266
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4_Rot_90 267
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5 268
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5_Rot_180 269
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5_Rot_270 270
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5_Rot_90 271
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_0 272
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_1 273
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_2 274
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_3 275
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_4 276
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_5 277
#define IDR_VP_PL2_444Dscale16_Buf_0 278
#define IDR_VP_PL2_444Dscale16_Buf_0_Rot_180 279
#define IDR_VP_PL2_444Dscale16_Buf_0_Rot_270 280
#define IDR_VP_PL2_444Dscale16_Buf_0_Rot_90 281
#define IDR_VP_PL2_444Dscale16_Buf_1 282
#define IDR_VP_PL2_444Dscale16_Buf_1_Rot_180 283
#define IDR_VP_PL2_444Dscale16_Buf_1_Rot_270 284
#define IDR_VP_PL2_444Dscale16_Buf_1_Rot_90 285
#define IDR_VP_PL2_444Dscale16_Buf_2 286
#define IDR_VP_PL2_444Dscale16_Buf_2_Rot_180 287
#define IDR_VP_PL2_444Dscale16_Buf_2_Rot_270 288
#define IDR_VP_PL2_444Dscale16_Buf_2_Rot_90 289
#define IDR_VP_PL2_444Dscale16_Buf_3 290
#define IDR_VP_PL2_444Dscale16_Buf_3_Rot_180 291
#define IDR_VP_PL2_444Dscale16_Buf_3_Rot_270 292
#define IDR_VP_PL2_444Dscale16_Buf_3_Rot_90 293
#define IDR_VP_PL2_444Dscale16_Buf_4 294
#define IDR_VP_PL2_444Dscale16_Buf_5 295
#define IDR_VP_PL2_444Dscale16_Buf_Sep_Alpha_4 296
#define IDR_VP_PL2_444Dscale16_Buf_Sep_Alpha_5 297
#define IDR_VP_PL2_444Scale16_Buf_0 298
#define IDR_VP_PL2_444Scale16_Buf_0_Rot_180 299
#define IDR_VP_PL2_444Scale16_Buf_0_Rot_270 300
#define IDR_VP_PL2_444Scale16_Buf_0_Rot_90 301
#define IDR_VP_PL2_444Scale16_Buf_1 302
#define IDR_VP_PL2_444Scale16_Buf_1_Rot_180 303
#define IDR_VP_PL2_444Scale16_Buf_1_Rot_270 304
#define IDR_VP_PL2_444Scale16_Buf_1_Rot_90 305
#define IDR_VP_PL2_444Scale16_Buf_2 306
#define IDR_VP_PL2_444Scale16_Buf_2_Rot_180 307
#define IDR_VP_PL2_444Scale16_Buf_2_Rot_270 308
#define IDR_VP_PL2_444Scale16_Buf_2_Rot_90 309
#define IDR_VP_PL2_444Scale16_Buf_3 310
#define IDR_VP_PL2_444Scale16_Buf_3_Rot_180 311
#define IDR_VP_PL2_444Scale16_Buf_3_Rot_270 312
#define IDR_VP_PL2_444Scale16_Buf_3_Rot_90 313
#define IDR_VP_PL2_444Scale16_Buf_4 314
#define IDR_VP_PL2_444Scale16_Buf_4_Rot_180 315
#define IDR_VP_PL2_444Scale16_Buf_4_Rot_270 316
#define IDR_VP_PL2_444Scale16_Buf_4_Rot_90 317
#define IDR_VP_PL2_444Scale16_Buf_5 318
#define IDR_VP_PL2_444Scale16_Buf_5_Rot_180 319
#define IDR_VP_PL2_444Scale16_Buf_5_Rot_270 320
#define IDR_VP_PL2_444Scale16_Buf_5_Rot_90 321
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4 322
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4_Rot_180 323
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4_Rot_270 324
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4_Rot_90 325
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5 326
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5_Rot_180 327
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5_Rot_270 328
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5_Rot_90 329
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0 330
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0_Rot_180 331
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0_Rot_270 332
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0_Rot_90 333
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1 334
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1_Rot_180 335
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1_Rot_270 336
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1_Rot_90 337
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2 338
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2_Rot_180 339
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2_Rot_270 340
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2_Rot_90 341
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3 342
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3_Rot_180 343
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3_Rot_270 344
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3_Rot_90 345
#define IDR_VP_PL2_444iDScale16_Buf_0 346
#define IDR_VP_PL2_444iDScale16_Buf_1 347
#define IDR_VP_PL2_444iDScale16_Buf_2 348
#define IDR_VP_PL2_444iDScale16_Buf_3 349
#define IDR_VP_PL2_444iScale16_Buf_0 350
#define IDR_VP_PL2_444iScale16_Buf_0_Rot_180 351
#define IDR_VP_PL2_444iScale16_Buf_0_Rot_270 352
#define IDR_VP_PL2_444iScale16_Buf_0_Rot_90 353
#define IDR_VP_PL2_444iScale16_Buf_1 354
#define IDR_VP_PL2_444iScale16_Buf_1_Rot_180 355
#define IDR_VP_PL2_444iScale16_Buf_1_Rot_270 356
#define IDR_VP_PL2_444iScale16_Buf_1_Rot_90 357
#define IDR_VP_PL2_444iScale16_Buf_2 358
#define IDR_VP_PL2_444iScale16_Buf_2_Rot_180 359
#define IDR_VP_PL2_444iScale16_Buf_2_Rot_270 360
#define IDR_VP_PL2_444iScale16_Buf_2_Rot_90 361
#define IDR_VP_PL2_444iScale16_Buf_3 362
#define IDR_VP_PL2_444iScale16_Buf_3_Rot_180 363
#define IDR_VP_PL2_444iScale16_Buf_3_Rot_270 364
#define IDR_VP_PL2_444iScale16_Buf_3_Rot_90 365
#define IDR_VP_PL2_AVS_Mirror_H_L0 366
#define IDR_VP_PL2_AVS_Mirror_H_L0_DualOutput 367
#define IDR_VP_PL2_AVS_Mirror_V_L0 368
#define IDR_VP_PL2_AVS_Rotate90_Mirror_H_L0 369
#define IDR_VP_PL2_AVS_Rotate90_Mirror_V_L0 370
#define IDR_VP_PL2_AVS_Rotate_L0_180 371
#define IDR_VP_PL2_AVS_Rotate_L0_270 372
#define IDR_VP_PL2_AVS_Rotate_L0_90 373
#define IDR_VP_PL2_Copy 374
#define IDR_VP_PL2_Scale_Mirror_H_L0 375
#define IDR_VP_PL2_Scale_Mirror_H_L0_DualOutput 376
#define IDR_VP_PL2_Scale_Mirror_V_L0 377
#define IDR_VP_PL2_Scale_Rotate90_Mirror_H_L0 378
#define IDR_VP_PL2_Scale_Rotate90_Mirror_V_L0 379
#define IDR_VP_PL2_Scale_Rotate_L0_180 380
#define IDR_VP_PL2_Scale_Rotate_L0_270 381
#define IDR_VP_PL2_Scale_Rotate_L0_90 382
#define IDR_VP_PL3_444AVS16_Buf_0 383
#define IDR_VP_PL3_444AVS16_Buf_0_Rot_180 384
#define IDR_VP_PL3_444AVS16_Buf_0_Rot_270 385
#define IDR_VP_PL3_444AVS16_Buf_0_Rot_90 386
#define IDR_VP_PL3_444AVS16_Buf_1 387
#define IDR_VP_PL3_444AVS16_Buf_1_Rot_180 388
#define IDR_VP_PL3_444AVS16_Buf_1_Rot_270 389
#define IDR_VP_PL3_444AVS16_Buf_1_Rot_90 390
#define IDR_VP_PL3_444AVS16_Buf_2 391
#define IDR_VP_PL3_444AVS16_Buf_2_Rot_180 392
#define IDR_VP_PL3_444AVS16_Buf_2_Rot_270 393
#define IDR_VP_PL3_444AVS16_Buf_2_Rot_90 394
#define IDR_VP_PL3_444AVS16_Buf_3 395
#define IDR_VP_PL3_444AVS16_Buf_3_Rot_180 396
#define IDR_VP_PL3_444AVS16_Buf_3_Rot_270 397
#define IDR_VP_PL3_444AVS16_Buf_3_Rot_90 398
#define IDR_VP_PL3_444AVS16_Buf_4 399
#define IDR_VP_PL3_444AVS16_Buf_4_Rot_180 400
#define IDR_VP_PL3_444AVS16_Buf_4_Rot_270 401
#define IDR_VP_PL3_444AVS16_Buf_4_Rot_90 402
#define IDR_VP_PL3_444AVS16_Buf_5 403
#define IDR_VP_PL3_444AVS16_Buf_5_Rot_180 404
#define IDR_VP_PL3_444AVS16_Buf_5_Rot_270 405
#define IDR_VP_PL3_444AVS16_Buf_5_Rot_90 406
#define IDR_VP_PL3_444DScale16_Buf_0 407
#define IDR_VP_PL3_444DScale16_Buf_1 408
#define IDR_VP_PL3_444DScale16_Buf_2 409
#define IDR_VP_PL3_444DScale16_Buf_3 410
#define IDR_VP_PL3_444DScale16_Buf_4 411
#define IDR_VP_PL3_444DScale16_Buf_5 412
#define IDR_VP_PL3_444Dscale16_Buf_0_Rot_180 413
#define IDR_VP_PL3_444Dscale16_Buf_0_Rot_270 414
#define IDR_VP_PL3_444Dscale16_Buf_0_Rot_90 415
#define IDR_VP_PL3_444Dscale16_Buf_1_Rot_180 416
#define IDR_VP_PL3_444Dscale16_Buf_1_Rot_270 417
#define IDR_VP_PL3_444Dscale16_Buf_1_Rot_90 418
#define IDR_VP_PL3_444Dscale16_Buf_2_Rot_180 419
#define IDR_VP_PL3_444Dscale16_Buf_2_Rot_270 420
#define IDR_VP_PL3_444Dscale16_Buf_2_Rot_90 421
#define IDR_VP_PL3_444Dscale16_Buf_3_Rot_180 422
#define IDR_VP_PL3_444Dscale16_Buf_3_Rot_270 423
#define IDR_VP_PL3_444Dscale16_Buf_3_Rot_90 424
#define IDR_VP_PL3_444Scale16_Buf_0 425
#define IDR_VP_PL3_444Scale16_Buf_0_Rot_180 426
#define IDR_VP_PL3_444Scale16_Buf_0_Rot_270 427
#define IDR_VP_PL3_444Scale16_Buf_0_Rot_90 428
#define IDR_VP_PL3_444Scale16_Buf_1 429
#define IDR_VP_PL3_444Scale16_Buf_1_Rot_180 430
#define IDR_VP_PL3_444Scale16_Buf_1_Rot_270 431
#define IDR_VP_PL3_444Scale16_Buf_1_Rot_90 432
#define IDR_VP_PL3_444Scale16_Buf_2 433
#define IDR_VP_PL3_444Scale16_Buf_2_Rot_180 434
#define IDR_VP_PL3_444Scale16_Buf_2_Rot_270 435
#define IDR_VP_PL3_444Scale16_Buf_2_Rot_90 436
#define IDR_VP_PL3_444Scale16_Buf_3 437
#define IDR_VP_PL3_444Scale16_Buf_3_Rot_180 438
#define IDR_VP_PL3_444Scale16_Buf_3_Rot_270 439
#define IDR_VP_PL3_444Scale16_Buf_3_Rot_90 440
#define IDR_VP_PL3_444Scale16_Buf_4 441
#define IDR_VP_PL3_444Scale16_Buf_4_Rot_180 442
#define IDR_VP_PL3_444Scale16_Buf_4_Rot_270 443
#define IDR_VP_PL3_444Scale16_Buf_4_Rot_90 444
#define IDR_VP_PL3_444Scale16_Buf_5 445
#define IDR_VP_PL3_444Scale16_Buf_5_Rot_180 446
#define IDR_VP_PL3_444Scale16_Buf_5_Rot_270 447
#define IDR_VP_PL3_444Scale16_Buf_5_Rot_90 448
#define IDR_VP_PL3_444iDScale16_Buf_0 449
#define IDR_VP_PL3_444iDScale16_Buf_1 450
#define IDR_VP_PL3_444iDScale16_Buf_2 451
#define IDR_VP_PL3_444iDScale16_Buf_3 452
#define IDR_VP_PL3_444iScale16_Buf_0 453
#define IDR_VP_PL3_444iScale16_Buf_0_Rot_180 454
#define IDR_VP_PL3_444iScale16_Buf_0_Rot_270 455
#define IDR_VP_PL3_444iScale16_Buf_0_Rot_90 456
#define IDR_VP_PL3_444iScale16_Buf_1 457
#define IDR_VP_PL3_444iScale16_Buf_1_Rot_180 458
#define IDR_VP_PL3_444iScale16_Buf_1_Rot_270 459
#define IDR_VP_PL3_444iScale16_Buf_1_Rot_90 460
#define IDR_VP_PL3_444iScale16_Buf_2 461
#define IDR_VP_PL3_444iScale16_Buf_2_Rot_180 462
#define IDR_VP_PL3_444iScale16_Buf_2_Rot_270 463
#define IDR_VP_PL3_444iScale16_Buf_2_Rot_90 464
#define IDR_VP_PL3_444iScale16_Buf_3 465
#define IDR_VP_PL3_444iScale16_Buf_3_Rot_180 466
#define IDR_VP_PL3_444iScale16_Buf_3_Rot_270 467
#define IDR_VP_PL3_444iScale16_Buf_3_Rot_90 468
#define IDR_VP_PL3_AVS_Rotate_L0_180 469
#define IDR_VP_PL3_AVS_Rotate_L0_270 470
#define IDR_VP_PL3_AVS_Rotate_L0_90 471
#define IDR_VP_PL3_Scale_Rotate_L0_180 472
#define IDR_VP_PL3_Scale_Rotate_L0_270 473
#define IDR_VP_PL3_Scale_Rotate_L0_90 474
#define IDR_VP_PLY_444DScale16_2f_Buf_0 475
#define IDR_VP_PLY_444DScale16_2f_Buf_1 476
#define IDR_VP_PLY_444DScale16_2f_Buf_2 477
#define IDR_VP_PLY_444DScale16_2f_Buf_3 478
#define IDR_VP_PLY_444DScale16_Buf_0 479
#define IDR_VP_PLY_444DScale16_Buf_0_Rot_180 480
#define IDR_VP_PLY_444DScale16_Buf_0_Rot_270 481
#define IDR_VP_PLY_444DScale16_Buf_0_Rot_90 482
#define IDR_VP_PLY_444DScale16_Buf_1 483
#define IDR_VP_PLY_444DScale16_Buf_1_Rot_180 484
#define IDR_VP_PLY_444DScale16_Buf_1_Rot_270 485
#define IDR_VP_PLY_444DScale16_Buf_1_Rot_90 486
#define IDR_VP_PLY_444DScale16_Buf_2 487
#define IDR_VP_PLY_444DScale16_Buf_2_Rot_180 488
#define IDR_VP_PLY_444DScale16_Buf_2_Rot_270 489
#define IDR_VP_PLY_444DScale16_Buf_2_Rot_90 490
#define IDR_VP_PLY_444DScale16_Buf_3 491
#define IDR_VP_PLY_444DScale16_Buf_3_Rot_180 492
#define IDR_VP_PLY_444DScale16_Buf_3_Rot_270 493
#define IDR_VP_PLY_444DScale16_Buf_3_Rot_90 494
#define IDR_VP_PartBlend_444_16 495
#define IDR_VP_Prepare_LumaKey_SampleUnorm 496
#define IDR_VP_RGB2sRGB 497
#define IDR_VP_Rotate_90_Mirror_AVS_H_L0 498
#define IDR_VP_Rotate_90_Mirror_AVS_V_L0 499
#define IDR_VP_Rotate_90_Mirror_H_scale_L0 500
#define IDR_VP_Rotate_90_Mirror_V_scale_L0 501
#define IDR_VP_Rotate_AVS_L0_180 502
#define IDR_VP_Rotate_AVS_L0_270 503
#define IDR_VP_Rotate_AVS_L0_90 504
#define IDR_VP_Rotate_Scale_L0_180 505
#define IDR_VP_Rotate_Scale_L0_270 506
#define IDR_VP_Rotate_Scale_L0_90 507
#define IDR_VP_SIP_Debug 508
#define IDR_VP_Save_444AVS16_ARGB 509
#define IDR_VP_Save_444AVS16_ARGB_64Byte 510
#define IDR_VP_Save_444AVS16_NV12 511
#define IDR_VP_Save_444AVS16_NV21 512
#define IDR_VP_Save_444AVS16_PA 513
#define IDR_VP_Save_444AVS16_PL3 514
#define IDR_VP_Save_444AVS16_R10G10B10 515
#define IDR_VP_Save_444AVS16_R10G10B10A2 516
#define IDR_VP_Save_444AVS16_R10G10B10X2 517
#define IDR_VP_Save_444AVS16_RGB 518
#define IDR_VP_Save_444AVS16_RGB16 519
#define IDR_VP_Save_444AVS16_RGB_64Byte 520
#define IDR_VP_Save_444AVS16_SrcAYUV 521
#define IDR_VP_Save_444AVS16_XRGB 522
#define IDR_VP_Save_444AVS16_XRGB_64Byte 523
#define IDR_VP_Save_444SCALE16_ARGB_64Byte 524
#define IDR_VP_Save_444SCALE16_NV21 525
#define IDR_VP_Save_444SCALE16_RGB_64Byte 526
#define IDR_VP_Save_444SCALE16_XRGB_64Byte 527
#define IDR_VP_Save_444Scale16_ARGB 528
#define IDR_VP_Save_444Scale16_ARGB_64Byte 529
#define IDR_VP_Save_444Scale16_Dither_NV12 530
#define IDR_VP_Save_444Scale16_Dither_NV21 531
#define IDR_VP_Save_444Scale16_Dither_PA 532
#define IDR_VP_Save_444Scale16_Dither_PA_32X16 533
#define IDR_VP_Save_444Scale16_Dither_PL3 534
#define IDR_VP_Save_444Scale16_Dither_RGB 535
#define IDR_VP_Save_444Scale16_Dither_RGB_64Byte 536
#define IDR_VP_Save_444Scale16_Dither_VUYA 537
#define IDR_VP_Save_444Scale16_Dither_XRGB 538
#define IDR_VP_Save_444Scale16_Dither_XRGB_64Byte 539
#define IDR_VP_Save_444Scale16_NV12 540
#define IDR_VP_Save_444Scale16_NV21 541
#define IDR_VP_Save_444Scale16_P010 542
#define IDR_VP_Save_444Scale16_PA 543
#define IDR_VP_Save_444Scale16_PA_32X16 544
#define IDR_VP_Save_444Scale16_PL3 545
#define IDR_VP_Save_444Scale16_PLY 546
#define IDR_VP_Save_444Scale16_R10G10B10 547
#define IDR_VP_Save_444Scale16_R10G10B10A2 548
#define IDR_VP_Save_444Scale16_R10G10B10X2 549
#define IDR_VP_Save_444Scale16_R10G10B10XR 550
#define IDR_VP_Save_444Scale16_R10G10B10XRA2 551
#define IDR_VP_Save_444Scale16_R10G10B10XRX2 552
#define IDR_VP_Save_444Scale16_RGB 553
#define IDR_VP_Save_444Scale16_RGB16 554
#define IDR_VP_Save_444Scale16_RGB_64Byte 555
#define IDR_VP_Save_444Scale16_SrcVUYA 556
#define IDR_VP_Save_444Scale16_VUYA 557
#define IDR_VP_Save_444Scale16_XRGB 558
#define IDR_VP_Save_444Scale16_XRGB_64Byte 559
#define IDR_VP_Save_444Scale16_Y210 560
#define IDR_VP_Save_444Scale16_Y410 561
#define IDR_VP_Set_Buf0_Buf4 562
#define IDR_VP_Set_Buf1_Buf5 563
#define IDR_VP_Set_Buf2_Buf4 564
#define IDR_VP_Set_Buf3_Buf5 565
#define IDR_VP_Set_CSC_Src_Buf0 566
#define IDR_VP_Set_CSC_Src_Buf1 567
#define IDR_VP_Set_CSC_Src_Buf2 568
#define IDR_VP_Set_CSC_Src_Buf3 569
#define IDR_VP_Set_CSC_Src_Buf4 570
#define IDR_VP_Set_CSC_Src_Buf5 571
#define IDR_VP_Set_CURBE_CSC_Coeff 572
#define IDR_VP_Set_ColorE_Src_Buf0 573
#define IDR_VP_Set_ColorE_Src_Buf1 574
#define IDR_VP_Set_ColorE_Src_Buf2 575
#define IDR_VP_Set_ColorE_Src_Buf3 576
#define IDR_VP_Set_Dest_Surf_Indexes_Primary 577
#define IDR_VP_Set_Dest_Surf_Indexes_Secondary 578
#define IDR_VP_Set_GammaC_Src_Buf0 579
#define IDR_VP_Set_GammaC_Src_Buf1 580
#define IDR_VP_Set_GammaC_Src_Buf2 581
#define IDR_VP_Set_GammaC_Src_Buf3 582
#define IDR_VP_Set_Layer_0 583
#define IDR_VP_Set_Layer_1 584
#define IDR_VP_Set_Layer_1_AVS 585
#define IDR_VP_Set_Layer_2 586
#define IDR_VP_Set_Layer_3 587
#define IDR_VP_Set_Layer_4 588
#define IDR_VP_Set_Layer_5 589
#define IDR_VP_Set_Layer_6 590
#define IDR_VP_Set_Layer_7 591
#define IDR_VP_Set_Patched_CSC_Coeff 592
#define IDR_VP_Set_Scale_Buf_0123_Colorfill 593
#define IDR_VP_Set_Sec_Half_Buf45 594
#define IDR_VP_Shuffle_444AVS16_Buf_0 595
#define IDR_VP_Shuffle_444AVS16_Buf_1 596
#define IDR_VP_Shuffle_444AVS16_Buf_2 597
#define IDR_VP_Shuffle_444AVS16_Buf_3 598
#define IDR_VP_Shuffle_444AVS16_Buf_4 599
#define IDR_VP_Shuffle_444AVS16_Buf_5 600
#define IDR_VP_SrcBlend_444_16 601
#define IDR_VP_SrcBlend_4bits_444_16 602
#define IDR_VP_UpdateDNState 603
#define IDR_VP_VP_Setup 604
#define IDR_VP_VP_Setup_MediaWalker 605
#define IDR_VP_VP_Setup_MediaWalker_32X16_Design 606
#define IDR_VP_VP_Setup_MediaWalker_32x32_Color 607
#define IDR_VP_Y210_444DScale16_Buf_0 609
#define IDR_VP_Y210_444DScale16_Buf_0_Rot_180 610
#define IDR_VP_Y210_444DScale16_Buf_0_Rot_270 611
#define IDR_VP_Y210_444DScale16_Buf_0_Rot_90 612
#define IDR_VP_Y210_444DScale16_Buf_1 613
#define IDR_VP_Y210_444DScale16_Buf_1_Rot_180 614
#define IDR_VP_Y210_444DScale16_Buf_1_Rot_270 615
#define IDR_VP_Y210_444DScale16_Buf_1_Rot_90 616
#define IDR_VP_Y210_444DScale16_Buf_2 617
#define IDR_VP_Y210_444DScale16_Buf_2_Rot_180 618
#define IDR_VP_Y210_444DScale16_Buf_2_Rot_270 619
#define IDR_VP_Y210_444DScale16_Buf_2_Rot_90 620
#define IDR_VP_Y210_444DScale16_Buf_3 621
#define IDR_VP_Y210_444DScale16_Buf_3_Rot_180 622
#define IDR_VP_Y210_444DScale16_Buf_3_Rot_270 623
#define IDR_VP_Y210_444DScale16_Buf_3_Rot_90 624
#define IDR_VP_Y210_444DScale16_Buf_4 625
#define IDR_VP_Y210_444DScale16_Buf_4_Rot_180 626
#define IDR_VP_Y210_444DScale16_Buf_4_Rot_270 627
#define IDR_VP_Y210_444DScale16_Buf_4_Rot_90 628
#define IDR_VP_Y210_444DScale16_Buf_5 629
#define IDR_VP_Y210_444DScale16_Buf_5_Rot_180 630
#define IDR_VP_Y210_444DScale16_Buf_5_Rot_270 631
#define IDR_VP_Y210_444DScale16_Buf_5_Rot_90 632
#define IDR_VP_Y210_444Scale16_Buf_0 633
#define IDR_VP_Y210_444Scale16_Buf_0_Rot_180 634
#define IDR_VP_Y210_444Scale16_Buf_0_Rot_270 635
#define IDR_VP_Y210_444Scale16_Buf_0_Rot_90 636
#define IDR_VP_Y210_444Scale16_Buf_1 637
#define IDR_VP_Y210_444Scale16_Buf_1_Rot_180 638
#define IDR_VP_Y210_444Scale16_Buf_1_Rot_270 639
#define IDR_VP_Y210_444Scale16_Buf_1_Rot_90 640
#define IDR_VP_Y210_444Scale16_Buf_2 641
#define IDR_VP_Y210_444Scale16_Buf_2_Rot_180 642
#define IDR_VP_Y210_444Scale16_Buf_2_Rot_270 643
#define IDR_VP_Y210_444Scale16_Buf_2_Rot_90 644
#define IDR_VP_Y210_444Scale16_Buf_3 645
#define IDR_VP_Y210_444Scale16_Buf_3_Rot_180 646
#define IDR_VP_Y210_444Scale16_Buf_3_Rot_270 647
#define IDR_VP_Y210_444Scale16_Buf_3_Rot_90 648
#define IDR_VP_Y210_444Scale16_Buf_4 649
#define IDR_VP_Y210_444Scale16_Buf_4_Rot_180 650
#define IDR_VP_Y210_444Scale16_Buf_4_Rot_270 651
#define IDR_VP_Y210_444Scale16_Buf_4_Rot_90 652
#define IDR_VP_Y210_444Scale16_Buf_5 653
#define IDR_VP_Y210_444Scale16_Buf_5_Rot_180 654
#define IDR_VP_Y210_444Scale16_Buf_5_Rot_270 655
#define IDR_VP_Y210_444Scale16_Buf_5_Rot_90 656
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0 657
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_180 658
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_270 659
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_90 660
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1 661
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_180 662
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_270 663
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_90 664
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2 665
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_180 666
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_270 667
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_90 668
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3 669
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_180 670
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_270 671
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_90 672
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4 673
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_180 674
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_270 675
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_90 676
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5 677
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_180 678
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_270 679
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_90 680
#define IDR_VP_Y410_444AVS16_Buf_0 681
#define IDR_VP_Y410_444AVS16_Buf_0_Rot_180 682
#define IDR_VP_Y410_444AVS16_Buf_0_Rot_270 683
#define IDR_VP_Y410_444AVS16_Buf_0_Rot_90 684
#define IDR_VP_Y410_444AVS16_Buf_1 685
#define IDR_VP_Y410_444AVS16_Buf_1_Rot_180 686
#define IDR_VP_Y410_444AVS16_Buf_1_Rot_270 687
#define IDR_VP_Y410_444AVS16_Buf_1_Rot_90 688
#define IDR_VP_Y410_444AVS16_Buf_2 689
#define IDR_VP_Y410_444AVS16_Buf_2_Rot_180 690
#define IDR_VP_Y410_444AVS16_Buf_2_Rot_270 691
#define IDR_VP_Y410_444AVS16_Buf_2_Rot_90 692
#define IDR_VP_Y410_444AVS16_Buf_3 693
#define IDR_VP_Y410_444AVS16_Buf_3_Rot_180 694
#define IDR_VP_Y410_444AVS16_Buf_3_Rot_270 695
#define IDR_VP_Y410_444AVS16_Buf_3_Rot_90 696
#define IDR_VP_Y410_444AVS16_Buf_4 697
#define IDR_VP_Y410_444AVS16_Buf_4_Rot_180 698
#define IDR_VP_Y410_444AVS16_Buf_4_Rot_270 699
#define IDR_VP_Y410_444AVS16_Buf_4_Rot_90 700
#define IDR_VP_Y410_444AVS16_Buf_5 701
#define IDR_VP_Y410_444AVS16_Buf_5_Rot_180 702
#define IDR_VP_Y410_444AVS16_Buf_5_Rot_270 703
#define IDR_VP_Y410_444AVS16_Buf_5_Rot_90 704
#define IDR_VP_Y410_444DScale16_Buf_0 705
#define IDR_VP_Y410_444DScale16_Buf_0_Rot_180 706
#define IDR_VP_Y410_444DScale16_Buf_0_Rot_270 707
#define IDR_VP_Y410_444DScale16_Buf_0_Rot_90 708
#define IDR_VP_Y410_444DScale16_Buf_1 709
#define IDR_VP_Y410_444DScale16_Buf_1_Rot_180 710
#define IDR_VP_Y410_444DScale16_Buf_1_Rot_270 711
#define IDR_VP_Y410_444DScale16_Buf_1_Rot_90 712
#define IDR_VP_Y410_444DScale16_Buf_2 713
#define IDR_VP_Y410_444DScale16_Buf_2_Rot_180 714
#define IDR_VP_Y410_444DScale16_Buf_2_Rot_270 715
#define IDR_VP_Y410_444DScale16_Buf_2_Rot_90 716
#define IDR_VP_Y410_444DScale16_Buf_3 717
#define IDR_VP_Y410_444DScale16_Buf_3_Rot_180 718
#define IDR_VP_Y410_444DScale16_Buf_3_Rot_270 719
#define IDR_VP_Y410_444DScale16_Buf_3_Rot_90 720
#define IDR_VP_Y410_444DScale16_Buf_4 721
#define IDR_VP_Y410_444DScale16_Buf_4_Rot_180 722
#define IDR_VP_Y410_444DScale16_Buf_4_Rot_270 723
#define IDR_VP_Y410_444DScale16_Buf_4_Rot_90 724
#define IDR_VP_Y410_444DScale16_Buf_5 725
#define IDR_VP_Y410_444DScale16_Buf_5_Rot_180 726
#define IDR_VP_Y410_444DScale16_Buf_5_Rot_270 727
#define IDR_VP_Y410_444DScale16_Buf_5_Rot_90 728
#define IDR_VP_Y410_444Scale16_Buf_0 729
#define IDR_VP_Y410_444Scale16_Buf_0_Rot_180 730
#define IDR_VP_Y410_444Scale16_Buf_0_Rot_270 731
#define IDR_VP_Y410_444Scale16_Buf_0_Rot_90 732
#define IDR_VP_Y410_444Scale16_Buf_1 733
#define IDR_VP_Y410_444Scale16_Buf_1_Rot_180 734
#define IDR_VP_Y410_444Scale16_Buf_1_Rot_270 735
#define IDR_VP_Y410_444Scale16_Buf_1_Rot_90 736
#define IDR_VP_Y410_444Scale16_Buf_2 737
#define IDR_VP_Y410_444Scale16_Buf_2_Rot_180 738
#define IDR_VP_Y410_444Scale16_Buf_2_Rot_270 739
#define IDR_VP_Y410_444Scale16_Buf_2_Rot_90 740
#define IDR_VP_Y410_444Scale16_Buf_3 741
#define IDR_VP_Y410_444Scale16_Buf_3_Rot_180 742
#define IDR_VP_Y410_444Scale16_Buf_3_Rot_270 743
#define IDR_VP_Y410_444Scale16_Buf_3_Rot_90 744
#define IDR_VP_Y410_444Scale16_Buf_4 745
#define IDR_VP_Y410_444Scale16_Buf_4_Rot_180 746
#define IDR_VP_Y410_444Scale16_Buf_4_Rot_270 747
#define IDR_VP_Y410_444Scale16_Buf_4_Rot_90 748
#define IDR_VP_Y410_444Scale16_Buf_5 749
#define IDR_VP_Y410_444Scale16_Buf_5_Rot_180 750
#define IDR_VP_Y410_444Scale16_Buf_5_Rot_270 751
#define IDR_VP_Y410_444Scale16_Buf_5_Rot_90 752
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0 753
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0_Rot_180 754
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0_Rot_270 755
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0_Rot_90 756
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1 757
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1_Rot_180 758
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1_Rot_270 759
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1_Rot_90 760
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2 761
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2_Rot_180 762
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2_Rot_270 763
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2_Rot_90 764
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3 765
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3_Rot_180 766
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3_Rot_270 767
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3_Rot_90 768
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4 769
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4_Rot_180 770
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4_Rot_270 771
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4_Rot_90 772
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5 773
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5_Rot_180 774
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5_Rot_270 775
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5_Rot_90 776
#define IDR_VP_camera_pipe_CalcParams 777
#define IDR_VP_return 778
#define IDR_VP_zzz_preproduction 779
#define IDR_VP_zzz_preproduction_ALLPL2Copy_Gen 780
#define IDR_VP_zzz_preproduction_HDR_mandatory_Gen 781
#define IDR_VP_zzz_preproduction_HDR_per_frame_stat_Gen 782
#define IDR_VP_zzz_preproduction_gcBltPS_32_To_128_Mirror_Gen 783
#define IDR_VP_zzz_preproduction_gcBltPS_64_To_128_Mirror_Gen 784
#define IDR_VP_zzz_preproduction_gcBltPS_Gen 785
#define IDR_VP_zzz_preproduction_gcClearNoReplicatePS_Gen 786
#define IDR_VP_zzz_preproduction_gcClearReplicatePS_Gen 787
#define IDR_VP_zzz_preproduction_gcColorFillNoReplicatePS_Gen 788
#define IDR_VP_zzz_preproduction_gcColorFillReplicatePS_Gen 789
#define IDR_VP_zzz_preproduction_gcFastClearReplicatePS_Gen 790
#define IDR_VP_zzz_production 791
#define IDR_VP_zzz_production_ALLPL2Copy_Gen 792
#define IDR_VP_zzz_production_HDR_mandatory_Gen 793
#define IDR_VP_zzz_production_HDR_per_frame_stat_Gen 794
#define IDR_VP_zzz_production_gcBltPS_32_To_128_Mirror_Gen 795
#define IDR_VP_zzz_production_gcBltPS_64_To_128_Mirror_Gen 796
#define IDR_VP_zzz_production_gcBltPS_Gen 797
#define IDR_VP_zzz_production_gcClearNoReplicatePS_Gen 798
#define IDR_VP_zzz_production_gcClearReplicatePS_Gen 799
#define IDR_VP_zzz_production_gcColorFillNoReplicatePS_Gen 800
#define IDR_VP_zzz_production_gcColorFillReplicatePS_Gen 801
#define IDR_VP_zzz_production_gcFastClearReplicatePS_Gen 802
#define IDR_VP_TOTAL_NUM_KERNELS 803

#if _DEBUG
#define IDR_VP_KERNEL_NAMES   \
    _T("3DLUT"),\
    _T("AlphaSrcBlendG"),\
    _T("ByteCopy"),\
    _T("ByteCopy_MediaWalker"),\
    _T("CSC_444_16"),\
    _T("CSC_Premultiplied_444_16"),\
    _T("Call_AlphaSrcBlendG"),\
    _T("Call_CSC"),\
    _T("Call_CSC_Premultiplied"),\
    _T("Call_ColorE"),\
    _T("Call_Composite"),\
    _T("Call_ConstBlend"),\
    _T("Call_ConstSrcBlend"),\
    _T("Call_GammaC"),\
    _T("Call_Mirror_H_YUV"),\
    _T("Call_Mirror_H_YUVA"),\
    _T("Call_PartBlend"),\
    _T("Call_SrcBlend"),\
    _T("Call_SrcBlend_4bits"),\
    _T("ColorE"),\
    _T("Colorfill_444AVS16"),\
    _T("Colorfill_444AVS16_ConstBlend"),\
    _T("Colorfill_444AVS16_ConstSrcBlend"),\
    _T("Colorfill_444AVS16_PartBlend"),\
    _T("Colorfill_444AVS16_SrcBlend"),\
    _T("Colorfill_444Scale16"),\
    _T("Colorfill_444Scale16_ConstBlend"),\
    _T("Colorfill_444Scale16_ConstSrcBlend"),\
    _T("Colorfill_444Scale16_PartBlend"),\
    _T("Colorfill_444Scale16_SrcBlend"),\
    _T("Composite_444_16"),\
    _T("Compute_Lumakey"),\
    _T("Compute_Lumakey_Buf0123"),\
    _T("ConstBlend_444_16"),\
    _T("ConstSrcBlend_444_16"),\
    _T("Crypto_Block_Copy"),\
    _T("EOT"),\
    _T("FMD_Summation"),\
    _T("FRC_Clean_Map"),\
    _T("FRC_GMV_Detection"),\
    _T("FRC_GMV_Sanity_Check"),\
    _T("FRC_GradUV"),\
    _T("FRC_GradY"),\
    _T("FRC_MC"),\
    _T("FRC_ME_Level1"),\
    _T("FRC_ME_Level2"),\
    _T("FRC_ME_Level3"),\
    _T("FRC_MV_Level1"),\
    _T("FRC_MV_Level2"),\
    _T("FRC_MV_Level3"),\
    _T("FRC_PS"),\
    _T("FRC_SPD_Map"),\
    _T("FRC_TempDiff"),\
    _T("FRC_TempDiff_HD"),\
    _T("FRC_WSD"),\
    _T("GammaC"),\
    _T("GeoCorrection"),\
    _T("HDR_mandatory"),\
    _T("HDR_per_frame_stat"),\
    _T("IS_DS"),\
    _T("IS_FW"),\
    _T("IS_GMC"),\
    _T("IS_ME"),\
    _T("Interlace_420_16_Buf_0"),\
    _T("Interlace_420_16_Buf_1"),\
    _T("Interlace_420_16_Buf_2"),\
    _T("Interlace_420_16_Buf_3"),\
    _T("Interlace_444AVS16_Buf_0"),\
    _T("Interlace_444AVS16_Buf_1"),\
    _T("Interlace_444AVS16_Buf_2"),\
    _T("Interlace_444AVS16_Buf_3"),\
    _T("Interlace_444_16_Buf_0"),\
    _T("Interlace_444_16_Buf_1"),\
    _T("Interlace_444_16_Buf_2"),\
    _T("Interlace_444_16_Buf_3"),\
    _T("LACE_HIST_SUM"),\
    _T("LACE_LUT"),\
    _T("LACE_PWLF"),\
    _T("LACE_STD"),\
    _T("LinkFile"),\
    _T("Mirror_AVS_H_L0"),\
    _T("Mirror_AVS_V_L0"),\
    _T("Mirror_H_YUV"),\
    _T("Mirror_H_YUVA"),\
    _T("Mirror_scale_H_L0"),\
    _T("Mirror_scale_V_L0"),\
    _T("NV12_DP_rotation_avg"),\
    _T("NV12_DP_rotation_nv12"),\
    _T("NV12_DP_rotation_rep"),\
    _T("P010_444Dscale16_Buf_0"),\
    _T("P010_444Dscale16_Buf_0_Rot_180"),\
    _T("P010_444Dscale16_Buf_0_Rot_270"),\
    _T("P010_444Dscale16_Buf_0_Rot_90"),\
    _T("P010_444Dscale16_Buf_1"),\
    _T("P010_444Dscale16_Buf_1_Rot_180"),\
    _T("P010_444Dscale16_Buf_1_Rot_270"),\
    _T("P010_444Dscale16_Buf_1_Rot_90"),\
    _T("P010_444Dscale16_Buf_2"),\
    _T("P010_444Dscale16_Buf_2_Rot_180"),\
    _T("P010_444Dscale16_Buf_2_Rot_270"),\
    _T("P010_444Dscale16_Buf_2_Rot_90"),\
    _T("P010_444Dscale16_Buf_3"),\
    _T("P010_444Dscale16_Buf_3_Rot_180"),\
    _T("P010_444Dscale16_Buf_3_Rot_270"),\
    _T("P010_444Dscale16_Buf_3_Rot_90"),\
    _T("PA_444AVS16_Buf_0"),\
    _T("PA_444AVS16_Buf_0_Rot_180"),\
    _T("PA_444AVS16_Buf_0_Rot_270"),\
    _T("PA_444AVS16_Buf_0_Rot_90"),\
    _T("PA_444AVS16_Buf_1"),\
    _T("PA_444AVS16_Buf_1_Rot_180"),\
    _T("PA_444AVS16_Buf_1_Rot_270"),\
    _T("PA_444AVS16_Buf_1_Rot_90"),\
    _T("PA_444AVS16_Buf_2"),\
    _T("PA_444AVS16_Buf_2_Rot_180"),\
    _T("PA_444AVS16_Buf_2_Rot_270"),\
    _T("PA_444AVS16_Buf_2_Rot_90"),\
    _T("PA_444AVS16_Buf_3"),\
    _T("PA_444AVS16_Buf_3_Rot_180"),\
    _T("PA_444AVS16_Buf_3_Rot_270"),\
    _T("PA_444AVS16_Buf_3_Rot_90"),\
    _T("PA_444AVS16_Buf_4"),\
    _T("PA_444AVS16_Buf_4_Rot_180"),\
    _T("PA_444AVS16_Buf_4_Rot_270"),\
    _T("PA_444AVS16_Buf_4_Rot_90"),\
    _T("PA_444AVS16_Buf_5"),\
    _T("PA_444AVS16_Buf_5_Rot_180"),\
    _T("PA_444AVS16_Buf_5_Rot_270"),\
    _T("PA_444AVS16_Buf_5_Rot_90"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_3"),\
    _T("PA_444DScale16_Buf_0"),\
    _T("PA_444DScale16_Buf_1"),\
    _T("PA_444DScale16_Buf_2"),\
    _T("PA_444DScale16_Buf_3"),\
    _T("PA_444DScale16_Buf_4"),\
    _T("PA_444DScale16_Buf_5"),\
    _T("PA_444Dscale16_Buf_0_Rot_180"),\
    _T("PA_444Dscale16_Buf_0_Rot_270"),\
    _T("PA_444Dscale16_Buf_0_Rot_90"),\
    _T("PA_444Dscale16_Buf_1_Rot_180"),\
    _T("PA_444Dscale16_Buf_1_Rot_270"),\
    _T("PA_444Dscale16_Buf_1_Rot_90"),\
    _T("PA_444Dscale16_Buf_2_Rot_180"),\
    _T("PA_444Dscale16_Buf_2_Rot_270"),\
    _T("PA_444Dscale16_Buf_2_Rot_90"),\
    _T("PA_444Dscale16_Buf_3_Rot_180"),\
    _T("PA_444Dscale16_Buf_3_Rot_270"),\
    _T("PA_444Dscale16_Buf_3_Rot_90"),\
    _T("PA_444Scale16_Buf_0"),\
    _T("PA_444Scale16_Buf_0_Rot_180"),\
    _T("PA_444Scale16_Buf_0_Rot_270"),\
    _T("PA_444Scale16_Buf_0_Rot_90"),\
    _T("PA_444Scale16_Buf_1"),\
    _T("PA_444Scale16_Buf_1_Rot_180"),\
    _T("PA_444Scale16_Buf_1_Rot_270"),\
    _T("PA_444Scale16_Buf_1_Rot_90"),\
    _T("PA_444Scale16_Buf_2"),\
    _T("PA_444Scale16_Buf_2_Rot_180"),\
    _T("PA_444Scale16_Buf_2_Rot_270"),\
    _T("PA_444Scale16_Buf_2_Rot_90"),\
    _T("PA_444Scale16_Buf_3"),\
    _T("PA_444Scale16_Buf_3_Rot_180"),\
    _T("PA_444Scale16_Buf_3_Rot_270"),\
    _T("PA_444Scale16_Buf_3_Rot_90"),\
    _T("PA_444Scale16_Buf_4"),\
    _T("PA_444Scale16_Buf_4_Rot_180"),\
    _T("PA_444Scale16_Buf_4_Rot_270"),\
    _T("PA_444Scale16_Buf_4_Rot_90"),\
    _T("PA_444Scale16_Buf_5"),\
    _T("PA_444Scale16_Buf_5_Rot_180"),\
    _T("PA_444Scale16_Buf_5_Rot_270"),\
    _T("PA_444Scale16_Buf_5_Rot_90"),\
    _T("PA_444iAVS16_Buf_0"),\
    _T("PA_444iAVS16_Buf_1"),\
    _T("PA_444iAVS16_Buf_2"),\
    _T("PA_444iAVS16_Buf_3"),\
    _T("PA_444iDScale16_Buf_0"),\
    _T("PA_444iDScale16_Buf_1"),\
    _T("PA_444iDScale16_Buf_2"),\
    _T("PA_444iDScale16_Buf_3"),\
    _T("PA_444iScale16_Buf_0"),\
    _T("PA_444iScale16_Buf_0_Rot_180"),\
    _T("PA_444iScale16_Buf_0_Rot_270"),\
    _T("PA_444iScale16_Buf_0_Rot_90"),\
    _T("PA_444iScale16_Buf_1"),\
    _T("PA_444iScale16_Buf_1_Rot_180"),\
    _T("PA_444iScale16_Buf_1_Rot_270"),\
    _T("PA_444iScale16_Buf_1_Rot_90"),\
    _T("PA_444iScale16_Buf_2"),\
    _T("PA_444iScale16_Buf_2_Rot_180"),\
    _T("PA_444iScale16_Buf_2_Rot_270"),\
    _T("PA_444iScale16_Buf_2_Rot_90"),\
    _T("PA_444iScale16_Buf_3"),\
    _T("PA_444iScale16_Buf_3_Rot_180"),\
    _T("PA_444iScale16_Buf_3_Rot_270"),\
    _T("PA_444iScale16_Buf_3_Rot_90"),\
    _T("PA_AVS_Mirror_H_L0"),\
    _T("PA_AVS_Mirror_V_L0"),\
    _T("PA_AVS_Rotate_90_Mirror_H_L0"),\
    _T("PA_AVS_Rotate_90_Mirror_V_L0"),\
    _T("PA_AVS_Rotate_L0_180"),\
    _T("PA_AVS_Rotate_L0_270"),\
    _T("PA_AVS_Rotate_L0_90"),\
    _T("PA_Copy"),\
    _T("PA_Scale_Mirror_H_L0"),\
    _T("PA_Scale_Mirror_V_L0"),\
    _T("PA_Scale_Rotate90_Mirror_H_L0"),\
    _T("PA_Scale_Rotate90_Mirror_V_L0"),\
    _T("PA_Scale_Rotate_L0_180"),\
    _T("PA_Scale_Rotate_L0_270"),\
    _T("PA_Scale_Rotate_L0_90"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_0"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_1"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_2"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_3"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_4"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_5"),\
    _T("PL2_444AVS16_Buf_0"),\
    _T("PL2_444AVS16_Buf_0_Rot_180"),\
    _T("PL2_444AVS16_Buf_0_Rot_270"),\
    _T("PL2_444AVS16_Buf_0_Rot_90"),\
    _T("PL2_444AVS16_Buf_1"),\
    _T("PL2_444AVS16_Buf_1_Rot_180"),\
    _T("PL2_444AVS16_Buf_1_Rot_270"),\
    _T("PL2_444AVS16_Buf_1_Rot_90"),\
    _T("PL2_444AVS16_Buf_2"),\
    _T("PL2_444AVS16_Buf_2_Rot_180"),\
    _T("PL2_444AVS16_Buf_2_Rot_270"),\
    _T("PL2_444AVS16_Buf_2_Rot_90"),\
    _T("PL2_444AVS16_Buf_3"),\
    _T("PL2_444AVS16_Buf_3_Rot_180"),\
    _T("PL2_444AVS16_Buf_3_Rot_270"),\
    _T("PL2_444AVS16_Buf_3_Rot_90"),\
    _T("PL2_444AVS16_Buf_4"),\
    _T("PL2_444AVS16_Buf_4_Rot_180"),\
    _T("PL2_444AVS16_Buf_4_Rot_270"),\
    _T("PL2_444AVS16_Buf_4_Rot_90"),\
    _T("PL2_444AVS16_Buf_5"),\
    _T("PL2_444AVS16_Buf_5_Rot_180"),\
    _T("PL2_444AVS16_Buf_5_Rot_270"),\
    _T("PL2_444AVS16_Buf_5_Rot_90"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4_Rot_180"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4_Rot_270"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4_Rot_90"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5_Rot_180"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5_Rot_270"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5_Rot_90"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_0"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_1"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_2"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_3"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_4"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_5"),\
    _T("PL2_444Dscale16_Buf_0"),\
    _T("PL2_444Dscale16_Buf_0_Rot_180"),\
    _T("PL2_444Dscale16_Buf_0_Rot_270"),\
    _T("PL2_444Dscale16_Buf_0_Rot_90"),\
    _T("PL2_444Dscale16_Buf_1"),\
    _T("PL2_444Dscale16_Buf_1_Rot_180"),\
    _T("PL2_444Dscale16_Buf_1_Rot_270"),\
    _T("PL2_444Dscale16_Buf_1_Rot_90"),\
    _T("PL2_444Dscale16_Buf_2"),\
    _T("PL2_444Dscale16_Buf_2_Rot_180"),\
    _T("PL2_444Dscale16_Buf_2_Rot_270"),\
    _T("PL2_444Dscale16_Buf_2_Rot_90"),\
    _T("PL2_444Dscale16_Buf_3"),\
    _T("PL2_444Dscale16_Buf_3_Rot_180"),\
    _T("PL2_444Dscale16_Buf_3_Rot_270"),\
    _T("PL2_444Dscale16_Buf_3_Rot_90"),\
    _T("PL2_444Dscale16_Buf_4"),\
    _T("PL2_444Dscale16_Buf_5"),\
    _T("PL2_444Dscale16_Buf_Sep_Alpha_4"),\
    _T("PL2_444Dscale16_Buf_Sep_Alpha_5"),\
    _T("PL2_444Scale16_Buf_0"),\
    _T("PL2_444Scale16_Buf_0_Rot_180"),\
    _T("PL2_444Scale16_Buf_0_Rot_270"),\
    _T("PL2_444Scale16_Buf_0_Rot_90"),\
    _T("PL2_444Scale16_Buf_1"),\
    _T("PL2_444Scale16_Buf_1_Rot_180"),\
    _T("PL2_444Scale16_Buf_1_Rot_270"),\
    _T("PL2_444Scale16_Buf_1_Rot_90"),\
    _T("PL2_444Scale16_Buf_2"),\
    _T("PL2_444Scale16_Buf_2_Rot_180"),\
    _T("PL2_444Scale16_Buf_2_Rot_270"),\
    _T("PL2_444Scale16_Buf_2_Rot_90"),\
    _T("PL2_444Scale16_Buf_3"),\
    _T("PL2_444Scale16_Buf_3_Rot_180"),\
    _T("PL2_444Scale16_Buf_3_Rot_270"),\
    _T("PL2_444Scale16_Buf_3_Rot_90"),\
    _T("PL2_444Scale16_Buf_4"),\
    _T("PL2_444Scale16_Buf_4_Rot_180"),\
    _T("PL2_444Scale16_Buf_4_Rot_270"),\
    _T("PL2_444Scale16_Buf_4_Rot_90"),\
    _T("PL2_444Scale16_Buf_5"),\
    _T("PL2_444Scale16_Buf_5_Rot_180"),\
    _T("PL2_444Scale16_Buf_5_Rot_270"),\
    _T("PL2_444Scale16_Buf_5_Rot_90"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4_Rot_180"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4_Rot_270"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4_Rot_90"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5_Rot_180"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5_Rot_270"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3_Rot_90"),\
    _T("PL2_444iDScale16_Buf_0"),\
    _T("PL2_444iDScale16_Buf_1"),\
    _T("PL2_444iDScale16_Buf_2"),\
    _T("PL2_444iDScale16_Buf_3"),\
    _T("PL2_444iScale16_Buf_0"),\
    _T("PL2_444iScale16_Buf_0_Rot_180"),\
    _T("PL2_444iScale16_Buf_0_Rot_270"),\
    _T("PL2_444iScale16_Buf_0_Rot_90"),\
    _T("PL2_444iScale16_Buf_1"),\
    _T("PL2_444iScale16_Buf_1_Rot_180"),\
    _T("PL2_444iScale16_Buf_1_Rot_270"),\
    _T("PL2_444iScale16_Buf_1_Rot_90"),\
    _T("PL2_444iScale16_Buf_2"),\
    _T("PL2_444iScale16_Buf_2_Rot_180"),\
    _T("PL2_444iScale16_Buf_2_Rot_270"),\
    _T("PL2_444iScale16_Buf_2_Rot_90"),\
    _T("PL2_444iScale16_Buf_3"),\
    _T("PL2_444iScale16_Buf_3_Rot_180"),\
    _T("PL2_444iScale16_Buf_3_Rot_270"),\
    _T("PL2_444iScale16_Buf_3_Rot_90"),\
    _T("PL2_AVS_Mirror_H_L0"),\
    _T("PL2_AVS_Mirror_H_L0_DualOutput"),\
    _T("PL2_AVS_Mirror_V_L0"),\
    _T("PL2_AVS_Rotate90_Mirror_H_L0"),\
    _T("PL2_AVS_Rotate90_Mirror_V_L0"),\
    _T("PL2_AVS_Rotate_L0_180"),\
    _T("PL2_AVS_Rotate_L0_270"),\
    _T("PL2_AVS_Rotate_L0_90"),\
    _T("PL2_Copy"),\
    _T("PL2_Scale_Mirror_H_L0"),\
    _T("PL2_Scale_Mirror_H_L0_DualOutput"),\
    _T("PL2_Scale_Mirror_V_L0"),\
    _T("PL2_Scale_Rotate90_Mirror_H_L0"),\
    _T("PL2_Scale_Rotate90_Mirror_V_L0"),\
    _T("PL2_Scale_Rotate_L0_180"),\
    _T("PL2_Scale_Rotate_L0_270"),\
    _T("PL2_Scale_Rotate_L0_90"),\
    _T("PL3_444AVS16_Buf_0"),\
    _T("PL3_444AVS16_Buf_0_Rot_180"),\
    _T("PL3_444AVS16_Buf_0_Rot_270"),\
    _T("PL3_444AVS16_Buf_0_Rot_90"),\
    _T("PL3_444AVS16_Buf_1"),\
    _T("PL3_444AVS16_Buf_1_Rot_180"),\
    _T("PL3_444AVS16_Buf_1_Rot_270"),\
    _T("PL3_444AVS16_Buf_1_Rot_90"),\
    _T("PL3_444AVS16_Buf_2"),\
    _T("PL3_444AVS16_Buf_2_Rot_180"),\
    _T("PL3_444AVS16_Buf_2_Rot_270"),\
    _T("PL3_444AVS16_Buf_2_Rot_90"),\
    _T("PL3_444AVS16_Buf_3"),\
    _T("PL3_444AVS16_Buf_3_Rot_180"),\
    _T("PL3_444AVS16_Buf_3_Rot_270"),\
    _T("PL3_444AVS16_Buf_3_Rot_90"),\
    _T("PL3_444AVS16_Buf_4"),\
    _T("PL3_444AVS16_Buf_4_Rot_180"),\
    _T("PL3_444AVS16_Buf_4_Rot_270"),\
    _T("PL3_444AVS16_Buf_4_Rot_90"),\
    _T("PL3_444AVS16_Buf_5"),\
    _T("PL3_444AVS16_Buf_5_Rot_180"),\
    _T("PL3_444AVS16_Buf_5_Rot_270"),\
    _T("PL3_444AVS16_Buf_5_Rot_90"),\
    _T("PL3_444DScale16_Buf_0"),\
    _T("PL3_444DScale16_Buf_1"),\
    _T("PL3_444DScale16_Buf_2"),\
    _T("PL3_444DScale16_Buf_3"),\
    _T("PL3_444DScale16_Buf_4"),\
    _T("PL3_444DScale16_Buf_5"),\
    _T("PL3_444Dscale16_Buf_0_Rot_180"),\
    _T("PL3_444Dscale16_Buf_0_Rot_270"),\
    _T("PL3_444Dscale16_Buf_0_Rot_90"),\
    _T("PL3_444Dscale16_Buf_1_Rot_180"),\
    _T("PL3_444Dscale16_Buf_1_Rot_270"),\
    _T("PL3_444Dscale16_Buf_1_Rot_90"),\
    _T("PL3_444Dscale16_Buf_2_Rot_180"),\
    _T("PL3_444Dscale16_Buf_2_Rot_270"),\
    _T("PL3_444Dscale16_Buf_2_Rot_90"),\
    _T("PL3_444Dscale16_Buf_3_Rot_180"),\
    _T("PL3_444Dscale16_Buf_3_Rot_270"),\
    _T("PL3_444Dscale16_Buf_3_Rot_90"),\
    _T("PL3_444Scale16_Buf_0"),\
    _T("PL3_444Scale16_Buf_0_Rot_180"),\
    _T("PL3_444Scale16_Buf_0_Rot_270"),\
    _T("PL3_444Scale16_Buf_0_Rot_90"),\
    _T("PL3_444Scale16_Buf_1"),\
    _T("PL3_444Scale16_Buf_1_Rot_180"),\
    _T("PL3_444Scale16_Buf_1_Rot_270"),\
    _T("PL3_444Scale16_Buf_1_Rot_90"),\
    _T("PL3_444Scale16_Buf_2"),\
    _T("PL3_444Scale16_Buf_2_Rot_180"),\
    _T("PL3_444Scale16_Buf_2_Rot_270"),\
    _T("PL3_444Scale16_Buf_2_Rot_90"),\
    _T("PL3_444Scale16_Buf_3"),\
    _T("PL3_444Scale16_Buf_3_Rot_180"),\
    _T("PL3_444Scale16_Buf_3_Rot_270"),\
    _T("PL3_444Scale16_Buf_3_Rot_90"),\
    _T("PL3_444Scale16_Buf_4"),\
    _T("PL3_444Scale16_Buf_4_Rot_180"),\
    _T("PL3_444Scale16_Buf_4_Rot_270"),\
    _T("PL3_444Scale16_Buf_4_Rot_90"),\
    _T("PL3_444Scale16_Buf_5"),\
    _T("PL3_444Scale16_Buf_5_Rot_180"),\
    _T("PL3_444Scale16_Buf_5_Rot_270"),\
    _T("PL3_444Scale16_Buf_5_Rot_90"),\
    _T("PL3_444iDScale16_Buf_0"),\
    _T("PL3_444iDScale16_Buf_1"),\
    _T("PL3_444iDScale16_Buf_2"),\
    _T("PL3_444iDScale16_Buf_3"),\
    _T("PL3_444iScale16_Buf_0"),\
    _T("PL3_444iScale16_Buf_0_Rot_180"),\
    _T("PL3_444iScale16_Buf_0_Rot_270"),\
    _T("PL3_444iScale16_Buf_0_Rot_90"),\
    _T("PL3_444iScale16_Buf_1"),\
    _T("PL3_444iScale16_Buf_1_Rot_180"),\
    _T("PL3_444iScale16_Buf_1_Rot_270"),\
    _T("PL3_444iScale16_Buf_1_Rot_90"),\
    _T("PL3_444iScale16_Buf_2"),\
    _T("PL3_444iScale16_Buf_2_Rot_180"),\
    _T("PL3_444iScale16_Buf_2_Rot_270"),\
    _T("PL3_444iScale16_Buf_2_Rot_90"),\
    _T("PL3_444iScale16_Buf_3"),\
    _T("PL3_444iScale16_Buf_3_Rot_180"),\
    _T("PL3_444iScale16_Buf_3_Rot_270"),\
    _T("PL3_444iScale16_Buf_3_Rot_90"),\
    _T("PL3_AVS_Rotate_L0_180"),\
    _T("PL3_AVS_Rotate_L0_270"),\
    _T("PL3_AVS_Rotate_L0_90"),\
    _T("PL3_Scale_Rotate_L0_180"),\
    _T("PL3_Scale_Rotate_L0_270"),\
    _T("PL3_Scale_Rotate_L0_90"),\
    _T("PLY_444DScale16_2f_Buf_0"),\
    _T("PLY_444DScale16_2f_Buf_1"),\
    _T("PLY_444DScale16_2f_Buf_2"),\
    _T("PLY_444DScale16_2f_Buf_3"),\
    _T("PLY_444DScale16_Buf_0"),\
    _T("PLY_444DScale16_Buf_0_Rot_180"),\
    _T("PLY_444DScale16_Buf_0_Rot_270"),\
    _T("PLY_444DScale16_Buf_0_Rot_90"),\
    _T("PLY_444DScale16_Buf_1"),\
    _T("PLY_444DScale16_Buf_1_Rot_180"),\
    _T("PLY_444DScale16_Buf_1_Rot_270"),\
    _T("PLY_444DScale16_Buf_1_Rot_90"),\
    _T("PLY_444DScale16_Buf_2"),\
    _T("PLY_444DScale16_Buf_2_Rot_180"),\
    _T("PLY_444DScale16_Buf_2_Rot_270"),\
    _T("PLY_444DScale16_Buf_2_Rot_90"),\
    _T("PLY_444DScale16_Buf_3"),\
    _T("PLY_444DScale16_Buf_3_Rot_180"),\
    _T("PLY_444DScale16_Buf_3_Rot_270"),\
    _T("PLY_444DScale16_Buf_3_Rot_90"),\
    _T("PartBlend_444_16"),\
    _T("Prepare_LumaKey_SampleUnorm"),\
    _T("RGB2sRGB"),\
    _T("Rotate_90_Mirror_AVS_H_L0"),\
    _T("Rotate_90_Mirror_AVS_V_L0"),\
    _T("Rotate_90_Mirror_H_scale_L0"),\
    _T("Rotate_90_Mirror_V_scale_L0"),\
    _T("Rotate_AVS_L0_180"),\
    _T("Rotate_AVS_L0_270"),\
    _T("Rotate_AVS_L0_90"),\
    _T("Rotate_Scale_L0_180"),\
    _T("Rotate_Scale_L0_270"),\
    _T("Rotate_Scale_L0_90"),\
    _T("SIP_Debug"),\
    _T("Save_444AVS16_ARGB"),\
    _T("Save_444AVS16_ARGB_64Byte"),\
    _T("Save_444AVS16_NV12"),\
    _T("Save_444AVS16_NV21"),\
    _T("Save_444AVS16_PA"),\
    _T("Save_444AVS16_PL3"),\
    _T("Save_444AVS16_R10G10B10"),\
    _T("Save_444AVS16_R10G10B10A2"),\
    _T("Save_444AVS16_R10G10B10X2"),\
    _T("Save_444AVS16_RGB"),\
    _T("Save_444AVS16_RGB16"),\
    _T("Save_444AVS16_RGB_64Byte"),\
    _T("Save_444AVS16_SrcAYUV"),\
    _T("Save_444AVS16_XRGB"),\
    _T("Save_444AVS16_XRGB_64Byte"),\
    _T("Save_444SCALE16_ARGB_64Byte"),\
    _T("Save_444SCALE16_NV21"),\
    _T("Save_444SCALE16_RGB_64Byte"),\
    _T("Save_444SCALE16_XRGB_64Byte"),\
    _T("Save_444Scale16_ARGB"),\
    _T("Save_444Scale16_ARGB_64Byte"),\
    _T("Save_444Scale16_Dither_NV12"),\
    _T("Save_444Scale16_Dither_NV21"),\
    _T("Save_444Scale16_Dither_PA"),\
    _T("Save_444Scale16_Dither_PA_32X16"),\
    _T("Save_444Scale16_Dither_PL3"),\
    _T("Save_444Scale16_Dither_RGB"),\
    _T("Save_444Scale16_Dither_RGB_64Byte"),\
    _T("Save_444Scale16_Dither_VUYA"),\
    _T("Save_444Scale16_Dither_XRGB"),\
    _T("Save_444Scale16_Dither_XRGB_64Byte"),\
    _T("Save_444Scale16_NV12"),\
    _T("Save_444Scale16_NV21"),\
    _T("Save_444Scale16_P010"),\
    _T("Save_444Scale16_PA"),\
    _T("Save_444Scale16_PA_32X16"),\
    _T("Save_444Scale16_PL3"),\
    _T("Save_444Scale16_PLY"),\
    _T("Save_444Scale16_R10G10B10"),\
    _T("Save_444Scale16_R10G10B10A2"),\
    _T("Save_444Scale16_R10G10B10X2"),\
    _T("Save_444Scale16_R10G10B10XR"),\
    _T("Save_444Scale16_R10G10B10XRA2"),\
    _T("Save_444Scale16_R10G10B10XRX2"),\
    _T("Save_444Scale16_RGB"),\
    _T("Save_444Scale16_RGB16"),\
    _T("Save_444Scale16_RGB_64Byte"),\
    _T("Save_444Scale16_SrcVUYA"),\
    _T("Save_444Scale16_VUYA"),\
    _T("Save_444Scale16_XRGB"),\
    _T("Save_444Scale16_XRGB_64Byte"),\
    _T("Save_444Scale16_Y210"),\
    _T("Save_444Scale16_Y410"),\
    _T("Set_Buf0_Buf4"),\
    _T("Set_Buf1_Buf5"),\
    _T("Set_Buf2_Buf4"),\
    _T("Set_Buf3_Buf5"),\
    _T("Set_CSC_Src_Buf0"),\
    _T("Set_CSC_Src_Buf1"),\
    _T("Set_CSC_Src_Buf2"),\
    _T("Set_CSC_Src_Buf3"),\
    _T("Set_CSC_Src_Buf4"),\
    _T("Set_CSC_Src_Buf5"),\
    _T("Set_CURBE_CSC_Coeff"),\
    _T("Set_ColorE_Src_Buf0"),\
    _T("Set_ColorE_Src_Buf1"),\
    _T("Set_ColorE_Src_Buf2"),\
    _T("Set_ColorE_Src_Buf3"),\
    _T("Set_Dest_Surf_Indexes_Primary"),\
    _T("Set_Dest_Surf_Indexes_Secondary"),\
    _T("Set_GammaC_Src_Buf0"),\
    _T("Set_GammaC_Src_Buf1"),\
    _T("Set_GammaC_Src_Buf2"),\
    _T("Set_GammaC_Src_Buf3"),\
    _T("Set_Layer_0"),\
    _T("Set_Layer_1"),\
    _T("Set_Layer_1_AVS"),\
    _T("Set_Layer_2"),\
    _T("Set_Layer_3"),\
    _T("Set_Layer_4"),\
    _T("Set_Layer_5"),\
    _T("Set_Layer_6"),\
    _T("Set_Layer_7"),\
    _T("Set_Patched_CSC_Coeff"),\
    _T("Set_Scale_Buf_0123_Colorfill"),\
    _T("Set_Sec_Half_Buf45"),\
    _T("Shuffle_444AVS16_Buf_0"),\
    _T("Shuffle_444AVS16_Buf_1"),\
    _T("Shuffle_444AVS16_Buf_2"),\
    _T("Shuffle_444AVS16_Buf_3"),\
    _T("Shuffle_444AVS16_Buf_4"),\
    _T("Shuffle_444AVS16_Buf_5"),\
    _T("SrcBlend_444_16"),\
    _T("SrcBlend_4bits_444_16"),\
    _T("UpdateDNState"),\
    _T("VP_Setup"),\
    _T("VP_Setup_MediaWalker"),\
    _T("VP_Setup_MediaWalker_32X16_Design"),\
    _T("VP_Setup_MediaWalker_32x32_Color"),\
    _T("Y210_444DScale16_Buf_0"),\
    _T("Y210_444DScale16_Buf_0_Rot_180"),\
    _T("Y210_444DScale16_Buf_0_Rot_270"),\
    _T("Y210_444DScale16_Buf_0_Rot_90"),\
    _T("Y210_444DScale16_Buf_1"),\
    _T("Y210_444DScale16_Buf_1_Rot_180"),\
    _T("Y210_444DScale16_Buf_1_Rot_270"),\
    _T("Y210_444DScale16_Buf_1_Rot_90"),\
    _T("Y210_444DScale16_Buf_2"),\
    _T("Y210_444DScale16_Buf_2_Rot_180"),\
    _T("Y210_444DScale16_Buf_2_Rot_270"),\
    _T("Y210_444DScale16_Buf_2_Rot_90"),\
    _T("Y210_444DScale16_Buf_3"),\
    _T("Y210_444DScale16_Buf_3_Rot_180"),\
    _T("Y210_444DScale16_Buf_3_Rot_270"),\
    _T("Y210_444DScale16_Buf_3_Rot_90"),\
    _T("Y210_444DScale16_Buf_4"),\
    _T("Y210_444DScale16_Buf_4_Rot_180"),\
    _T("Y210_444DScale16_Buf_4_Rot_270"),\
    _T("Y210_444DScale16_Buf_4_Rot_90"),\
    _T("Y210_444DScale16_Buf_5"),\
    _T("Y210_444DScale16_Buf_5_Rot_180"),\
    _T("Y210_444DScale16_Buf_5_Rot_270"),\
    _T("Y210_444DScale16_Buf_5_Rot_90"),\
    _T("Y210_444Scale16_Buf_0"),\
    _T("Y210_444Scale16_Buf_0_Rot_180"),\
    _T("Y210_444Scale16_Buf_0_Rot_270"),\
    _T("Y210_444Scale16_Buf_0_Rot_90"),\
    _T("Y210_444Scale16_Buf_1"),\
    _T("Y210_444Scale16_Buf_1_Rot_180"),\
    _T("Y210_444Scale16_Buf_1_Rot_270"),\
    _T("Y210_444Scale16_Buf_1_Rot_90"),\
    _T("Y210_444Scale16_Buf_2"),\
    _T("Y210_444Scale16_Buf_2_Rot_180"),\
    _T("Y210_444Scale16_Buf_2_Rot_270"),\
    _T("Y210_444Scale16_Buf_2_Rot_90"),\
    _T("Y210_444Scale16_Buf_3"),\
    _T("Y210_444Scale16_Buf_3_Rot_180"),\
    _T("Y210_444Scale16_Buf_3_Rot_270"),\
    _T("Y210_444Scale16_Buf_3_Rot_90"),\
    _T("Y210_444Scale16_Buf_4"),\
    _T("Y210_444Scale16_Buf_4_Rot_180"),\
    _T("Y210_444Scale16_Buf_4_Rot_270"),\
    _T("Y210_444Scale16_Buf_4_Rot_90"),\
    _T("Y210_444Scale16_Buf_5"),\
    _T("Y210_444Scale16_Buf_5_Rot_180"),\
    _T("Y210_444Scale16_Buf_5_Rot_270"),\
    _T("Y210_444Scale16_Buf_5_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_90"),\
    _T("Y410_444AVS16_Buf_0"),\
    _T("Y410_444AVS16_Buf_0_Rot_180"),\
    _T("Y410_444AVS16_Buf_0_Rot_270"),\
    _T("Y410_444AVS16_Buf_0_Rot_90"),\
    _T("Y410_444AVS16_Buf_1"),\
    _T("Y410_444AVS16_Buf_1_Rot_180"),\
    _T("Y410_444AVS16_Buf_1_Rot_270"),\
    _T("Y410_444AVS16_Buf_1_Rot_90"),\
    _T("Y410_444AVS16_Buf_2"),\
    _T("Y410_444AVS16_Buf_2_Rot_180"),\
    _T("Y410_444AVS16_Buf_2_Rot_270"),\
    _T("Y410_444AVS16_Buf_2_Rot_90"),\
    _T("Y410_444AVS16_Buf_3"),\
    _T("Y410_444AVS16_Buf_3_Rot_180"),\
    _T("Y410_444AVS16_Buf_3_Rot_270"),\
    _T("Y410_444AVS16_Buf_3_Rot_90"),\
    _T("Y410_444AVS16_Buf_4"),\
    _T("Y410_444AVS16_Buf_4_Rot_180"),\
    _T("Y410_444AVS16_Buf_4_Rot_270"),\
    _T("Y410_444AVS16_Buf_4_Rot_90"),\
    _T("Y410_444AVS16_Buf_5"),\
    _T("Y410_444AVS16_Buf_5_Rot_180"),\
    _T("Y410_444AVS16_Buf_5_Rot_270"),\
    _T("Y410_444AVS16_Buf_5_Rot_90"),\
    _T("Y410_444DScale16_Buf_0"),\
    _T("Y410_444DScale16_Buf_0_Rot_180"),\
    _T("Y410_444DScale16_Buf_0_Rot_270"),\
    _T("Y410_444DScale16_Buf_0_Rot_90"),\
    _T("Y410_444DScale16_Buf_1"),\
    _T("Y410_444DScale16_Buf_1_Rot_180"),\
    _T("Y410_444DScale16_Buf_1_Rot_270"),\
    _T("Y410_444DScale16_Buf_1_Rot_90"),\
    _T("Y410_444DScale16_Buf_2"),\
    _T("Y410_444DScale16_Buf_2_Rot_180"),\
    _T("Y410_444DScale16_Buf_2_Rot_270"),\
    _T("Y410_444DScale16_Buf_2_Rot_90"),\
    _T("Y410_444DScale16_Buf_3"),\
    _T("Y410_444DScale16_Buf_3_Rot_180"),\
    _T("Y410_444DScale16_Buf_3_Rot_270"),\
    _T("Y410_444DScale16_Buf_3_Rot_90"),\
    _T("Y410_444DScale16_Buf_4"),\
    _T("Y410_444DScale16_Buf_4_Rot_180"),\
    _T("Y410_444DScale16_Buf_4_Rot_270"),\
    _T("Y410_444DScale16_Buf_4_Rot_90"),\
    _T("Y410_444DScale16_Buf_5"),\
    _T("Y410_444DScale16_Buf_5_Rot_180"),\
    _T("Y410_444DScale16_Buf_5_Rot_270"),\
    _T("Y410_444DScale16_Buf_5_Rot_90"),\
    _T("Y410_444Scale16_Buf_0"),\
    _T("Y410_444Scale16_Buf_0_Rot_180"),\
    _T("Y410_444Scale16_Buf_0_Rot_270"),\
    _T("Y410_444Scale16_Buf_0_Rot_90"),\
    _T("Y410_444Scale16_Buf_1"),\
    _T("Y410_444Scale16_Buf_1_Rot_180"),\
    _T("Y410_444Scale16_Buf_1_Rot_270"),\
    _T("Y410_444Scale16_Buf_1_Rot_90"),\
    _T("Y410_444Scale16_Buf_2"),\
    _T("Y410_444Scale16_Buf_2_Rot_180"),\
    _T("Y410_444Scale16_Buf_2_Rot_270"),\
    _T("Y410_444Scale16_Buf_2_Rot_90"),\
    _T("Y410_444Scale16_Buf_3"),\
    _T("Y410_444Scale16_Buf_3_Rot_180"),\
    _T("Y410_444Scale16_Buf_3_Rot_270"),\
    _T("Y410_444Scale16_Buf_3_Rot_90"),\
    _T("Y410_444Scale16_Buf_4"),\
    _T("Y410_444Scale16_Buf_4_Rot_180"),\
    _T("Y410_444Scale16_Buf_4_Rot_270"),\
    _T("Y410_444Scale16_Buf_4_Rot_90"),\
    _T("Y410_444Scale16_Buf_5"),\
    _T("Y410_444Scale16_Buf_5_Rot_180"),\
    _T("Y410_444Scale16_Buf_5_Rot_270"),\
    _T("Y410_444Scale16_Buf_5_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5_Rot_90"),\
    _T("camera_pipe_CalcParams"),\
    _T("return"),\
    _T("zzz_preproduction"),\
    _T("zzz_preproduction_ALLPL2Copy_Gen"),\
    _T("zzz_preproduction_HDR_mandatory_Gen"),\
    _T("zzz_preproduction_HDR_per_frame_stat_Gen"),\
    _T("zzz_preproduction_gcBltPS_32_To_128_Mirror_Gen"),\
    _T("zzz_preproduction_gcBltPS_64_To_128_Mirror_Gen"),\
    _T("zzz_preproduction_gcBltPS_Gen"),\
    _T("zzz_preproduction_gcClearNoReplicatePS_Gen"),\
    _T("zzz_preproduction_gcClearReplicatePS_Gen"),\
    _T("zzz_preproduction_gcColorFillNoReplicatePS_Gen"),\
    _T("zzz_preproduction_gcColorFillReplicatePS_Gen"),\
    _T("zzz_preproduction_gcFastClearReplicatePS_Gen"),\
    _T("zzz_production"),\
    _T("zzz_production_ALLPL2Copy_Gen"),\
    _T("zzz_production_HDR_mandatory_Gen"),\
    _T("zzz_production_HDR_per_frame_stat_Gen"),\
    _T("zzz_production_gcBltPS_32_To_128_Mirror_Gen"),\
    _T("zzz_production_gcBltPS_64_To_128_Mirror_Gen"),\
    _T("zzz_production_gcBltPS_Gen"),\
    _T("zzz_production_gcClearNoReplicatePS_Gen"),\
    _T("zzz_production_gcClearReplicatePS_Gen"),\
    _T("zzz_production_gcColorFillNoReplicatePS_Gen"),\
    _T("zzz_production_gcColorFillReplicatePS_Gen"),\
    _T("zzz_production_gcFastClearReplicatePS_Gen"),\
    _T("")
#else // !_DEBUG
#define IDR_VP_KERNEL_NAMES   \
    _T("000"),\
    _T("001"),\
    _T("002"),\
    _T("003"),\
    _T("004"),\
    _T("005"),\
    _T("006"),\
    _T("007"),\
    _T("008"),\
    _T("009"),\
    _T("010"),\
    _T("011"),\
    _T("012"),\
    _T("013"),\
    _T("014"),\
    _T("015"),\
    _T("016"),\
    _T("017"),\
    _T("018"),\
    _T("019"),\
    _T("020"),\
    _T("021"),\
    _T("022"),\
    _T("023"),\
    _T("024"),\
    _T("025"),\
    _T("026"),\
    _T("027"),\
    _T("028"),\
    _T("029"),\
    _T("030"),\
    _T("031"),\
    _T("032"),\
    _T("033"),\
    _T("034"),\
    _T("035"),\
    _T("036"),\
    _T("037"),\
    _T("038"),\
    _T("039"),\
    _T("040"),\
    _T("041"),\
    _T("042"),\
    _T("043"),\
    _T("044"),\
    _T("045"),\
    _T("046"),\
    _T("047"),\
    _T("048"),\
    _T("049"),\
    _T("050"),\
    _T("051"),\
    _T("052"),\
    _T("053"),\
    _T("054"),\
    _T("055"),\
    _T("056"),\
    _T("057"),\
    _T("058"),\
    _T("059"),\
    _T("060"),\
    _T("061"),\
    _T("062"),\
    _T("063"),\
    _T("064"),\
    _T("065"),\
    _T("066"),\
    _T("067"),\
    _T("068"),\
    _T("069"),\
    _T("070"),\
    _T("071"),\
    _T("072"),\
    _T("073"),\
    _T("074"),\
    _T("075"),\
    _T("076"),\
    _T("077"),\
    _T("078"),\
    _T("079"),\
    _T("080"),\
    _T("081"),\
    _T("082"),\
    _T("083"),\
    _T("084"),\
    _T("085"),\
    _T("086"),\
    _T("087"),\
    _T("088"),\
    _T("089"),\
    _T("090"),\
    _T("091"),\
    _T("092"),\
    _T("093"),\
    _T("094"),\
    _T("095"),\
    _T("096"),\
    _T("097"),\
    _T("098"),\
    _T("099"),\
    _T("100"),\
    _T("101"),\
    _T("102"),\
    _T("103"),\
    _T("104"),\
    _T("105"),\
    _T("106"),\
    _T("107"),\
    _T("108"),\
    _T("109"),\
    _T("110"),\
    _T("111"),\
    _T("112"),\
    _T("113"),\
    _T("114"),\
    _T("115"),\
    _T("116"),\
    _T("117"),\
    _T("118"),\
    _T("119"),\
    _T("120"),\
    _T("121"),\
    _T("122"),\
    _T("123"),\
    _T("124"),\
    _T("125"),\
    _T("126"),\
    _T("127"),\
    _T("128"),\
    _T("129"),\
    _T("130"),\
    _T("131"),\
    _T("132"),\
    _T("133"),\
    _T("134"),\
    _T("135"),\
    _T("136"),\
    _T("137"),\
    _T("138"),\
    _T("139"),\
    _T("140"),\
    _T("141"),\
    _T("142"),\
    _T("143"),\
    _T("144"),\
    _T("145"),\
    _T("146"),\
    _T("147"),\
    _T("148"),\
    _T("149"),\
    _T("150"),\
    _T("151"),\
    _T("152"),\
    _T("153"),\
    _T("154"),\
    _T("155"),\
    _T("156"),\
    _T("157"),\
    _T("158"),\
    _T("159"),\
    _T("160"),\
    _T("161"),\
    _T("162"),\
    _T("163"),\
    _T("164"),\
    _T("165"),\
    _T("166"),\
    _T("167"),\
    _T("168"),\
    _T("169"),\
    _T("170"),\
    _T("171"),\
    _T("172"),\
    _T("173"),\
    _T("174"),\
    _T("175"),\
    _T("176"),\
    _T("177"),\
    _T("178"),\
    _T("179"),\
    _T("180"),\
    _T("181"),\
    _T("182"),\
    _T("183"),\
    _T("184"),\
    _T("185"),\
    _T("186"),\
    _T("187"),\
    _T("188"),\
    _T("189"),\
    _T("190"),\
    _T("191"),\
    _T("192"),\
    _T("193"),\
    _T("194"),\
    _T("195"),\
    _T("196"),\
    _T("197"),\
    _T("198"),\
    _T("199"),\
    _T("200"),\
    _T("201"),\
    _T("202"),\
    _T("203"),\
    _T("204"),\
    _T("205"),\
    _T("206"),\
    _T("207"),\
    _T("208"),\
    _T("209"),\
    _T("210"),\
    _T("211"),\
    _T("212"),\
    _T("213"),\
    _T("214"),\
    _T("215"),\
    _T("216"),\
    _T("217"),\
    _T("218"),\
    _T("219"),\
    _T("220"),\
    _T("221"),\
    _T("222"),\
    _T("223"),\
    _T("224"),\
    _T("225"),\
    _T("226"),\
    _T("227"),\
    _T("228"),\
    _T("229"),\
    _T("230"),\
    _T("231"),\
    _T("232"),\
    _T("233"),\
    _T("234"),\
    _T("235"),\
    _T("236"),\
    _T("237"),\
    _T("238"),\
    _T("239"),\
    _T("240"),\
    _T("241"),\
    _T("242"),\
    _T("243"),\
    _T("244"),\
    _T("245"),\
    _T("246"),\
    _T("247"),\
    _T("248"),\
    _T("249"),\
    _T("250"),\
    _T("251"),\
    _T("252"),\
    _T("253"),\
    _T("254"),\
    _T("255"),\
    _T("256"),\
    _T("257"),\
    _T("258"),\
    _T("259"),\
    _T("260"),\
    _T("261"),\
    _T("262"),\
    _T("263"),\
    _T("264"),\
    _T("265"),\
    _T("266"),\
    _T("267"),\
    _T("268"),\
    _T("269"),\
    _T("270"),\
    _T("271"),\
    _T("272"),\
    _T("273"),\
    _T("274"),\
    _T("275"),\
    _T("276"),\
    _T("277"),\
    _T("278"),\
    _T("279"),\
    _T("280"),\
    _T("281"),\
    _T("282"),\
    _T("283"),\
    _T("284"),\
    _T("285"),\
    _T("286"),\
    _T("287"),\
    _T("288"),\
    _T("289"),\
    _T("290"),\
    _T("291"),\
    _T("292"),\
    _T("293"),\
    _T("294"),\
    _T("295"),\
    _T("296"),\
    _T("297"),\
    _T("298"),\
    _T("299"),\
    _T("300"),\
    _T("301"),\
    _T("302"),\
    _T("303"),\
    _T("304"),\
    _T("305"),\
    _T("306"),\
    _T("307"),\
    _T("308"),\
    _T("309"),\
    _T("310"),\
    _T("311"),\
    _T("312"),\
    _T("313"),\
    _T("314"),\
    _T("315"),\
    _T("316"),\
    _T("317"),\
    _T("318"),\
    _T("319"),\
    _T("320"),\
    _T("321"),\
    _T("322"),\
    _T("323"),\
    _T("324"),\
    _T("325"),\
    _T("326"),\
    _T("327"),\
    _T("328"),\
    _T("329"),\
    _T("330"),\
    _T("331"),\
    _T("332"),\
    _T("333"),\
    _T("334"),\
    _T("335"),\
    _T("336"),\
    _T("337"),\
    _T("338"),\
    _T("339"),\
    _T("340"),\
    _T("341"),\
    _T("342"),\
    _T("343"),\
    _T("344"),\
    _T("345"),\
    _T("346"),\
    _T("347"),\
    _T("348"),\
    _T("349"),\
    _T("350"),\
    _T("351"),\
    _T("352"),\
    _T("353"),\
    _T("354"),\
    _T("355"),\
    _T("356"),\
    _T("357"),\
    _T("358"),\
    _T("359"),\
    _T("360"),\
    _T("361"),\
    _T("362"),\
    _T("363"),\
    _T("364"),\
    _T("365"),\
    _T("366"),\
    _T("367"),\
    _T("368"),\
    _T("369"),\
    _T("370"),\
    _T("371"),\
    _T("372"),\
    _T("373"),\
    _T("374"),\
    _T("375"),\
    _T("376"),\
    _T("377"),\
    _T("378"),\
    _T("379"),\
    _T("380"),\
    _T("381"),\
    _T("382"),\
    _T("383"),\
    _T("384"),\
    _T("385"),\
    _T("386"),\
    _T("387"),\
    _T("388"),\
    _T("389"),\
    _T("390"),\
    _T("391"),\
    _T("392"),\
    _T("393"),\
    _T("394"),\
    _T("395"),\
    _T("396"),\
    _T("397"),\
    _T("398"),\
    _T("399"),\
    _T("400"),\
    _T("401"),\
    _T("402"),\
    _T("403"),\
    _T("404"),\
    _T("405"),\
    _T("406"),\
    _T("407"),\
    _T("408"),\
    _T("409"),\
    _T("410"),\
    _T("411"),\
    _T("412"),\
    _T("413"),\
    _T("414"),\
    _T("415"),\
    _T("416"),\
    _T("417"),\
    _T("418"),\
    _T("419"),\
    _T("420"),\
    _T("421"),\
    _T("422"),\
    _T("423"),\
    _T("424"),\
    _T("425"),\
    _T("426"),\
    _T("427"),\
    _T("428"),\
    _T("429"),\
    _T("430"),\
    _T("431"),\
    _T("432"),\
    _T("433"),\
    _T("434"),\
    _T("435"),\
    _T("436"),\
    _T("437"),\
    _T("438"),\
    _T("439"),\
    _T("440"),\
    _T("441"),\
    _T("442"),\
    _T("443"),\
    _T("444"),\
    _T("445"),\
    _T("446"),\
    _T("447"),\
    _T("448"),\
    _T("449"),\
    _T("450"),\
    _T("451"),\
    _T("452"),\
    _T("453"),\
    _T("454"),\
    _T("455"),\
    _T("456"),\
    _T("457"),\
    _T("458"),\
    _T("459"),\
    _T("460"),\
    _T("461"),\
    _T("462"),\
    _T("463"),\
    _T("464"),\
    _T("465"),\
    _T("466"),\
    _T("467"),\
    _T("468"),\
    _T("469"),\
    _T("470"),\
    _T("471"),\
    _T("472"),\
    _T("473"),\
    _T("474"),\
    _T("475"),\
    _T("476"),\
    _T("477"),\
    _T("478"),\
    _T("479"),\
    _T("480"),\
    _T("481"),\
    _T("482"),\
    _T("483"),\
    _T("484"),\
    _T("485"),\
    _T("486"),\
    _T("487"),\
    _T("488"),\
    _T("489"),\
    _T("490"),\
    _T("491"),\
    _T("492"),\
    _T("493"),\
    _T("494"),\
    _T("495"),\
    _T("496"),\
    _T("497"),\
    _T("498"),\
    _T("499"),\
    _T("500"),\
    _T("501"),\
    _T("502"),\
    _T("503"),\
    _T("504"),\
    _T("505"),\
    _T("506"),\
    _T("507"),\
    _T("508"),\
    _T("509"),\
    _T("510"),\
    _T("511"),\
    _T("512"),\
    _T("513"),\
    _T("514"),\
    _T("515"),\
    _T("516"),\
    _T("517"),\
    _T("518"),\
    _T("519"),\
    _T("520"),\
    _T("521"),\
    _T("522"),\
    _T("523"),\
    _T("524"),\
    _T("525"),\
    _T("526"),\
    _T("527"),\
    _T("528"),\
    _T("529"),\
    _T("530"),\
    _T("531"),\
    _T("532"),\
    _T("533"),\
    _T("534"),\
    _T("535"),\
    _T("536"),\
    _T("537"),\
    _T("538"),\
    _T("539"),\
    _T("540"),\
    _T("541"),\
    _T("542"),\
    _T("543"),\
    _T("544"),\
    _T("545"),\
    _T("546"),\
    _T("547"),\
    _T("548"),\
    _T("549"),\
    _T("550"),\
    _T("551"),\
    _T("552"),\
    _T("553"),\
    _T("554"),\
    _T("555"),\
    _T("556"),\
    _T("557"),\
    _T("558"),\
    _T("559"),\
    _T("560"),\
    _T("561"),\
    _T("562"),\
    _T("563"),\
    _T("564"),\
    _T("565"),\
    _T("566"),\
    _T("567"),\
    _T("568"),\
    _T("569"),\
    _T("570"),\
    _T("571"),\
    _T("572"),\
    _T("573"),\
    _T("574"),\
    _T("575"),\
    _T("576"),\
    _T("577"),\
    _T("578"),\
    _T("579"),\
    _T("580"),\
    _T("581"),\
    _T("582"),\
    _T("583"),\
    _T("584"),\
    _T("585"),\
    _T("586"),\
    _T("587"),\
    _T("588"),\
    _T("589"),\
    _T("590"),\
    _T("591"),\
    _T("592"),\
    _T("593"),\
    _T("594"),\
    _T("595"),\
    _T("596"),\
    _T("597"),\
    _T("598"),\
    _T("599"),\
    _T("600"),\
    _T("601"),\
    _T("602"),\
    _T("603"),\
    _T("604"),\
    _T("605"),\
    _T("606"),\
    _T("607"),\
    _T("608"),\
    _T("609"),\
    _T("610"),\
    _T("611"),\
    _T("612"),\
    _T("613"),\
    _T("614"),\
    _T("615"),\
    _T("616"),\
    _T("617"),\
    _T("618"),\
    _T("619"),\
    _T("620"),\
    _T("621"),\
    _T("622"),\
    _T("623"),\
    _T("624"),\
    _T("625"),\
    _T("626"),\
    _T("627"),\
    _T("628"),\
    _T("629"),\
    _T("630"),\
    _T("631"),\
    _T("632"),\
    _T("633"),\
    _T("634"),\
    _T("635"),\
    _T("636"),\
    _T("637"),\
    _T("638"),\
    _T("639"),\
    _T("640"),\
    _T("641"),\
    _T("642"),\
    _T("643"),\
    _T("644"),\
    _T("645"),\
    _T("646"),\
    _T("647"),\
    _T("648"),\
    _T("649"),\
    _T("650"),\
    _T("651"),\
    _T("652"),\
    _T("653"),\
    _T("654"),\
    _T("655"),\
    _T("656"),\
    _T("657"),\
    _T("658"),\
    _T("659"),\
    _T("660"),\
    _T("661"),\
    _T("662"),\
    _T("663"),\
    _T("664"),\
    _T("665"),\
    _T("666"),\
    _T("667"),\
    _T("668"),\
    _T("669"),\
    _T("670"),\
    _T("671"),\
    _T("672"),\
    _T("673"),\
    _T("674"),\
    _T("675"),\
    _T("676"),\
    _T("677"),\
    _T("678"),\
    _T("679"),\
    _T("680"),\
    _T("681"),\
    _T("682"),\
    _T("683"),\
    _T("684"),\
    _T("685"),\
    _T("686"),\
    _T("687"),\
    _T("688"),\
    _T("689"),\
    _T("690"),\
    _T("691"),\
    _T("692"),\
    _T("693"),\
    _T("694"),\
    _T("695"),\
    _T("696"),\
    _T("697"),\
    _T("698"),\
    _T("699"),\
    _T("700"),\
    _T("701"),\
    _T("702"),\
    _T("703"),\
    _T("704"),\
    _T("705"),\
    _T("706"),\
    _T("707"),\
    _T("708"),\
    _T("709"),\
    _T("710"),\
    _T("711"),\
    _T("712"),\
    _T("713"),\
    _T("714"),\
    _T("715"),\
    _T("716"),\
    _T("717"),\
    _T("718"),\
    _T("719"),\
    _T("720"),\
    _T("721"),\
    _T("722"),\
    _T("723"),\
    _T("724"),\
    _T("725"),\
    _T("726"),\
    _T("727"),\
    _T("728"),\
    _T("729"),\
    _T("730"),\
    _T("731"),\
    _T("732"),\
    _T("733"),\
    _T("734"),\
    _T("735"),\
    _T("736"),\
    _T("737"),\
    _T("738"),\
    _T("739"),\
    _T("740"),\
    _T("741"),\
    _T("742"),\
    _T("743"),\
    _T("744"),\
    _T("745"),\
    _T("746"),\
    _T("747"),\
    _T("748"),\
    _T("749"),\
    _T("750"),\
    _T("751"),\
    _T("752"),\
    _T("753"),\
    _T("754"),\
    _T("755"),\
    _T("756"),\
    _T("757"),\
    _T("758"),\
    _T("759"),\
    _T("760"),\
    _T("761"),\
    _T("762"),\
    _T("763"),\
    _T("764"),\
    _T("765"),\
    _T("766"),\
    _T("767"),\
    _T("768"),\
    _T("769"),\
    _T("770"),\
    _T("771"),\
    _T("772"),\
    _T("773"),\
    _T("774"),\
    _T("775"),\
    _T("776"),\
    _T("777"),\
    _T("778"),\
    _T("779"),\
    _T("780"),\
    _T("781"),\
    _T("782"),\
    _T("783"),\
    _T("784"),\
    _T("785"),\
    _T("786"),\
    _T("787"),\
    _T("788"),\
    _T("789"),\
    _T("790"),\
    _T("791"),\
    _T("792"),\
    _T("793"),\
    _T("794"),\
    _T("795"),\
    _T("796"),\
    _T("797"),\
    _T("798"),\
    _T("799"),\
    _T("800"),\
    _T("801"),\
    _T("802"),\
    _T("")
#endif // _DEBUG

#endif // __VPKRNHEADER_H__
