/*                                                                                     
// Copyright (c) 2017 Intel Corporation                                                
//                                                                                     
// Permission is hereby granted, free of charge, to any person obtaining a             
// copy of this software and associated documentation files (the                       
// 'Software'), to deal in the Software without restriction, including                 
// without limitation the rights to use, copy, modify, merge, publish,                 
// distribute, sublicense, and/or sell copies of the Software, and to                  
// permit persons to whom the Software is furnished to do so, subject to               
// the following conditions:                                                           
//                                                                                     
// The above copyright notice and this permission notice shall be included             
// in all copies or substantial portions of the Software.                              
//                                                                                     
// THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS             
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF                          
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.              
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY                
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,                
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE                   
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                              
*/                                                                                     
                                                                                       
////////////////////////////////////////////////////////////////////////////////       
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!                        
// Generated by GenKrnBin.exe tool                                                     
////////////////////////////////////////////////////////////////////////////////       
#ifndef __VPKRNHEADER_H__
#define __VPKRNHEADER_H__

#define IDR_VP_LINKFILE_VERSION 65536
#define IDR_VP_LINKFILE_HEADER 16

#define IDR_VP_3DLUT 0
#define IDR_VP_AlphaSrcBlendG 1
#define IDR_VP_ByteCopy 2
#define IDR_VP_ByteCopy_MediaWalker 3
#define IDR_VP_CSC_444_16 4
#define IDR_VP_CSC_Premultiplied_444_16 5
#define IDR_VP_Call_AlphaSrcBlendG 6
#define IDR_VP_Call_CSC 7
#define IDR_VP_Call_CSC_Premultiplied 8
#define IDR_VP_Call_ColorE 9
#define IDR_VP_Call_Composite 10
#define IDR_VP_Call_ConstBlend 11
#define IDR_VP_Call_ConstSrcBlend 12
#define IDR_VP_Call_GammaC 13
#define IDR_VP_Call_Mirror_H_YUV 14
#define IDR_VP_Call_Mirror_H_YUVA 15
#define IDR_VP_Call_PartBlend 16
#define IDR_VP_Call_SrcBlend 17
#define IDR_VP_Call_SrcBlend_4bits 18
#define IDR_VP_ColorE 19
#define IDR_VP_Colorfill_444AVS16 20
#define IDR_VP_Colorfill_444AVS16_ConstBlend 21
#define IDR_VP_Colorfill_444AVS16_ConstSrcBlend 22
#define IDR_VP_Colorfill_444AVS16_PartBlend 23
#define IDR_VP_Colorfill_444AVS16_SrcBlend 24
#define IDR_VP_Colorfill_444Scale16 25
#define IDR_VP_Colorfill_444Scale16_ConstBlend 26
#define IDR_VP_Colorfill_444Scale16_ConstSrcBlend 27
#define IDR_VP_Colorfill_444Scale16_PartBlend 28
#define IDR_VP_Colorfill_444Scale16_SrcBlend 29
#define IDR_VP_Composite_444_16 30
#define IDR_VP_Compute_Lumakey 31
#define IDR_VP_Compute_Lumakey_Buf0123 32
#define IDR_VP_ConstBlend_444_16 33
#define IDR_VP_ConstSrcBlend_444_16 34
#define IDR_VP_EOT 35
#define IDR_VP_FMD_Summation 36
#define IDR_VP_FRC_Clean_Map 37
#define IDR_VP_FRC_GMV_Detection 38
#define IDR_VP_FRC_GMV_Sanity_Check 39
#define IDR_VP_FRC_GradUV 40
#define IDR_VP_FRC_GradY 41
#define IDR_VP_FRC_MC 42
#define IDR_VP_FRC_ME_Level1 43
#define IDR_VP_FRC_ME_Level2 44
#define IDR_VP_FRC_ME_Level3 45
#define IDR_VP_FRC_MV_Level1 46
#define IDR_VP_FRC_MV_Level2 47
#define IDR_VP_FRC_MV_Level3 48
#define IDR_VP_FRC_PS 49
#define IDR_VP_FRC_SPD_Map 50
#define IDR_VP_FRC_TempDiff 51
#define IDR_VP_FRC_TempDiff_HD 52
#define IDR_VP_FRC_WSD 53
#define IDR_VP_GammaC 54
#define IDR_VP_GeoCorrection 55
#define IDR_VP_HDR_mandatory 56
#define IDR_VP_HDR_per_frame_stat 57
#define IDR_VP_IS_DS 58
#define IDR_VP_IS_FW 59
#define IDR_VP_IS_GMC 60
#define IDR_VP_IS_ME 61
#define IDR_VP_Interlace_420_16_Buf_0 62
#define IDR_VP_Interlace_420_16_Buf_1 63
#define IDR_VP_Interlace_420_16_Buf_2 64
#define IDR_VP_Interlace_420_16_Buf_3 65
#define IDR_VP_Interlace_444AVS16_Buf_0 66
#define IDR_VP_Interlace_444AVS16_Buf_1 67
#define IDR_VP_Interlace_444AVS16_Buf_2 68
#define IDR_VP_Interlace_444AVS16_Buf_3 69
#define IDR_VP_Interlace_444_16_Buf_0 70
#define IDR_VP_Interlace_444_16_Buf_1 71
#define IDR_VP_Interlace_444_16_Buf_2 72
#define IDR_VP_Interlace_444_16_Buf_3 73
#define IDR_VP_LACE_HIST_SUM 74
#define IDR_VP_LACE_LUT 75
#define IDR_VP_LACE_PWLF 76
#define IDR_VP_LACE_STD 77
#define IDR_VP_LinkFile 78
#define IDR_VP_Mirror_AVS_H_L0 79
#define IDR_VP_Mirror_AVS_V_L0 80
#define IDR_VP_Mirror_H_YUV 81
#define IDR_VP_Mirror_H_YUVA 82
#define IDR_VP_Mirror_scale_H_L0 83
#define IDR_VP_Mirror_scale_V_L0 84
#define IDR_VP_NV12_DP_rotation_avg 85
#define IDR_VP_NV12_DP_rotation_nv12 86
#define IDR_VP_NV12_DP_rotation_rep 87
#define IDR_VP_P010_444Dscale16_Buf_0 88
#define IDR_VP_P010_444Dscale16_Buf_0_Rot_180 89
#define IDR_VP_P010_444Dscale16_Buf_0_Rot_270 90
#define IDR_VP_P010_444Dscale16_Buf_0_Rot_90 91
#define IDR_VP_P010_444Dscale16_Buf_1 92
#define IDR_VP_P010_444Dscale16_Buf_1_Rot_180 93
#define IDR_VP_P010_444Dscale16_Buf_1_Rot_270 94
#define IDR_VP_P010_444Dscale16_Buf_1_Rot_90 95
#define IDR_VP_P010_444Dscale16_Buf_2 96
#define IDR_VP_P010_444Dscale16_Buf_2_Rot_180 97
#define IDR_VP_P010_444Dscale16_Buf_2_Rot_270 98
#define IDR_VP_P010_444Dscale16_Buf_2_Rot_90 99
#define IDR_VP_P010_444Dscale16_Buf_3 100
#define IDR_VP_P010_444Dscale16_Buf_3_Rot_180 101
#define IDR_VP_P010_444Dscale16_Buf_3_Rot_270 102
#define IDR_VP_P010_444Dscale16_Buf_3_Rot_90 103
#define IDR_VP_PA_444AVS16_Buf_0 104
#define IDR_VP_PA_444AVS16_Buf_0_Rot_180 105
#define IDR_VP_PA_444AVS16_Buf_0_Rot_270 106
#define IDR_VP_PA_444AVS16_Buf_0_Rot_90 107
#define IDR_VP_PA_444AVS16_Buf_1 108
#define IDR_VP_PA_444AVS16_Buf_1_Rot_180 109
#define IDR_VP_PA_444AVS16_Buf_1_Rot_270 110
#define IDR_VP_PA_444AVS16_Buf_1_Rot_90 111
#define IDR_VP_PA_444AVS16_Buf_2 112
#define IDR_VP_PA_444AVS16_Buf_2_Rot_180 113
#define IDR_VP_PA_444AVS16_Buf_2_Rot_270 114
#define IDR_VP_PA_444AVS16_Buf_2_Rot_90 115
#define IDR_VP_PA_444AVS16_Buf_3 116
#define IDR_VP_PA_444AVS16_Buf_3_Rot_180 117
#define IDR_VP_PA_444AVS16_Buf_3_Rot_270 118
#define IDR_VP_PA_444AVS16_Buf_3_Rot_90 119
#define IDR_VP_PA_444AVS16_Buf_4 120
#define IDR_VP_PA_444AVS16_Buf_4_Rot_180 121
#define IDR_VP_PA_444AVS16_Buf_4_Rot_270 122
#define IDR_VP_PA_444AVS16_Buf_4_Rot_90 123
#define IDR_VP_PA_444AVS16_Buf_5 124
#define IDR_VP_PA_444AVS16_Buf_5_Rot_180 125
#define IDR_VP_PA_444AVS16_Buf_5_Rot_270 126
#define IDR_VP_PA_444AVS16_Buf_5_Rot_90 127
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_0 128
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_1 129
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_2 130
#define IDR_VP_PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_3 131
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_0 132
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_1 133
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_2 134
#define IDR_VP_PA_444AVS16_HDC_DW_Y8_UNORM_Buf_3 135
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_0 136
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_1 137
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_2 138
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_3 139
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_0 140
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_1 141
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_2 142
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_3 143
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_0 144
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_1 145
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_2 146
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_3 147
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_0 148
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_1 149
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_2 150
#define IDR_VP_PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_3 151
#define IDR_VP_PA_444DScale16_Buf_0 152
#define IDR_VP_PA_444DScale16_Buf_0_Rot_180 153
#define IDR_VP_PA_444DScale16_Buf_0_Rot_270 154
#define IDR_VP_PA_444DScale16_Buf_0_Rot_90 155
#define IDR_VP_PA_444DScale16_Buf_1 156
#define IDR_VP_PA_444DScale16_Buf_1_Rot_180 157
#define IDR_VP_PA_444DScale16_Buf_1_Rot_270 158
#define IDR_VP_PA_444DScale16_Buf_1_Rot_90 159
#define IDR_VP_PA_444DScale16_Buf_2 160
#define IDR_VP_PA_444DScale16_Buf_2_Rot_180 161
#define IDR_VP_PA_444DScale16_Buf_2_Rot_270 162
#define IDR_VP_PA_444DScale16_Buf_2_Rot_90 163
#define IDR_VP_PA_444DScale16_Buf_3 164
#define IDR_VP_PA_444DScale16_Buf_3_Rot_180 165
#define IDR_VP_PA_444DScale16_Buf_3_Rot_270 166
#define IDR_VP_PA_444DScale16_Buf_3_Rot_90 167
#define IDR_VP_PA_444DScale16_Buf_4 168
#define IDR_VP_PA_444DScale16_Buf_4_Rot_180 169
#define IDR_VP_PA_444DScale16_Buf_4_Rot_270 170
#define IDR_VP_PA_444DScale16_Buf_4_Rot_90 171
#define IDR_VP_PA_444DScale16_Buf_5 172
#define IDR_VP_PA_444DScale16_Buf_5_Rot_180 173
#define IDR_VP_PA_444DScale16_Buf_5_Rot_270 174
#define IDR_VP_PA_444DScale16_Buf_5_Rot_90 175
#define IDR_VP_PA_444Scale16_Buf_0 176
#define IDR_VP_PA_444Scale16_Buf_0_Rot_180 177
#define IDR_VP_PA_444Scale16_Buf_0_Rot_270 178
#define IDR_VP_PA_444Scale16_Buf_0_Rot_90 179
#define IDR_VP_PA_444Scale16_Buf_1 180
#define IDR_VP_PA_444Scale16_Buf_1_Rot_180 181
#define IDR_VP_PA_444Scale16_Buf_1_Rot_270 182
#define IDR_VP_PA_444Scale16_Buf_1_Rot_90 183
#define IDR_VP_PA_444Scale16_Buf_2 184
#define IDR_VP_PA_444Scale16_Buf_2_Rot_180 185
#define IDR_VP_PA_444Scale16_Buf_2_Rot_270 186
#define IDR_VP_PA_444Scale16_Buf_2_Rot_90 187
#define IDR_VP_PA_444Scale16_Buf_3 188
#define IDR_VP_PA_444Scale16_Buf_3_Rot_180 189
#define IDR_VP_PA_444Scale16_Buf_3_Rot_270 190
#define IDR_VP_PA_444Scale16_Buf_3_Rot_90 191
#define IDR_VP_PA_444Scale16_Buf_4 192
#define IDR_VP_PA_444Scale16_Buf_4_Rot_180 193
#define IDR_VP_PA_444Scale16_Buf_4_Rot_270 194
#define IDR_VP_PA_444Scale16_Buf_4_Rot_90 195
#define IDR_VP_PA_444Scale16_Buf_5 196
#define IDR_VP_PA_444Scale16_Buf_5_Rot_180 197
#define IDR_VP_PA_444Scale16_Buf_5_Rot_270 198
#define IDR_VP_PA_444Scale16_Buf_5_Rot_90 199
#define IDR_VP_PA_444iAVS16_Buf_0 200
#define IDR_VP_PA_444iAVS16_Buf_1 201
#define IDR_VP_PA_444iAVS16_Buf_2 202
#define IDR_VP_PA_444iAVS16_Buf_3 203
#define IDR_VP_PA_444iDScale16_Buf_0 204
#define IDR_VP_PA_444iDScale16_Buf_1 205
#define IDR_VP_PA_444iDScale16_Buf_2 206
#define IDR_VP_PA_444iDScale16_Buf_3 207
#define IDR_VP_PA_444iScale16_Buf_0 208
#define IDR_VP_PA_444iScale16_Buf_0_Rot_180 209
#define IDR_VP_PA_444iScale16_Buf_0_Rot_270 210
#define IDR_VP_PA_444iScale16_Buf_0_Rot_90 211
#define IDR_VP_PA_444iScale16_Buf_1 212
#define IDR_VP_PA_444iScale16_Buf_1_Rot_180 213
#define IDR_VP_PA_444iScale16_Buf_1_Rot_270 214
#define IDR_VP_PA_444iScale16_Buf_1_Rot_90 215
#define IDR_VP_PA_444iScale16_Buf_2 216
#define IDR_VP_PA_444iScale16_Buf_2_Rot_180 217
#define IDR_VP_PA_444iScale16_Buf_2_Rot_270 218
#define IDR_VP_PA_444iScale16_Buf_2_Rot_90 219
#define IDR_VP_PA_444iScale16_Buf_3 220
#define IDR_VP_PA_444iScale16_Buf_3_Rot_180 221
#define IDR_VP_PA_444iScale16_Buf_3_Rot_270 222
#define IDR_VP_PA_444iScale16_Buf_3_Rot_90 223
#define IDR_VP_PA_AVS_Mirror_H_L0 224
#define IDR_VP_PA_AVS_Mirror_V_L0 225
#define IDR_VP_PA_AVS_Rotate_90_Mirror_H_L0 226
#define IDR_VP_PA_AVS_Rotate_90_Mirror_V_L0 227
#define IDR_VP_PA_AVS_Rotate_L0_180 228
#define IDR_VP_PA_AVS_Rotate_L0_270 229
#define IDR_VP_PA_AVS_Rotate_L0_90 230
#define IDR_VP_PA_Copy 231
#define IDR_VP_PA_Scale_Mirror_H_L0 232
#define IDR_VP_PA_Scale_Mirror_V_L0 233
#define IDR_VP_PA_Scale_Rotate90_Mirror_H_L0 234
#define IDR_VP_PA_Scale_Rotate90_Mirror_V_L0 235
#define IDR_VP_PA_Scale_Rotate_L0_180 236
#define IDR_VP_PA_Scale_Rotate_L0_270 237
#define IDR_VP_PA_Scale_Rotate_L0_90 238
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_0 239
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_1 240
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_2 241
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_3 242
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_4 243
#define IDR_VP_PL2_422AVS16_ChromaSiting_Buf_5 244
#define IDR_VP_PL2_444AVS16_Buf_0 245
#define IDR_VP_PL2_444AVS16_Buf_0_Rot_180 246
#define IDR_VP_PL2_444AVS16_Buf_0_Rot_270 247
#define IDR_VP_PL2_444AVS16_Buf_0_Rot_90 248
#define IDR_VP_PL2_444AVS16_Buf_1 249
#define IDR_VP_PL2_444AVS16_Buf_1_Rot_180 250
#define IDR_VP_PL2_444AVS16_Buf_1_Rot_270 251
#define IDR_VP_PL2_444AVS16_Buf_1_Rot_90 252
#define IDR_VP_PL2_444AVS16_Buf_2 253
#define IDR_VP_PL2_444AVS16_Buf_2_Rot_180 254
#define IDR_VP_PL2_444AVS16_Buf_2_Rot_270 255
#define IDR_VP_PL2_444AVS16_Buf_2_Rot_90 256
#define IDR_VP_PL2_444AVS16_Buf_3 257
#define IDR_VP_PL2_444AVS16_Buf_3_Rot_180 258
#define IDR_VP_PL2_444AVS16_Buf_3_Rot_270 259
#define IDR_VP_PL2_444AVS16_Buf_3_Rot_90 260
#define IDR_VP_PL2_444AVS16_Buf_4 261
#define IDR_VP_PL2_444AVS16_Buf_4_Rot_180 262
#define IDR_VP_PL2_444AVS16_Buf_4_Rot_270 263
#define IDR_VP_PL2_444AVS16_Buf_4_Rot_90 264
#define IDR_VP_PL2_444AVS16_Buf_5 265
#define IDR_VP_PL2_444AVS16_Buf_5_Rot_180 266
#define IDR_VP_PL2_444AVS16_Buf_5_Rot_270 267
#define IDR_VP_PL2_444AVS16_Buf_5_Rot_90 268
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4 269
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4_Rot_180 270
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4_Rot_270 271
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_4_Rot_90 272
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5 273
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5_Rot_180 274
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5_Rot_270 275
#define IDR_VP_PL2_444AVS16_Buf_Sep_Alpha_5_Rot_90 276
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_0 277
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_1 278
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_2 279
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_3 280
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_4 281
#define IDR_VP_PL2_444AVS16_ChromaSiting_Buf_5 282
#define IDR_VP_PL2_444DScale16_Buf_0 283
#define IDR_VP_PL2_444DScale16_Buf_0_Rot_180 284
#define IDR_VP_PL2_444DScale16_Buf_0_Rot_270 285
#define IDR_VP_PL2_444DScale16_Buf_0_Rot_90 286
#define IDR_VP_PL2_444DScale16_Buf_1 287
#define IDR_VP_PL2_444DScale16_Buf_1_Rot_180 288
#define IDR_VP_PL2_444DScale16_Buf_1_Rot_270 289
#define IDR_VP_PL2_444DScale16_Buf_1_Rot_90 290
#define IDR_VP_PL2_444DScale16_Buf_2 291
#define IDR_VP_PL2_444DScale16_Buf_2_Rot_180 292
#define IDR_VP_PL2_444DScale16_Buf_2_Rot_270 293
#define IDR_VP_PL2_444DScale16_Buf_2_Rot_90 294
#define IDR_VP_PL2_444DScale16_Buf_3 295
#define IDR_VP_PL2_444DScale16_Buf_3_Rot_180 296
#define IDR_VP_PL2_444DScale16_Buf_3_Rot_270 297
#define IDR_VP_PL2_444DScale16_Buf_3_Rot_90 298
#define IDR_VP_PL2_444DScale16_Buf_4 299
#define IDR_VP_PL2_444DScale16_Buf_4_Rot_180 300
#define IDR_VP_PL2_444DScale16_Buf_4_Rot_270 301
#define IDR_VP_PL2_444DScale16_Buf_4_Rot_90 302
#define IDR_VP_PL2_444DScale16_Buf_5 303
#define IDR_VP_PL2_444DScale16_Buf_5_Rot_180 304
#define IDR_VP_PL2_444DScale16_Buf_5_Rot_270 305
#define IDR_VP_PL2_444DScale16_Buf_5_Rot_90 306
#define IDR_VP_PL2_444DScale16_Buf_Sep_Alpha_4 307
#define IDR_VP_PL2_444DScale16_Buf_Sep_Alpha_5 308
#define IDR_VP_PL2_444Scale16_Buf_0 309
#define IDR_VP_PL2_444Scale16_Buf_0_Rot_180 310
#define IDR_VP_PL2_444Scale16_Buf_0_Rot_270 311
#define IDR_VP_PL2_444Scale16_Buf_0_Rot_90 312
#define IDR_VP_PL2_444Scale16_Buf_1 313
#define IDR_VP_PL2_444Scale16_Buf_1_Rot_180 314
#define IDR_VP_PL2_444Scale16_Buf_1_Rot_270 315
#define IDR_VP_PL2_444Scale16_Buf_1_Rot_90 316
#define IDR_VP_PL2_444Scale16_Buf_2 317
#define IDR_VP_PL2_444Scale16_Buf_2_Rot_180 318
#define IDR_VP_PL2_444Scale16_Buf_2_Rot_270 319
#define IDR_VP_PL2_444Scale16_Buf_2_Rot_90 320
#define IDR_VP_PL2_444Scale16_Buf_3 321
#define IDR_VP_PL2_444Scale16_Buf_3_Rot_180 322
#define IDR_VP_PL2_444Scale16_Buf_3_Rot_270 323
#define IDR_VP_PL2_444Scale16_Buf_3_Rot_90 324
#define IDR_VP_PL2_444Scale16_Buf_4 325
#define IDR_VP_PL2_444Scale16_Buf_4_Rot_180 326
#define IDR_VP_PL2_444Scale16_Buf_4_Rot_270 327
#define IDR_VP_PL2_444Scale16_Buf_4_Rot_90 328
#define IDR_VP_PL2_444Scale16_Buf_5 329
#define IDR_VP_PL2_444Scale16_Buf_5_Rot_180 330
#define IDR_VP_PL2_444Scale16_Buf_5_Rot_270 331
#define IDR_VP_PL2_444Scale16_Buf_5_Rot_90 332
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4 333
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4_Rot_180 334
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4_Rot_270 335
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_4_Rot_90 336
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5 337
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5_Rot_180 338
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5_Rot_270 339
#define IDR_VP_PL2_444Scale16_Buf_Sep_Alpha_5_Rot_90 340
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0 341
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0_Rot_180 342
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0_Rot_270 343
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_0_Rot_90 344
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1 345
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1_Rot_180 346
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1_Rot_270 347
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_1_Rot_90 348
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2 349
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2_Rot_180 350
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2_Rot_270 351
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_2_Rot_90 352
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3 353
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3_Rot_180 354
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3_Rot_270 355
#define IDR_VP_PL2_444Scale16_Chromasiting_Buf_3_Rot_90 356
#define IDR_VP_PL2_444iDScale16_Buf_0 357
#define IDR_VP_PL2_444iDScale16_Buf_1 358
#define IDR_VP_PL2_444iDScale16_Buf_2 359
#define IDR_VP_PL2_444iDScale16_Buf_3 360
#define IDR_VP_PL2_444iScale16_Buf_0 361
#define IDR_VP_PL2_444iScale16_Buf_0_Rot_180 362
#define IDR_VP_PL2_444iScale16_Buf_0_Rot_270 363
#define IDR_VP_PL2_444iScale16_Buf_0_Rot_90 364
#define IDR_VP_PL2_444iScale16_Buf_1 365
#define IDR_VP_PL2_444iScale16_Buf_1_Rot_180 366
#define IDR_VP_PL2_444iScale16_Buf_1_Rot_270 367
#define IDR_VP_PL2_444iScale16_Buf_1_Rot_90 368
#define IDR_VP_PL2_444iScale16_Buf_2 369
#define IDR_VP_PL2_444iScale16_Buf_2_Rot_180 370
#define IDR_VP_PL2_444iScale16_Buf_2_Rot_270 371
#define IDR_VP_PL2_444iScale16_Buf_2_Rot_90 372
#define IDR_VP_PL2_444iScale16_Buf_3 373
#define IDR_VP_PL2_444iScale16_Buf_3_Rot_180 374
#define IDR_VP_PL2_444iScale16_Buf_3_Rot_270 375
#define IDR_VP_PL2_444iScale16_Buf_3_Rot_90 376
#define IDR_VP_PL2_AVS_Mirror_H_L0 377
#define IDR_VP_PL2_AVS_Mirror_H_L0_DualOutput 378
#define IDR_VP_PL2_AVS_Mirror_V_L0 379
#define IDR_VP_PL2_AVS_Rotate90_Mirror_H_L0 380
#define IDR_VP_PL2_AVS_Rotate90_Mirror_V_L0 381
#define IDR_VP_PL2_AVS_Rotate_L0_180 382
#define IDR_VP_PL2_AVS_Rotate_L0_270 383
#define IDR_VP_PL2_AVS_Rotate_L0_90 384
#define IDR_VP_PL2_Copy 385
#define IDR_VP_PL2_Scale_Mirror_H_L0 386
#define IDR_VP_PL2_Scale_Mirror_H_L0_DualOutput 387
#define IDR_VP_PL2_Scale_Mirror_V_L0 388
#define IDR_VP_PL2_Scale_Rotate90_Mirror_H_L0 389
#define IDR_VP_PL2_Scale_Rotate90_Mirror_V_L0 390
#define IDR_VP_PL2_Scale_Rotate_L0_180 391
#define IDR_VP_PL2_Scale_Rotate_L0_270 392
#define IDR_VP_PL2_Scale_Rotate_L0_90 393
#define IDR_VP_PL3_444AVS16_Buf_0 394
#define IDR_VP_PL3_444AVS16_Buf_0_Rot_180 395
#define IDR_VP_PL3_444AVS16_Buf_0_Rot_270 396
#define IDR_VP_PL3_444AVS16_Buf_0_Rot_90 397
#define IDR_VP_PL3_444AVS16_Buf_1 398
#define IDR_VP_PL3_444AVS16_Buf_1_Rot_180 399
#define IDR_VP_PL3_444AVS16_Buf_1_Rot_270 400
#define IDR_VP_PL3_444AVS16_Buf_1_Rot_90 401
#define IDR_VP_PL3_444AVS16_Buf_2 402
#define IDR_VP_PL3_444AVS16_Buf_2_Rot_180 403
#define IDR_VP_PL3_444AVS16_Buf_2_Rot_270 404
#define IDR_VP_PL3_444AVS16_Buf_2_Rot_90 405
#define IDR_VP_PL3_444AVS16_Buf_3 406
#define IDR_VP_PL3_444AVS16_Buf_3_Rot_180 407
#define IDR_VP_PL3_444AVS16_Buf_3_Rot_270 408
#define IDR_VP_PL3_444AVS16_Buf_3_Rot_90 409
#define IDR_VP_PL3_444AVS16_Buf_4 410
#define IDR_VP_PL3_444AVS16_Buf_4_Rot_180 411
#define IDR_VP_PL3_444AVS16_Buf_4_Rot_270 412
#define IDR_VP_PL3_444AVS16_Buf_4_Rot_90 413
#define IDR_VP_PL3_444AVS16_Buf_5 414
#define IDR_VP_PL3_444AVS16_Buf_5_Rot_180 415
#define IDR_VP_PL3_444AVS16_Buf_5_Rot_270 416
#define IDR_VP_PL3_444AVS16_Buf_5_Rot_90 417
#define IDR_VP_PL3_444DScale16_Buf_0 418
#define IDR_VP_PL3_444DScale16_Buf_0_Rot_180 419
#define IDR_VP_PL3_444DScale16_Buf_0_Rot_270 420
#define IDR_VP_PL3_444DScale16_Buf_0_Rot_90 421
#define IDR_VP_PL3_444DScale16_Buf_1 422
#define IDR_VP_PL3_444DScale16_Buf_1_Rot_180 423
#define IDR_VP_PL3_444DScale16_Buf_1_Rot_270 424
#define IDR_VP_PL3_444DScale16_Buf_1_Rot_90 425
#define IDR_VP_PL3_444DScale16_Buf_2 426
#define IDR_VP_PL3_444DScale16_Buf_2_Rot_180 427
#define IDR_VP_PL3_444DScale16_Buf_2_Rot_270 428
#define IDR_VP_PL3_444DScale16_Buf_2_Rot_90 429
#define IDR_VP_PL3_444DScale16_Buf_3 430
#define IDR_VP_PL3_444DScale16_Buf_3_Rot_180 431
#define IDR_VP_PL3_444DScale16_Buf_3_Rot_270 432
#define IDR_VP_PL3_444DScale16_Buf_3_Rot_90 433
#define IDR_VP_PL3_444DScale16_Buf_4 434
#define IDR_VP_PL3_444DScale16_Buf_4_Rot_180 435
#define IDR_VP_PL3_444DScale16_Buf_4_Rot_270 436
#define IDR_VP_PL3_444DScale16_Buf_4_Rot_90 437
#define IDR_VP_PL3_444DScale16_Buf_5 438
#define IDR_VP_PL3_444DScale16_Buf_5_Rot_180 439
#define IDR_VP_PL3_444DScale16_Buf_5_Rot_270 440
#define IDR_VP_PL3_444DScale16_Buf_5_Rot_90 441
#define IDR_VP_PL3_444Scale16_Buf_0 442
#define IDR_VP_PL3_444Scale16_Buf_0_Rot_180 443
#define IDR_VP_PL3_444Scale16_Buf_0_Rot_270 444
#define IDR_VP_PL3_444Scale16_Buf_0_Rot_90 445
#define IDR_VP_PL3_444Scale16_Buf_1 446
#define IDR_VP_PL3_444Scale16_Buf_1_Rot_180 447
#define IDR_VP_PL3_444Scale16_Buf_1_Rot_270 448
#define IDR_VP_PL3_444Scale16_Buf_1_Rot_90 449
#define IDR_VP_PL3_444Scale16_Buf_2 450
#define IDR_VP_PL3_444Scale16_Buf_2_Rot_180 451
#define IDR_VP_PL3_444Scale16_Buf_2_Rot_270 452
#define IDR_VP_PL3_444Scale16_Buf_2_Rot_90 453
#define IDR_VP_PL3_444Scale16_Buf_3 454
#define IDR_VP_PL3_444Scale16_Buf_3_Rot_180 455
#define IDR_VP_PL3_444Scale16_Buf_3_Rot_270 456
#define IDR_VP_PL3_444Scale16_Buf_3_Rot_90 457
#define IDR_VP_PL3_444Scale16_Buf_4 458
#define IDR_VP_PL3_444Scale16_Buf_4_Rot_180 459
#define IDR_VP_PL3_444Scale16_Buf_4_Rot_270 460
#define IDR_VP_PL3_444Scale16_Buf_4_Rot_90 461
#define IDR_VP_PL3_444Scale16_Buf_5 462
#define IDR_VP_PL3_444Scale16_Buf_5_Rot_180 463
#define IDR_VP_PL3_444Scale16_Buf_5_Rot_270 464
#define IDR_VP_PL3_444Scale16_Buf_5_Rot_90 465
#define IDR_VP_PL3_444iDScale16_Buf_0 466
#define IDR_VP_PL3_444iDScale16_Buf_1 467
#define IDR_VP_PL3_444iDScale16_Buf_2 468
#define IDR_VP_PL3_444iDScale16_Buf_3 469
#define IDR_VP_PL3_444iScale16_Buf_0 470
#define IDR_VP_PL3_444iScale16_Buf_0_Rot_180 471
#define IDR_VP_PL3_444iScale16_Buf_0_Rot_270 472
#define IDR_VP_PL3_444iScale16_Buf_0_Rot_90 473
#define IDR_VP_PL3_444iScale16_Buf_1 474
#define IDR_VP_PL3_444iScale16_Buf_1_Rot_180 475
#define IDR_VP_PL3_444iScale16_Buf_1_Rot_270 476
#define IDR_VP_PL3_444iScale16_Buf_1_Rot_90 477
#define IDR_VP_PL3_444iScale16_Buf_2 478
#define IDR_VP_PL3_444iScale16_Buf_2_Rot_180 479
#define IDR_VP_PL3_444iScale16_Buf_2_Rot_270 480
#define IDR_VP_PL3_444iScale16_Buf_2_Rot_90 481
#define IDR_VP_PL3_444iScale16_Buf_3 482
#define IDR_VP_PL3_444iScale16_Buf_3_Rot_180 483
#define IDR_VP_PL3_444iScale16_Buf_3_Rot_270 484
#define IDR_VP_PL3_444iScale16_Buf_3_Rot_90 485
#define IDR_VP_PL3_AVS_Rotate_L0_180 486
#define IDR_VP_PL3_AVS_Rotate_L0_270 487
#define IDR_VP_PL3_AVS_Rotate_L0_90 488
#define IDR_VP_PL3_Scale_Rotate_L0_180 489
#define IDR_VP_PL3_Scale_Rotate_L0_270 490
#define IDR_VP_PL3_Scale_Rotate_L0_90 491
#define IDR_VP_PLY_444DScale16_2f_Buf_0 492
#define IDR_VP_PLY_444DScale16_2f_Buf_1 493
#define IDR_VP_PLY_444DScale16_2f_Buf_2 494
#define IDR_VP_PLY_444DScale16_2f_Buf_3 495
#define IDR_VP_PLY_444DScale16_Buf_0 496
#define IDR_VP_PLY_444DScale16_Buf_0_Rot_180 497
#define IDR_VP_PLY_444DScale16_Buf_0_Rot_270 498
#define IDR_VP_PLY_444DScale16_Buf_0_Rot_90 499
#define IDR_VP_PLY_444DScale16_Buf_1 500
#define IDR_VP_PLY_444DScale16_Buf_1_Rot_180 501
#define IDR_VP_PLY_444DScale16_Buf_1_Rot_270 502
#define IDR_VP_PLY_444DScale16_Buf_1_Rot_90 503
#define IDR_VP_PLY_444DScale16_Buf_2 504
#define IDR_VP_PLY_444DScale16_Buf_2_Rot_180 505
#define IDR_VP_PLY_444DScale16_Buf_2_Rot_270 506
#define IDR_VP_PLY_444DScale16_Buf_2_Rot_90 507
#define IDR_VP_PLY_444DScale16_Buf_3 508
#define IDR_VP_PLY_444DScale16_Buf_3_Rot_180 509
#define IDR_VP_PLY_444DScale16_Buf_3_Rot_270 510
#define IDR_VP_PLY_444DScale16_Buf_3_Rot_90 511
#define IDR_VP_PartBlend_444_16 512
#define IDR_VP_Prepare_LumaKey_SampleUnorm 513
#define IDR_VP_RGB2sRGB 514
#define IDR_VP_Rotate_90_Mirror_AVS_H_L0 515
#define IDR_VP_Rotate_90_Mirror_AVS_V_L0 516
#define IDR_VP_Rotate_90_Mirror_H_scale_L0 517
#define IDR_VP_Rotate_90_Mirror_V_scale_L0 518
#define IDR_VP_Rotate_AVS_L0_180 519
#define IDR_VP_Rotate_AVS_L0_270 520
#define IDR_VP_Rotate_AVS_L0_90 521
#define IDR_VP_Rotate_Scale_L0_180 522
#define IDR_VP_Rotate_Scale_L0_270 523
#define IDR_VP_Rotate_Scale_L0_90 524
#define IDR_VP_SIP_Debug 525
#define IDR_VP_Save_444AVS16_ARGB 526
#define IDR_VP_Save_444AVS16_ARGB_64Byte 527
#define IDR_VP_Save_444AVS16_NV12 528
#define IDR_VP_Save_444AVS16_NV21 529
#define IDR_VP_Save_444AVS16_PA 530
#define IDR_VP_Save_444AVS16_PL3 531
#define IDR_VP_Save_444AVS16_R10G10B10 532
#define IDR_VP_Save_444AVS16_R10G10B10A2 533
#define IDR_VP_Save_444AVS16_R10G10B10X2 534
#define IDR_VP_Save_444AVS16_RGB 535
#define IDR_VP_Save_444AVS16_RGB16 536
#define IDR_VP_Save_444AVS16_RGB_64Byte 537
#define IDR_VP_Save_444AVS16_SrcAYUV 538
#define IDR_VP_Save_444AVS16_XRGB 539
#define IDR_VP_Save_444AVS16_XRGB_64Byte 540
#define IDR_VP_Save_444Scale16_ARGB 541
#define IDR_VP_Save_444Scale16_ARGB_64Byte 542
#define IDR_VP_Save_444Scale16_Dither_NV12 543
#define IDR_VP_Save_444Scale16_Dither_NV21 544
#define IDR_VP_Save_444Scale16_Dither_PA 545
#define IDR_VP_Save_444Scale16_Dither_PA_32X16 546
#define IDR_VP_Save_444Scale16_Dither_PL3 547
#define IDR_VP_Save_444Scale16_Dither_RGB 548
#define IDR_VP_Save_444Scale16_Dither_RGB_64Byte 549
#define IDR_VP_Save_444Scale16_Dither_VUYA 550
#define IDR_VP_Save_444Scale16_Dither_XRGB 551
#define IDR_VP_Save_444Scale16_Dither_XRGB_64Byte 552
#define IDR_VP_Save_444Scale16_NV12 553
#define IDR_VP_Save_444Scale16_NV21 554
#define IDR_VP_Save_444Scale16_P010 555
#define IDR_VP_Save_444Scale16_PA 556
#define IDR_VP_Save_444Scale16_PA_32X16 557
#define IDR_VP_Save_444Scale16_PL3 558
#define IDR_VP_Save_444Scale16_PLY 559
#define IDR_VP_Save_444Scale16_R10G10B10 560
#define IDR_VP_Save_444Scale16_R10G10B10A2 561
#define IDR_VP_Save_444Scale16_R10G10B10X2 562
#define IDR_VP_Save_444Scale16_R10G10B10XR 563
#define IDR_VP_Save_444Scale16_R10G10B10XRA2 564
#define IDR_VP_Save_444Scale16_R10G10B10XRX2 565
#define IDR_VP_Save_444Scale16_RGB 566
#define IDR_VP_Save_444Scale16_RGB16 567
#define IDR_VP_Save_444Scale16_RGBP 568
#define IDR_VP_Save_444Scale16_RGB_64Byte 569
#define IDR_VP_Save_444Scale16_SrcVUYA 570
#define IDR_VP_Save_444Scale16_VUYA 571
#define IDR_VP_Save_444Scale16_XRGB 572
#define IDR_VP_Save_444Scale16_XRGB_64Byte 573
#define IDR_VP_Save_444Scale16_Y210 574
#define IDR_VP_Save_444Scale16_Y216 575
#define IDR_VP_Save_444Scale16_Y410 576
#define IDR_VP_Save_444Scale16_Y416 577
#define IDR_VP_Secure_Block_Copy 578
#define IDR_VP_Set_Buf0_Buf4 579
#define IDR_VP_Set_Buf1_Buf5 580
#define IDR_VP_Set_Buf2_Buf4 581
#define IDR_VP_Set_Buf3_Buf5 582
#define IDR_VP_Set_CSC_Src_Buf0 583
#define IDR_VP_Set_CSC_Src_Buf1 584
#define IDR_VP_Set_CSC_Src_Buf2 585
#define IDR_VP_Set_CSC_Src_Buf3 586
#define IDR_VP_Set_CSC_Src_Buf4 587
#define IDR_VP_Set_CSC_Src_Buf5 588
#define IDR_VP_Set_CURBE_CSC_Coeff 589
#define IDR_VP_Set_ColorE_Src_Buf0 590
#define IDR_VP_Set_ColorE_Src_Buf1 591
#define IDR_VP_Set_ColorE_Src_Buf2 592
#define IDR_VP_Set_ColorE_Src_Buf3 593
#define IDR_VP_Set_Dest_Surf_Indexes_Primary 594
#define IDR_VP_Set_Dest_Surf_Indexes_Secondary 595
#define IDR_VP_Set_GammaC_Src_Buf0 596
#define IDR_VP_Set_GammaC_Src_Buf1 597
#define IDR_VP_Set_GammaC_Src_Buf2 598
#define IDR_VP_Set_GammaC_Src_Buf3 599
#define IDR_VP_Set_Layer_0 600
#define IDR_VP_Set_Layer_1 601
#define IDR_VP_Set_Layer_1_AVS 602
#define IDR_VP_Set_Layer_2 603
#define IDR_VP_Set_Layer_3 604
#define IDR_VP_Set_Layer_4 605
#define IDR_VP_Set_Layer_5 606
#define IDR_VP_Set_Layer_6 607
#define IDR_VP_Set_Layer_7 608
#define IDR_VP_Set_Patched_CSC_Coeff 609
#define IDR_VP_Set_Scale_Buf_0123_Colorfill 610
#define IDR_VP_Set_Sec_Half_Buf45 611
#define IDR_VP_Shuffle_444AVS16_Buf_0 612
#define IDR_VP_Shuffle_444AVS16_Buf_1 613
#define IDR_VP_Shuffle_444AVS16_Buf_2 614
#define IDR_VP_Shuffle_444AVS16_Buf_3 615
#define IDR_VP_Shuffle_444AVS16_Buf_4 616
#define IDR_VP_Shuffle_444AVS16_Buf_5 617
#define IDR_VP_SrcBlend_444_16 618
#define IDR_VP_SrcBlend_4bits_444_16 619
#define IDR_VP_UpdateDNState 620
#define IDR_VP_VP_Setup 621
#define IDR_VP_VP_Setup_MediaWalker 622
#define IDR_VP_VP_Setup_MediaWalker_32X16_Design 623
#define IDR_VP_VP_Setup_MediaWalker_32x32_Color 624
#define IDR_VP_Y210_444DScale16_Buf_0 625
#define IDR_VP_Y210_444DScale16_Buf_0_Rot_180 626
#define IDR_VP_Y210_444DScale16_Buf_0_Rot_270 627
#define IDR_VP_Y210_444DScale16_Buf_0_Rot_90 628
#define IDR_VP_Y210_444DScale16_Buf_1 629
#define IDR_VP_Y210_444DScale16_Buf_1_Rot_180 630
#define IDR_VP_Y210_444DScale16_Buf_1_Rot_270 631
#define IDR_VP_Y210_444DScale16_Buf_1_Rot_90 632
#define IDR_VP_Y210_444DScale16_Buf_2 633
#define IDR_VP_Y210_444DScale16_Buf_2_Rot_180 634
#define IDR_VP_Y210_444DScale16_Buf_2_Rot_270 635
#define IDR_VP_Y210_444DScale16_Buf_2_Rot_90 636
#define IDR_VP_Y210_444DScale16_Buf_3 637
#define IDR_VP_Y210_444DScale16_Buf_3_Rot_180 638
#define IDR_VP_Y210_444DScale16_Buf_3_Rot_270 639
#define IDR_VP_Y210_444DScale16_Buf_3_Rot_90 640
#define IDR_VP_Y210_444DScale16_Buf_4 641
#define IDR_VP_Y210_444DScale16_Buf_4_Rot_180 642
#define IDR_VP_Y210_444DScale16_Buf_4_Rot_270 643
#define IDR_VP_Y210_444DScale16_Buf_4_Rot_90 644
#define IDR_VP_Y210_444DScale16_Buf_5 645
#define IDR_VP_Y210_444DScale16_Buf_5_Rot_180 646
#define IDR_VP_Y210_444DScale16_Buf_5_Rot_270 647
#define IDR_VP_Y210_444DScale16_Buf_5_Rot_90 648
#define IDR_VP_Y210_444Scale16_Buf_0 649
#define IDR_VP_Y210_444Scale16_Buf_0_Rot_180 650
#define IDR_VP_Y210_444Scale16_Buf_0_Rot_270 651
#define IDR_VP_Y210_444Scale16_Buf_0_Rot_90 652
#define IDR_VP_Y210_444Scale16_Buf_1 653
#define IDR_VP_Y210_444Scale16_Buf_1_Rot_180 654
#define IDR_VP_Y210_444Scale16_Buf_1_Rot_270 655
#define IDR_VP_Y210_444Scale16_Buf_1_Rot_90 656
#define IDR_VP_Y210_444Scale16_Buf_2 657
#define IDR_VP_Y210_444Scale16_Buf_2_Rot_180 658
#define IDR_VP_Y210_444Scale16_Buf_2_Rot_270 659
#define IDR_VP_Y210_444Scale16_Buf_2_Rot_90 660
#define IDR_VP_Y210_444Scale16_Buf_3 661
#define IDR_VP_Y210_444Scale16_Buf_3_Rot_180 662
#define IDR_VP_Y210_444Scale16_Buf_3_Rot_270 663
#define IDR_VP_Y210_444Scale16_Buf_3_Rot_90 664
#define IDR_VP_Y210_444Scale16_Buf_4 665
#define IDR_VP_Y210_444Scale16_Buf_4_Rot_180 666
#define IDR_VP_Y210_444Scale16_Buf_4_Rot_270 667
#define IDR_VP_Y210_444Scale16_Buf_4_Rot_90 668
#define IDR_VP_Y210_444Scale16_Buf_5 669
#define IDR_VP_Y210_444Scale16_Buf_5_Rot_180 670
#define IDR_VP_Y210_444Scale16_Buf_5_Rot_270 671
#define IDR_VP_Y210_444Scale16_Buf_5_Rot_90 672
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0 673
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_180 674
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_270 675
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_90 676
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1 677
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_180 678
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_270 679
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_90 680
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2 681
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_180 682
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_270 683
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_90 684
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3 685
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_180 686
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_270 687
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_90 688
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4 689
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_180 690
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_270 691
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_90 692
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5 693
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_180 694
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_270 695
#define IDR_VP_Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_90 696
#define IDR_VP_Y410_444AVS16_Buf_0 697
#define IDR_VP_Y410_444AVS16_Buf_0_Rot_180 698
#define IDR_VP_Y410_444AVS16_Buf_0_Rot_270 699
#define IDR_VP_Y410_444AVS16_Buf_0_Rot_90 700
#define IDR_VP_Y410_444AVS16_Buf_1 701
#define IDR_VP_Y410_444AVS16_Buf_1_Rot_180 702
#define IDR_VP_Y410_444AVS16_Buf_1_Rot_270 703
#define IDR_VP_Y410_444AVS16_Buf_1_Rot_90 704
#define IDR_VP_Y410_444AVS16_Buf_2 705
#define IDR_VP_Y410_444AVS16_Buf_2_Rot_180 706
#define IDR_VP_Y410_444AVS16_Buf_2_Rot_270 707
#define IDR_VP_Y410_444AVS16_Buf_2_Rot_90 708
#define IDR_VP_Y410_444AVS16_Buf_3 709
#define IDR_VP_Y410_444AVS16_Buf_3_Rot_180 710
#define IDR_VP_Y410_444AVS16_Buf_3_Rot_270 711
#define IDR_VP_Y410_444AVS16_Buf_3_Rot_90 712
#define IDR_VP_Y410_444AVS16_Buf_4 713
#define IDR_VP_Y410_444AVS16_Buf_4_Rot_180 714
#define IDR_VP_Y410_444AVS16_Buf_4_Rot_270 715
#define IDR_VP_Y410_444AVS16_Buf_4_Rot_90 716
#define IDR_VP_Y410_444AVS16_Buf_5 717
#define IDR_VP_Y410_444AVS16_Buf_5_Rot_180 718
#define IDR_VP_Y410_444AVS16_Buf_5_Rot_270 719
#define IDR_VP_Y410_444AVS16_Buf_5_Rot_90 720
#define IDR_VP_Y410_444DScale16_Buf_0 721
#define IDR_VP_Y410_444DScale16_Buf_0_Rot_180 722
#define IDR_VP_Y410_444DScale16_Buf_0_Rot_270 723
#define IDR_VP_Y410_444DScale16_Buf_0_Rot_90 724
#define IDR_VP_Y410_444DScale16_Buf_1 725
#define IDR_VP_Y410_444DScale16_Buf_1_Rot_180 726
#define IDR_VP_Y410_444DScale16_Buf_1_Rot_270 727
#define IDR_VP_Y410_444DScale16_Buf_1_Rot_90 728
#define IDR_VP_Y410_444DScale16_Buf_2 729
#define IDR_VP_Y410_444DScale16_Buf_2_Rot_180 730
#define IDR_VP_Y410_444DScale16_Buf_2_Rot_270 731
#define IDR_VP_Y410_444DScale16_Buf_2_Rot_90 732
#define IDR_VP_Y410_444DScale16_Buf_3 733
#define IDR_VP_Y410_444DScale16_Buf_3_Rot_180 734
#define IDR_VP_Y410_444DScale16_Buf_3_Rot_270 735
#define IDR_VP_Y410_444DScale16_Buf_3_Rot_90 736
#define IDR_VP_Y410_444DScale16_Buf_4 737
#define IDR_VP_Y410_444DScale16_Buf_4_Rot_180 738
#define IDR_VP_Y410_444DScale16_Buf_4_Rot_270 739
#define IDR_VP_Y410_444DScale16_Buf_4_Rot_90 740
#define IDR_VP_Y410_444DScale16_Buf_5 741
#define IDR_VP_Y410_444DScale16_Buf_5_Rot_180 742
#define IDR_VP_Y410_444DScale16_Buf_5_Rot_270 743
#define IDR_VP_Y410_444DScale16_Buf_5_Rot_90 744
#define IDR_VP_Y410_444Scale16_Buf_0 745
#define IDR_VP_Y410_444Scale16_Buf_0_Rot_180 746
#define IDR_VP_Y410_444Scale16_Buf_0_Rot_270 747
#define IDR_VP_Y410_444Scale16_Buf_0_Rot_90 748
#define IDR_VP_Y410_444Scale16_Buf_1 749
#define IDR_VP_Y410_444Scale16_Buf_1_Rot_180 750
#define IDR_VP_Y410_444Scale16_Buf_1_Rot_270 751
#define IDR_VP_Y410_444Scale16_Buf_1_Rot_90 752
#define IDR_VP_Y410_444Scale16_Buf_2 753
#define IDR_VP_Y410_444Scale16_Buf_2_Rot_180 754
#define IDR_VP_Y410_444Scale16_Buf_2_Rot_270 755
#define IDR_VP_Y410_444Scale16_Buf_2_Rot_90 756
#define IDR_VP_Y410_444Scale16_Buf_3 757
#define IDR_VP_Y410_444Scale16_Buf_3_Rot_180 758
#define IDR_VP_Y410_444Scale16_Buf_3_Rot_270 759
#define IDR_VP_Y410_444Scale16_Buf_3_Rot_90 760
#define IDR_VP_Y410_444Scale16_Buf_4 761
#define IDR_VP_Y410_444Scale16_Buf_4_Rot_180 762
#define IDR_VP_Y410_444Scale16_Buf_4_Rot_270 763
#define IDR_VP_Y410_444Scale16_Buf_4_Rot_90 764
#define IDR_VP_Y410_444Scale16_Buf_5 765
#define IDR_VP_Y410_444Scale16_Buf_5_Rot_180 766
#define IDR_VP_Y410_444Scale16_Buf_5_Rot_270 767
#define IDR_VP_Y410_444Scale16_Buf_5_Rot_90 768
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0 769
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0_Rot_180 770
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0_Rot_270 771
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_0_Rot_90 772
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1 773
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1_Rot_180 774
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1_Rot_270 775
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_1_Rot_90 776
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2 777
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2_Rot_180 778
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2_Rot_270 779
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_2_Rot_90 780
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3 781
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3_Rot_180 782
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3_Rot_270 783
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_3_Rot_90 784
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4 785
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4_Rot_180 786
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4_Rot_270 787
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_4_Rot_90 788
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5 789
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5_Rot_180 790
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5_Rot_270 791
#define IDR_VP_YUY2_444Scale16_Chromasiting_Buf_5_Rot_90 792
#define IDR_VP_avs_scale_16aligned 793
#define IDR_VP_camera_pipe_CalcParams 794
#define IDR_VP_fast_avs_1_to_n 795
#define IDR_VP_return 796
#define IDR_VP_zzz_preproduction 797
#define IDR_VP_zzz_preproduction_ALLPL2Copy_Gen 798
#define IDR_VP_zzz_preproduction_HDR_mandatory_Gen 799
#define IDR_VP_zzz_preproduction_HDR_per_frame_stat_Gen 800
#define IDR_VP_zzz_preproduction_gcBltPS_32_To_128_Mirror_Gen 801
#define IDR_VP_zzz_preproduction_gcBltPS_64_To_128_Mirror_Gen 802
#define IDR_VP_zzz_preproduction_gcBltPS_Gen 803
#define IDR_VP_zzz_preproduction_gcClearNoReplicatePS_Gen 804
#define IDR_VP_zzz_preproduction_gcClearReplicatePS_Gen 805
#define IDR_VP_zzz_preproduction_gcColorFillNoReplicatePS_Gen 806
#define IDR_VP_zzz_preproduction_gcColorFillReplicatePS_Gen 807
#define IDR_VP_zzz_preproduction_gcFastClearReplicatePS_Gen 808
#define IDR_VP_zzz_production 809
#define IDR_VP_zzz_production_ALLPL2Copy_Gen 810
#define IDR_VP_zzz_production_HDR_mandatory_Gen 811
#define IDR_VP_zzz_production_HDR_per_frame_stat_Gen 812
#define IDR_VP_zzz_production_gcBltPS_32_To_128_Mirror_Gen 813
#define IDR_VP_zzz_production_gcBltPS_64_To_128_Mirror_Gen 814
#define IDR_VP_zzz_production_gcBltPS_Gen 815
#define IDR_VP_zzz_production_gcClearNoReplicatePS_Gen 816
#define IDR_VP_zzz_production_gcClearReplicatePS_Gen 817
#define IDR_VP_zzz_production_gcColorFillNoReplicatePS_Gen 818
#define IDR_VP_zzz_production_gcColorFillReplicatePS_Gen 819
#define IDR_VP_zzz_production_gcFastClearReplicatePS_Gen 820
#define IDR_VP_TOTAL_NUM_KERNELS 821

#if _DEBUG
#define IDR_VP_KERNEL_NAMES   \
    _T("3DLUT"),\
    _T("AlphaSrcBlendG"),\
    _T("ByteCopy"),\
    _T("ByteCopy_MediaWalker"),\
    _T("CSC_444_16"),\
    _T("CSC_Premultiplied_444_16"),\
    _T("Call_AlphaSrcBlendG"),\
    _T("Call_CSC"),\
    _T("Call_CSC_Premultiplied"),\
    _T("Call_ColorE"),\
    _T("Call_Composite"),\
    _T("Call_ConstBlend"),\
    _T("Call_ConstSrcBlend"),\
    _T("Call_GammaC"),\
    _T("Call_Mirror_H_YUV"),\
    _T("Call_Mirror_H_YUVA"),\
    _T("Call_PartBlend"),\
    _T("Call_SrcBlend"),\
    _T("Call_SrcBlend_4bits"),\
    _T("ColorE"),\
    _T("Colorfill_444AVS16"),\
    _T("Colorfill_444AVS16_ConstBlend"),\
    _T("Colorfill_444AVS16_ConstSrcBlend"),\
    _T("Colorfill_444AVS16_PartBlend"),\
    _T("Colorfill_444AVS16_SrcBlend"),\
    _T("Colorfill_444Scale16"),\
    _T("Colorfill_444Scale16_ConstBlend"),\
    _T("Colorfill_444Scale16_ConstSrcBlend"),\
    _T("Colorfill_444Scale16_PartBlend"),\
    _T("Colorfill_444Scale16_SrcBlend"),\
    _T("Composite_444_16"),\
    _T("Compute_Lumakey"),\
    _T("Compute_Lumakey_Buf0123"),\
    _T("ConstBlend_444_16"),\
    _T("ConstSrcBlend_444_16"),\
    _T("EOT"),\
    _T("FMD_Summation"),\
    _T("FRC_Clean_Map"),\
    _T("FRC_GMV_Detection"),\
    _T("FRC_GMV_Sanity_Check"),\
    _T("FRC_GradUV"),\
    _T("FRC_GradY"),\
    _T("FRC_MC"),\
    _T("FRC_ME_Level1"),\
    _T("FRC_ME_Level2"),\
    _T("FRC_ME_Level3"),\
    _T("FRC_MV_Level1"),\
    _T("FRC_MV_Level2"),\
    _T("FRC_MV_Level3"),\
    _T("FRC_PS"),\
    _T("FRC_SPD_Map"),\
    _T("FRC_TempDiff"),\
    _T("FRC_TempDiff_HD"),\
    _T("FRC_WSD"),\
    _T("GammaC"),\
    _T("GeoCorrection"),\
    _T("HDR_mandatory"),\
    _T("HDR_per_frame_stat"),\
    _T("IS_DS"),\
    _T("IS_FW"),\
    _T("IS_GMC"),\
    _T("IS_ME"),\
    _T("Interlace_420_16_Buf_0"),\
    _T("Interlace_420_16_Buf_1"),\
    _T("Interlace_420_16_Buf_2"),\
    _T("Interlace_420_16_Buf_3"),\
    _T("Interlace_444AVS16_Buf_0"),\
    _T("Interlace_444AVS16_Buf_1"),\
    _T("Interlace_444AVS16_Buf_2"),\
    _T("Interlace_444AVS16_Buf_3"),\
    _T("Interlace_444_16_Buf_0"),\
    _T("Interlace_444_16_Buf_1"),\
    _T("Interlace_444_16_Buf_2"),\
    _T("Interlace_444_16_Buf_3"),\
    _T("LACE_HIST_SUM"),\
    _T("LACE_LUT"),\
    _T("LACE_PWLF"),\
    _T("LACE_STD"),\
    _T("LinkFile"),\
    _T("Mirror_AVS_H_L0"),\
    _T("Mirror_AVS_V_L0"),\
    _T("Mirror_H_YUV"),\
    _T("Mirror_H_YUVA"),\
    _T("Mirror_scale_H_L0"),\
    _T("Mirror_scale_V_L0"),\
    _T("NV12_DP_rotation_avg"),\
    _T("NV12_DP_rotation_nv12"),\
    _T("NV12_DP_rotation_rep"),\
    _T("P010_444Dscale16_Buf_0"),\
    _T("P010_444Dscale16_Buf_0_Rot_180"),\
    _T("P010_444Dscale16_Buf_0_Rot_270"),\
    _T("P010_444Dscale16_Buf_0_Rot_90"),\
    _T("P010_444Dscale16_Buf_1"),\
    _T("P010_444Dscale16_Buf_1_Rot_180"),\
    _T("P010_444Dscale16_Buf_1_Rot_270"),\
    _T("P010_444Dscale16_Buf_1_Rot_90"),\
    _T("P010_444Dscale16_Buf_2"),\
    _T("P010_444Dscale16_Buf_2_Rot_180"),\
    _T("P010_444Dscale16_Buf_2_Rot_270"),\
    _T("P010_444Dscale16_Buf_2_Rot_90"),\
    _T("P010_444Dscale16_Buf_3"),\
    _T("P010_444Dscale16_Buf_3_Rot_180"),\
    _T("P010_444Dscale16_Buf_3_Rot_270"),\
    _T("P010_444Dscale16_Buf_3_Rot_90"),\
    _T("PA_444AVS16_Buf_0"),\
    _T("PA_444AVS16_Buf_0_Rot_180"),\
    _T("PA_444AVS16_Buf_0_Rot_270"),\
    _T("PA_444AVS16_Buf_0_Rot_90"),\
    _T("PA_444AVS16_Buf_1"),\
    _T("PA_444AVS16_Buf_1_Rot_180"),\
    _T("PA_444AVS16_Buf_1_Rot_270"),\
    _T("PA_444AVS16_Buf_1_Rot_90"),\
    _T("PA_444AVS16_Buf_2"),\
    _T("PA_444AVS16_Buf_2_Rot_180"),\
    _T("PA_444AVS16_Buf_2_Rot_270"),\
    _T("PA_444AVS16_Buf_2_Rot_90"),\
    _T("PA_444AVS16_Buf_3"),\
    _T("PA_444AVS16_Buf_3_Rot_180"),\
    _T("PA_444AVS16_Buf_3_Rot_270"),\
    _T("PA_444AVS16_Buf_3_Rot_90"),\
    _T("PA_444AVS16_Buf_4"),\
    _T("PA_444AVS16_Buf_4_Rot_180"),\
    _T("PA_444AVS16_Buf_4_Rot_270"),\
    _T("PA_444AVS16_Buf_4_Rot_90"),\
    _T("PA_444AVS16_Buf_5"),\
    _T("PA_444AVS16_Buf_5_Rot_180"),\
    _T("PA_444AVS16_Buf_5_Rot_270"),\
    _T("PA_444AVS16_Buf_5_Rot_90"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_PLANAR_420_8_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_Y8_UNORM_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_NORMAL_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUVY_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPUV_Buf_3"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_0"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_1"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_2"),\
    _T("PA_444AVS16_HDC_DW_YCRCB_SWAPY_Buf_3"),\
    _T("PA_444DScale16_Buf_0"),\
    _T("PA_444DScale16_Buf_0_Rot_180"),\
    _T("PA_444DScale16_Buf_0_Rot_270"),\
    _T("PA_444DScale16_Buf_0_Rot_90"),\
    _T("PA_444DScale16_Buf_1"),\
    _T("PA_444DScale16_Buf_1_Rot_180"),\
    _T("PA_444DScale16_Buf_1_Rot_270"),\
    _T("PA_444DScale16_Buf_1_Rot_90"),\
    _T("PA_444DScale16_Buf_2"),\
    _T("PA_444DScale16_Buf_2_Rot_180"),\
    _T("PA_444DScale16_Buf_2_Rot_270"),\
    _T("PA_444DScale16_Buf_2_Rot_90"),\
    _T("PA_444DScale16_Buf_3"),\
    _T("PA_444DScale16_Buf_3_Rot_180"),\
    _T("PA_444DScale16_Buf_3_Rot_270"),\
    _T("PA_444DScale16_Buf_3_Rot_90"),\
    _T("PA_444DScale16_Buf_4"),\
    _T("PA_444DScale16_Buf_4_Rot_180"),\
    _T("PA_444DScale16_Buf_4_Rot_270"),\
    _T("PA_444DScale16_Buf_4_Rot_90"),\
    _T("PA_444DScale16_Buf_5"),\
    _T("PA_444DScale16_Buf_5_Rot_180"),\
    _T("PA_444DScale16_Buf_5_Rot_270"),\
    _T("PA_444DScale16_Buf_5_Rot_90"),\
    _T("PA_444Scale16_Buf_0"),\
    _T("PA_444Scale16_Buf_0_Rot_180"),\
    _T("PA_444Scale16_Buf_0_Rot_270"),\
    _T("PA_444Scale16_Buf_0_Rot_90"),\
    _T("PA_444Scale16_Buf_1"),\
    _T("PA_444Scale16_Buf_1_Rot_180"),\
    _T("PA_444Scale16_Buf_1_Rot_270"),\
    _T("PA_444Scale16_Buf_1_Rot_90"),\
    _T("PA_444Scale16_Buf_2"),\
    _T("PA_444Scale16_Buf_2_Rot_180"),\
    _T("PA_444Scale16_Buf_2_Rot_270"),\
    _T("PA_444Scale16_Buf_2_Rot_90"),\
    _T("PA_444Scale16_Buf_3"),\
    _T("PA_444Scale16_Buf_3_Rot_180"),\
    _T("PA_444Scale16_Buf_3_Rot_270"),\
    _T("PA_444Scale16_Buf_3_Rot_90"),\
    _T("PA_444Scale16_Buf_4"),\
    _T("PA_444Scale16_Buf_4_Rot_180"),\
    _T("PA_444Scale16_Buf_4_Rot_270"),\
    _T("PA_444Scale16_Buf_4_Rot_90"),\
    _T("PA_444Scale16_Buf_5"),\
    _T("PA_444Scale16_Buf_5_Rot_180"),\
    _T("PA_444Scale16_Buf_5_Rot_270"),\
    _T("PA_444Scale16_Buf_5_Rot_90"),\
    _T("PA_444iAVS16_Buf_0"),\
    _T("PA_444iAVS16_Buf_1"),\
    _T("PA_444iAVS16_Buf_2"),\
    _T("PA_444iAVS16_Buf_3"),\
    _T("PA_444iDScale16_Buf_0"),\
    _T("PA_444iDScale16_Buf_1"),\
    _T("PA_444iDScale16_Buf_2"),\
    _T("PA_444iDScale16_Buf_3"),\
    _T("PA_444iScale16_Buf_0"),\
    _T("PA_444iScale16_Buf_0_Rot_180"),\
    _T("PA_444iScale16_Buf_0_Rot_270"),\
    _T("PA_444iScale16_Buf_0_Rot_90"),\
    _T("PA_444iScale16_Buf_1"),\
    _T("PA_444iScale16_Buf_1_Rot_180"),\
    _T("PA_444iScale16_Buf_1_Rot_270"),\
    _T("PA_444iScale16_Buf_1_Rot_90"),\
    _T("PA_444iScale16_Buf_2"),\
    _T("PA_444iScale16_Buf_2_Rot_180"),\
    _T("PA_444iScale16_Buf_2_Rot_270"),\
    _T("PA_444iScale16_Buf_2_Rot_90"),\
    _T("PA_444iScale16_Buf_3"),\
    _T("PA_444iScale16_Buf_3_Rot_180"),\
    _T("PA_444iScale16_Buf_3_Rot_270"),\
    _T("PA_444iScale16_Buf_3_Rot_90"),\
    _T("PA_AVS_Mirror_H_L0"),\
    _T("PA_AVS_Mirror_V_L0"),\
    _T("PA_AVS_Rotate_90_Mirror_H_L0"),\
    _T("PA_AVS_Rotate_90_Mirror_V_L0"),\
    _T("PA_AVS_Rotate_L0_180"),\
    _T("PA_AVS_Rotate_L0_270"),\
    _T("PA_AVS_Rotate_L0_90"),\
    _T("PA_Copy"),\
    _T("PA_Scale_Mirror_H_L0"),\
    _T("PA_Scale_Mirror_V_L0"),\
    _T("PA_Scale_Rotate90_Mirror_H_L0"),\
    _T("PA_Scale_Rotate90_Mirror_V_L0"),\
    _T("PA_Scale_Rotate_L0_180"),\
    _T("PA_Scale_Rotate_L0_270"),\
    _T("PA_Scale_Rotate_L0_90"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_0"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_1"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_2"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_3"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_4"),\
    _T("PL2_422AVS16_ChromaSiting_Buf_5"),\
    _T("PL2_444AVS16_Buf_0"),\
    _T("PL2_444AVS16_Buf_0_Rot_180"),\
    _T("PL2_444AVS16_Buf_0_Rot_270"),\
    _T("PL2_444AVS16_Buf_0_Rot_90"),\
    _T("PL2_444AVS16_Buf_1"),\
    _T("PL2_444AVS16_Buf_1_Rot_180"),\
    _T("PL2_444AVS16_Buf_1_Rot_270"),\
    _T("PL2_444AVS16_Buf_1_Rot_90"),\
    _T("PL2_444AVS16_Buf_2"),\
    _T("PL2_444AVS16_Buf_2_Rot_180"),\
    _T("PL2_444AVS16_Buf_2_Rot_270"),\
    _T("PL2_444AVS16_Buf_2_Rot_90"),\
    _T("PL2_444AVS16_Buf_3"),\
    _T("PL2_444AVS16_Buf_3_Rot_180"),\
    _T("PL2_444AVS16_Buf_3_Rot_270"),\
    _T("PL2_444AVS16_Buf_3_Rot_90"),\
    _T("PL2_444AVS16_Buf_4"),\
    _T("PL2_444AVS16_Buf_4_Rot_180"),\
    _T("PL2_444AVS16_Buf_4_Rot_270"),\
    _T("PL2_444AVS16_Buf_4_Rot_90"),\
    _T("PL2_444AVS16_Buf_5"),\
    _T("PL2_444AVS16_Buf_5_Rot_180"),\
    _T("PL2_444AVS16_Buf_5_Rot_270"),\
    _T("PL2_444AVS16_Buf_5_Rot_90"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4_Rot_180"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4_Rot_270"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_4_Rot_90"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5_Rot_180"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5_Rot_270"),\
    _T("PL2_444AVS16_Buf_Sep_Alpha_5_Rot_90"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_0"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_1"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_2"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_3"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_4"),\
    _T("PL2_444AVS16_ChromaSiting_Buf_5"),\
    _T("PL2_444DScale16_Buf_0"),\
    _T("PL2_444DScale16_Buf_0_Rot_180"),\
    _T("PL2_444DScale16_Buf_0_Rot_270"),\
    _T("PL2_444DScale16_Buf_0_Rot_90"),\
    _T("PL2_444DScale16_Buf_1"),\
    _T("PL2_444DScale16_Buf_1_Rot_180"),\
    _T("PL2_444DScale16_Buf_1_Rot_270"),\
    _T("PL2_444DScale16_Buf_1_Rot_90"),\
    _T("PL2_444DScale16_Buf_2"),\
    _T("PL2_444DScale16_Buf_2_Rot_180"),\
    _T("PL2_444DScale16_Buf_2_Rot_270"),\
    _T("PL2_444DScale16_Buf_2_Rot_90"),\
    _T("PL2_444DScale16_Buf_3"),\
    _T("PL2_444DScale16_Buf_3_Rot_180"),\
    _T("PL2_444DScale16_Buf_3_Rot_270"),\
    _T("PL2_444DScale16_Buf_3_Rot_90"),\
    _T("PL2_444DScale16_Buf_4"),\
    _T("PL2_444DScale16_Buf_4_Rot_180"),\
    _T("PL2_444DScale16_Buf_4_Rot_270"),\
    _T("PL2_444DScale16_Buf_4_Rot_90"),\
    _T("PL2_444DScale16_Buf_5"),\
    _T("PL2_444DScale16_Buf_5_Rot_180"),\
    _T("PL2_444DScale16_Buf_5_Rot_270"),\
    _T("PL2_444DScale16_Buf_5_Rot_90"),\
    _T("PL2_444DScale16_Buf_Sep_Alpha_4"),\
    _T("PL2_444DScale16_Buf_Sep_Alpha_5"),\
    _T("PL2_444Scale16_Buf_0"),\
    _T("PL2_444Scale16_Buf_0_Rot_180"),\
    _T("PL2_444Scale16_Buf_0_Rot_270"),\
    _T("PL2_444Scale16_Buf_0_Rot_90"),\
    _T("PL2_444Scale16_Buf_1"),\
    _T("PL2_444Scale16_Buf_1_Rot_180"),\
    _T("PL2_444Scale16_Buf_1_Rot_270"),\
    _T("PL2_444Scale16_Buf_1_Rot_90"),\
    _T("PL2_444Scale16_Buf_2"),\
    _T("PL2_444Scale16_Buf_2_Rot_180"),\
    _T("PL2_444Scale16_Buf_2_Rot_270"),\
    _T("PL2_444Scale16_Buf_2_Rot_90"),\
    _T("PL2_444Scale16_Buf_3"),\
    _T("PL2_444Scale16_Buf_3_Rot_180"),\
    _T("PL2_444Scale16_Buf_3_Rot_270"),\
    _T("PL2_444Scale16_Buf_3_Rot_90"),\
    _T("PL2_444Scale16_Buf_4"),\
    _T("PL2_444Scale16_Buf_4_Rot_180"),\
    _T("PL2_444Scale16_Buf_4_Rot_270"),\
    _T("PL2_444Scale16_Buf_4_Rot_90"),\
    _T("PL2_444Scale16_Buf_5"),\
    _T("PL2_444Scale16_Buf_5_Rot_180"),\
    _T("PL2_444Scale16_Buf_5_Rot_270"),\
    _T("PL2_444Scale16_Buf_5_Rot_90"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4_Rot_180"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4_Rot_270"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_4_Rot_90"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5_Rot_180"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5_Rot_270"),\
    _T("PL2_444Scale16_Buf_Sep_Alpha_5_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_0_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_1_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_2_Rot_90"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3_Rot_180"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3_Rot_270"),\
    _T("PL2_444Scale16_Chromasiting_Buf_3_Rot_90"),\
    _T("PL2_444iDScale16_Buf_0"),\
    _T("PL2_444iDScale16_Buf_1"),\
    _T("PL2_444iDScale16_Buf_2"),\
    _T("PL2_444iDScale16_Buf_3"),\
    _T("PL2_444iScale16_Buf_0"),\
    _T("PL2_444iScale16_Buf_0_Rot_180"),\
    _T("PL2_444iScale16_Buf_0_Rot_270"),\
    _T("PL2_444iScale16_Buf_0_Rot_90"),\
    _T("PL2_444iScale16_Buf_1"),\
    _T("PL2_444iScale16_Buf_1_Rot_180"),\
    _T("PL2_444iScale16_Buf_1_Rot_270"),\
    _T("PL2_444iScale16_Buf_1_Rot_90"),\
    _T("PL2_444iScale16_Buf_2"),\
    _T("PL2_444iScale16_Buf_2_Rot_180"),\
    _T("PL2_444iScale16_Buf_2_Rot_270"),\
    _T("PL2_444iScale16_Buf_2_Rot_90"),\
    _T("PL2_444iScale16_Buf_3"),\
    _T("PL2_444iScale16_Buf_3_Rot_180"),\
    _T("PL2_444iScale16_Buf_3_Rot_270"),\
    _T("PL2_444iScale16_Buf_3_Rot_90"),\
    _T("PL2_AVS_Mirror_H_L0"),\
    _T("PL2_AVS_Mirror_H_L0_DualOutput"),\
    _T("PL2_AVS_Mirror_V_L0"),\
    _T("PL2_AVS_Rotate90_Mirror_H_L0"),\
    _T("PL2_AVS_Rotate90_Mirror_V_L0"),\
    _T("PL2_AVS_Rotate_L0_180"),\
    _T("PL2_AVS_Rotate_L0_270"),\
    _T("PL2_AVS_Rotate_L0_90"),\
    _T("PL2_Copy"),\
    _T("PL2_Scale_Mirror_H_L0"),\
    _T("PL2_Scale_Mirror_H_L0_DualOutput"),\
    _T("PL2_Scale_Mirror_V_L0"),\
    _T("PL2_Scale_Rotate90_Mirror_H_L0"),\
    _T("PL2_Scale_Rotate90_Mirror_V_L0"),\
    _T("PL2_Scale_Rotate_L0_180"),\
    _T("PL2_Scale_Rotate_L0_270"),\
    _T("PL2_Scale_Rotate_L0_90"),\
    _T("PL3_444AVS16_Buf_0"),\
    _T("PL3_444AVS16_Buf_0_Rot_180"),\
    _T("PL3_444AVS16_Buf_0_Rot_270"),\
    _T("PL3_444AVS16_Buf_0_Rot_90"),\
    _T("PL3_444AVS16_Buf_1"),\
    _T("PL3_444AVS16_Buf_1_Rot_180"),\
    _T("PL3_444AVS16_Buf_1_Rot_270"),\
    _T("PL3_444AVS16_Buf_1_Rot_90"),\
    _T("PL3_444AVS16_Buf_2"),\
    _T("PL3_444AVS16_Buf_2_Rot_180"),\
    _T("PL3_444AVS16_Buf_2_Rot_270"),\
    _T("PL3_444AVS16_Buf_2_Rot_90"),\
    _T("PL3_444AVS16_Buf_3"),\
    _T("PL3_444AVS16_Buf_3_Rot_180"),\
    _T("PL3_444AVS16_Buf_3_Rot_270"),\
    _T("PL3_444AVS16_Buf_3_Rot_90"),\
    _T("PL3_444AVS16_Buf_4"),\
    _T("PL3_444AVS16_Buf_4_Rot_180"),\
    _T("PL3_444AVS16_Buf_4_Rot_270"),\
    _T("PL3_444AVS16_Buf_4_Rot_90"),\
    _T("PL3_444AVS16_Buf_5"),\
    _T("PL3_444AVS16_Buf_5_Rot_180"),\
    _T("PL3_444AVS16_Buf_5_Rot_270"),\
    _T("PL3_444AVS16_Buf_5_Rot_90"),\
    _T("PL3_444DScale16_Buf_0"),\
    _T("PL3_444DScale16_Buf_0_Rot_180"),\
    _T("PL3_444DScale16_Buf_0_Rot_270"),\
    _T("PL3_444DScale16_Buf_0_Rot_90"),\
    _T("PL3_444DScale16_Buf_1"),\
    _T("PL3_444DScale16_Buf_1_Rot_180"),\
    _T("PL3_444DScale16_Buf_1_Rot_270"),\
    _T("PL3_444DScale16_Buf_1_Rot_90"),\
    _T("PL3_444DScale16_Buf_2"),\
    _T("PL3_444DScale16_Buf_2_Rot_180"),\
    _T("PL3_444DScale16_Buf_2_Rot_270"),\
    _T("PL3_444DScale16_Buf_2_Rot_90"),\
    _T("PL3_444DScale16_Buf_3"),\
    _T("PL3_444DScale16_Buf_3_Rot_180"),\
    _T("PL3_444DScale16_Buf_3_Rot_270"),\
    _T("PL3_444DScale16_Buf_3_Rot_90"),\
    _T("PL3_444DScale16_Buf_4"),\
    _T("PL3_444DScale16_Buf_4_Rot_180"),\
    _T("PL3_444DScale16_Buf_4_Rot_270"),\
    _T("PL3_444DScale16_Buf_4_Rot_90"),\
    _T("PL3_444DScale16_Buf_5"),\
    _T("PL3_444DScale16_Buf_5_Rot_180"),\
    _T("PL3_444DScale16_Buf_5_Rot_270"),\
    _T("PL3_444DScale16_Buf_5_Rot_90"),\
    _T("PL3_444Scale16_Buf_0"),\
    _T("PL3_444Scale16_Buf_0_Rot_180"),\
    _T("PL3_444Scale16_Buf_0_Rot_270"),\
    _T("PL3_444Scale16_Buf_0_Rot_90"),\
    _T("PL3_444Scale16_Buf_1"),\
    _T("PL3_444Scale16_Buf_1_Rot_180"),\
    _T("PL3_444Scale16_Buf_1_Rot_270"),\
    _T("PL3_444Scale16_Buf_1_Rot_90"),\
    _T("PL3_444Scale16_Buf_2"),\
    _T("PL3_444Scale16_Buf_2_Rot_180"),\
    _T("PL3_444Scale16_Buf_2_Rot_270"),\
    _T("PL3_444Scale16_Buf_2_Rot_90"),\
    _T("PL3_444Scale16_Buf_3"),\
    _T("PL3_444Scale16_Buf_3_Rot_180"),\
    _T("PL3_444Scale16_Buf_3_Rot_270"),\
    _T("PL3_444Scale16_Buf_3_Rot_90"),\
    _T("PL3_444Scale16_Buf_4"),\
    _T("PL3_444Scale16_Buf_4_Rot_180"),\
    _T("PL3_444Scale16_Buf_4_Rot_270"),\
    _T("PL3_444Scale16_Buf_4_Rot_90"),\
    _T("PL3_444Scale16_Buf_5"),\
    _T("PL3_444Scale16_Buf_5_Rot_180"),\
    _T("PL3_444Scale16_Buf_5_Rot_270"),\
    _T("PL3_444Scale16_Buf_5_Rot_90"),\
    _T("PL3_444iDScale16_Buf_0"),\
    _T("PL3_444iDScale16_Buf_1"),\
    _T("PL3_444iDScale16_Buf_2"),\
    _T("PL3_444iDScale16_Buf_3"),\
    _T("PL3_444iScale16_Buf_0"),\
    _T("PL3_444iScale16_Buf_0_Rot_180"),\
    _T("PL3_444iScale16_Buf_0_Rot_270"),\
    _T("PL3_444iScale16_Buf_0_Rot_90"),\
    _T("PL3_444iScale16_Buf_1"),\
    _T("PL3_444iScale16_Buf_1_Rot_180"),\
    _T("PL3_444iScale16_Buf_1_Rot_270"),\
    _T("PL3_444iScale16_Buf_1_Rot_90"),\
    _T("PL3_444iScale16_Buf_2"),\
    _T("PL3_444iScale16_Buf_2_Rot_180"),\
    _T("PL3_444iScale16_Buf_2_Rot_270"),\
    _T("PL3_444iScale16_Buf_2_Rot_90"),\
    _T("PL3_444iScale16_Buf_3"),\
    _T("PL3_444iScale16_Buf_3_Rot_180"),\
    _T("PL3_444iScale16_Buf_3_Rot_270"),\
    _T("PL3_444iScale16_Buf_3_Rot_90"),\
    _T("PL3_AVS_Rotate_L0_180"),\
    _T("PL3_AVS_Rotate_L0_270"),\
    _T("PL3_AVS_Rotate_L0_90"),\
    _T("PL3_Scale_Rotate_L0_180"),\
    _T("PL3_Scale_Rotate_L0_270"),\
    _T("PL3_Scale_Rotate_L0_90"),\
    _T("PLY_444DScale16_2f_Buf_0"),\
    _T("PLY_444DScale16_2f_Buf_1"),\
    _T("PLY_444DScale16_2f_Buf_2"),\
    _T("PLY_444DScale16_2f_Buf_3"),\
    _T("PLY_444DScale16_Buf_0"),\
    _T("PLY_444DScale16_Buf_0_Rot_180"),\
    _T("PLY_444DScale16_Buf_0_Rot_270"),\
    _T("PLY_444DScale16_Buf_0_Rot_90"),\
    _T("PLY_444DScale16_Buf_1"),\
    _T("PLY_444DScale16_Buf_1_Rot_180"),\
    _T("PLY_444DScale16_Buf_1_Rot_270"),\
    _T("PLY_444DScale16_Buf_1_Rot_90"),\
    _T("PLY_444DScale16_Buf_2"),\
    _T("PLY_444DScale16_Buf_2_Rot_180"),\
    _T("PLY_444DScale16_Buf_2_Rot_270"),\
    _T("PLY_444DScale16_Buf_2_Rot_90"),\
    _T("PLY_444DScale16_Buf_3"),\
    _T("PLY_444DScale16_Buf_3_Rot_180"),\
    _T("PLY_444DScale16_Buf_3_Rot_270"),\
    _T("PLY_444DScale16_Buf_3_Rot_90"),\
    _T("PartBlend_444_16"),\
    _T("Prepare_LumaKey_SampleUnorm"),\
    _T("RGB2sRGB"),\
    _T("Rotate_90_Mirror_AVS_H_L0"),\
    _T("Rotate_90_Mirror_AVS_V_L0"),\
    _T("Rotate_90_Mirror_H_scale_L0"),\
    _T("Rotate_90_Mirror_V_scale_L0"),\
    _T("Rotate_AVS_L0_180"),\
    _T("Rotate_AVS_L0_270"),\
    _T("Rotate_AVS_L0_90"),\
    _T("Rotate_Scale_L0_180"),\
    _T("Rotate_Scale_L0_270"),\
    _T("Rotate_Scale_L0_90"),\
    _T("SIP_Debug"),\
    _T("Save_444AVS16_ARGB"),\
    _T("Save_444AVS16_ARGB_64Byte"),\
    _T("Save_444AVS16_NV12"),\
    _T("Save_444AVS16_NV21"),\
    _T("Save_444AVS16_PA"),\
    _T("Save_444AVS16_PL3"),\
    _T("Save_444AVS16_R10G10B10"),\
    _T("Save_444AVS16_R10G10B10A2"),\
    _T("Save_444AVS16_R10G10B10X2"),\
    _T("Save_444AVS16_RGB"),\
    _T("Save_444AVS16_RGB16"),\
    _T("Save_444AVS16_RGB_64Byte"),\
    _T("Save_444AVS16_SrcAYUV"),\
    _T("Save_444AVS16_XRGB"),\
    _T("Save_444AVS16_XRGB_64Byte"),\
    _T("Save_444Scale16_ARGB"),\
    _T("Save_444Scale16_ARGB_64Byte"),\
    _T("Save_444Scale16_Dither_NV12"),\
    _T("Save_444Scale16_Dither_NV21"),\
    _T("Save_444Scale16_Dither_PA"),\
    _T("Save_444Scale16_Dither_PA_32X16"),\
    _T("Save_444Scale16_Dither_PL3"),\
    _T("Save_444Scale16_Dither_RGB"),\
    _T("Save_444Scale16_Dither_RGB_64Byte"),\
    _T("Save_444Scale16_Dither_VUYA"),\
    _T("Save_444Scale16_Dither_XRGB"),\
    _T("Save_444Scale16_Dither_XRGB_64Byte"),\
    _T("Save_444Scale16_NV12"),\
    _T("Save_444Scale16_NV21"),\
    _T("Save_444Scale16_P010"),\
    _T("Save_444Scale16_PA"),\
    _T("Save_444Scale16_PA_32X16"),\
    _T("Save_444Scale16_PL3"),\
    _T("Save_444Scale16_PLY"),\
    _T("Save_444Scale16_R10G10B10"),\
    _T("Save_444Scale16_R10G10B10A2"),\
    _T("Save_444Scale16_R10G10B10X2"),\
    _T("Save_444Scale16_R10G10B10XR"),\
    _T("Save_444Scale16_R10G10B10XRA2"),\
    _T("Save_444Scale16_R10G10B10XRX2"),\
    _T("Save_444Scale16_RGB"),\
    _T("Save_444Scale16_RGB16"),\
    _T("Save_444Scale16_RGBP"),\
    _T("Save_444Scale16_RGB_64Byte"),\
    _T("Save_444Scale16_SrcVUYA"),\
    _T("Save_444Scale16_VUYA"),\
    _T("Save_444Scale16_XRGB"),\
    _T("Save_444Scale16_XRGB_64Byte"),\
    _T("Save_444Scale16_Y210"),\
    _T("Save_444Scale16_Y216"),\
    _T("Save_444Scale16_Y410"),\
    _T("Save_444Scale16_Y416"),\
    _T("Secure_Block_Copy"),\
    _T("Set_Buf0_Buf4"),\
    _T("Set_Buf1_Buf5"),\
    _T("Set_Buf2_Buf4"),\
    _T("Set_Buf3_Buf5"),\
    _T("Set_CSC_Src_Buf0"),\
    _T("Set_CSC_Src_Buf1"),\
    _T("Set_CSC_Src_Buf2"),\
    _T("Set_CSC_Src_Buf3"),\
    _T("Set_CSC_Src_Buf4"),\
    _T("Set_CSC_Src_Buf5"),\
    _T("Set_CURBE_CSC_Coeff"),\
    _T("Set_ColorE_Src_Buf0"),\
    _T("Set_ColorE_Src_Buf1"),\
    _T("Set_ColorE_Src_Buf2"),\
    _T("Set_ColorE_Src_Buf3"),\
    _T("Set_Dest_Surf_Indexes_Primary"),\
    _T("Set_Dest_Surf_Indexes_Secondary"),\
    _T("Set_GammaC_Src_Buf0"),\
    _T("Set_GammaC_Src_Buf1"),\
    _T("Set_GammaC_Src_Buf2"),\
    _T("Set_GammaC_Src_Buf3"),\
    _T("Set_Layer_0"),\
    _T("Set_Layer_1"),\
    _T("Set_Layer_1_AVS"),\
    _T("Set_Layer_2"),\
    _T("Set_Layer_3"),\
    _T("Set_Layer_4"),\
    _T("Set_Layer_5"),\
    _T("Set_Layer_6"),\
    _T("Set_Layer_7"),\
    _T("Set_Patched_CSC_Coeff"),\
    _T("Set_Scale_Buf_0123_Colorfill"),\
    _T("Set_Sec_Half_Buf45"),\
    _T("Shuffle_444AVS16_Buf_0"),\
    _T("Shuffle_444AVS16_Buf_1"),\
    _T("Shuffle_444AVS16_Buf_2"),\
    _T("Shuffle_444AVS16_Buf_3"),\
    _T("Shuffle_444AVS16_Buf_4"),\
    _T("Shuffle_444AVS16_Buf_5"),\
    _T("SrcBlend_444_16"),\
    _T("SrcBlend_4bits_444_16"),\
    _T("UpdateDNState"),\
    _T("VP_Setup"),\
    _T("VP_Setup_MediaWalker"),\
    _T("VP_Setup_MediaWalker_32X16_Design"),\
    _T("VP_Setup_MediaWalker_32x32_Color"),\
    _T("Y210_444DScale16_Buf_0"),\
    _T("Y210_444DScale16_Buf_0_Rot_180"),\
    _T("Y210_444DScale16_Buf_0_Rot_270"),\
    _T("Y210_444DScale16_Buf_0_Rot_90"),\
    _T("Y210_444DScale16_Buf_1"),\
    _T("Y210_444DScale16_Buf_1_Rot_180"),\
    _T("Y210_444DScale16_Buf_1_Rot_270"),\
    _T("Y210_444DScale16_Buf_1_Rot_90"),\
    _T("Y210_444DScale16_Buf_2"),\
    _T("Y210_444DScale16_Buf_2_Rot_180"),\
    _T("Y210_444DScale16_Buf_2_Rot_270"),\
    _T("Y210_444DScale16_Buf_2_Rot_90"),\
    _T("Y210_444DScale16_Buf_3"),\
    _T("Y210_444DScale16_Buf_3_Rot_180"),\
    _T("Y210_444DScale16_Buf_3_Rot_270"),\
    _T("Y210_444DScale16_Buf_3_Rot_90"),\
    _T("Y210_444DScale16_Buf_4"),\
    _T("Y210_444DScale16_Buf_4_Rot_180"),\
    _T("Y210_444DScale16_Buf_4_Rot_270"),\
    _T("Y210_444DScale16_Buf_4_Rot_90"),\
    _T("Y210_444DScale16_Buf_5"),\
    _T("Y210_444DScale16_Buf_5_Rot_180"),\
    _T("Y210_444DScale16_Buf_5_Rot_270"),\
    _T("Y210_444DScale16_Buf_5_Rot_90"),\
    _T("Y210_444Scale16_Buf_0"),\
    _T("Y210_444Scale16_Buf_0_Rot_180"),\
    _T("Y210_444Scale16_Buf_0_Rot_270"),\
    _T("Y210_444Scale16_Buf_0_Rot_90"),\
    _T("Y210_444Scale16_Buf_1"),\
    _T("Y210_444Scale16_Buf_1_Rot_180"),\
    _T("Y210_444Scale16_Buf_1_Rot_270"),\
    _T("Y210_444Scale16_Buf_1_Rot_90"),\
    _T("Y210_444Scale16_Buf_2"),\
    _T("Y210_444Scale16_Buf_2_Rot_180"),\
    _T("Y210_444Scale16_Buf_2_Rot_270"),\
    _T("Y210_444Scale16_Buf_2_Rot_90"),\
    _T("Y210_444Scale16_Buf_3"),\
    _T("Y210_444Scale16_Buf_3_Rot_180"),\
    _T("Y210_444Scale16_Buf_3_Rot_270"),\
    _T("Y210_444Scale16_Buf_3_Rot_90"),\
    _T("Y210_444Scale16_Buf_4"),\
    _T("Y210_444Scale16_Buf_4_Rot_180"),\
    _T("Y210_444Scale16_Buf_4_Rot_270"),\
    _T("Y210_444Scale16_Buf_4_Rot_90"),\
    _T("Y210_444Scale16_Buf_5"),\
    _T("Y210_444Scale16_Buf_5_Rot_180"),\
    _T("Y210_444Scale16_Buf_5_Rot_270"),\
    _T("Y210_444Scale16_Buf_5_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_0_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_1_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_2_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_3_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_4_Rot_90"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_180"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_270"),\
    _T("Y210_444_AVS16_Y_Scale16_UV_Buf_5_Rot_90"),\
    _T("Y410_444AVS16_Buf_0"),\
    _T("Y410_444AVS16_Buf_0_Rot_180"),\
    _T("Y410_444AVS16_Buf_0_Rot_270"),\
    _T("Y410_444AVS16_Buf_0_Rot_90"),\
    _T("Y410_444AVS16_Buf_1"),\
    _T("Y410_444AVS16_Buf_1_Rot_180"),\
    _T("Y410_444AVS16_Buf_1_Rot_270"),\
    _T("Y410_444AVS16_Buf_1_Rot_90"),\
    _T("Y410_444AVS16_Buf_2"),\
    _T("Y410_444AVS16_Buf_2_Rot_180"),\
    _T("Y410_444AVS16_Buf_2_Rot_270"),\
    _T("Y410_444AVS16_Buf_2_Rot_90"),\
    _T("Y410_444AVS16_Buf_3"),\
    _T("Y410_444AVS16_Buf_3_Rot_180"),\
    _T("Y410_444AVS16_Buf_3_Rot_270"),\
    _T("Y410_444AVS16_Buf_3_Rot_90"),\
    _T("Y410_444AVS16_Buf_4"),\
    _T("Y410_444AVS16_Buf_4_Rot_180"),\
    _T("Y410_444AVS16_Buf_4_Rot_270"),\
    _T("Y410_444AVS16_Buf_4_Rot_90"),\
    _T("Y410_444AVS16_Buf_5"),\
    _T("Y410_444AVS16_Buf_5_Rot_180"),\
    _T("Y410_444AVS16_Buf_5_Rot_270"),\
    _T("Y410_444AVS16_Buf_5_Rot_90"),\
    _T("Y410_444DScale16_Buf_0"),\
    _T("Y410_444DScale16_Buf_0_Rot_180"),\
    _T("Y410_444DScale16_Buf_0_Rot_270"),\
    _T("Y410_444DScale16_Buf_0_Rot_90"),\
    _T("Y410_444DScale16_Buf_1"),\
    _T("Y410_444DScale16_Buf_1_Rot_180"),\
    _T("Y410_444DScale16_Buf_1_Rot_270"),\
    _T("Y410_444DScale16_Buf_1_Rot_90"),\
    _T("Y410_444DScale16_Buf_2"),\
    _T("Y410_444DScale16_Buf_2_Rot_180"),\
    _T("Y410_444DScale16_Buf_2_Rot_270"),\
    _T("Y410_444DScale16_Buf_2_Rot_90"),\
    _T("Y410_444DScale16_Buf_3"),\
    _T("Y410_444DScale16_Buf_3_Rot_180"),\
    _T("Y410_444DScale16_Buf_3_Rot_270"),\
    _T("Y410_444DScale16_Buf_3_Rot_90"),\
    _T("Y410_444DScale16_Buf_4"),\
    _T("Y410_444DScale16_Buf_4_Rot_180"),\
    _T("Y410_444DScale16_Buf_4_Rot_270"),\
    _T("Y410_444DScale16_Buf_4_Rot_90"),\
    _T("Y410_444DScale16_Buf_5"),\
    _T("Y410_444DScale16_Buf_5_Rot_180"),\
    _T("Y410_444DScale16_Buf_5_Rot_270"),\
    _T("Y410_444DScale16_Buf_5_Rot_90"),\
    _T("Y410_444Scale16_Buf_0"),\
    _T("Y410_444Scale16_Buf_0_Rot_180"),\
    _T("Y410_444Scale16_Buf_0_Rot_270"),\
    _T("Y410_444Scale16_Buf_0_Rot_90"),\
    _T("Y410_444Scale16_Buf_1"),\
    _T("Y410_444Scale16_Buf_1_Rot_180"),\
    _T("Y410_444Scale16_Buf_1_Rot_270"),\
    _T("Y410_444Scale16_Buf_1_Rot_90"),\
    _T("Y410_444Scale16_Buf_2"),\
    _T("Y410_444Scale16_Buf_2_Rot_180"),\
    _T("Y410_444Scale16_Buf_2_Rot_270"),\
    _T("Y410_444Scale16_Buf_2_Rot_90"),\
    _T("Y410_444Scale16_Buf_3"),\
    _T("Y410_444Scale16_Buf_3_Rot_180"),\
    _T("Y410_444Scale16_Buf_3_Rot_270"),\
    _T("Y410_444Scale16_Buf_3_Rot_90"),\
    _T("Y410_444Scale16_Buf_4"),\
    _T("Y410_444Scale16_Buf_4_Rot_180"),\
    _T("Y410_444Scale16_Buf_4_Rot_270"),\
    _T("Y410_444Scale16_Buf_4_Rot_90"),\
    _T("Y410_444Scale16_Buf_5"),\
    _T("Y410_444Scale16_Buf_5_Rot_180"),\
    _T("Y410_444Scale16_Buf_5_Rot_270"),\
    _T("Y410_444Scale16_Buf_5_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_0_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_1_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_2_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_3_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_4_Rot_90"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5_Rot_180"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5_Rot_270"),\
    _T("YUY2_444Scale16_Chromasiting_Buf_5_Rot_90"),\
    _T("avs_scale_16aligned"),\
    _T("camera_pipe_CalcParams"),\
    _T("fast_avs_1_to_n"),\
    _T("return"),\
    _T("zzz_preproduction"),\
    _T("zzz_preproduction_ALLPL2Copy_Gen"),\
    _T("zzz_preproduction_HDR_mandatory_Gen"),\
    _T("zzz_preproduction_HDR_per_frame_stat_Gen"),\
    _T("zzz_preproduction_gcBltPS_32_To_128_Mirror_Gen"),\
    _T("zzz_preproduction_gcBltPS_64_To_128_Mirror_Gen"),\
    _T("zzz_preproduction_gcBltPS_Gen"),\
    _T("zzz_preproduction_gcClearNoReplicatePS_Gen"),\
    _T("zzz_preproduction_gcClearReplicatePS_Gen"),\
    _T("zzz_preproduction_gcColorFillNoReplicatePS_Gen"),\
    _T("zzz_preproduction_gcColorFillReplicatePS_Gen"),\
    _T("zzz_preproduction_gcFastClearReplicatePS_Gen"),\
    _T("zzz_production"),\
    _T("zzz_production_ALLPL2Copy_Gen"),\
    _T("zzz_production_HDR_mandatory_Gen"),\
    _T("zzz_production_HDR_per_frame_stat_Gen"),\
    _T("zzz_production_gcBltPS_32_To_128_Mirror_Gen"),\
    _T("zzz_production_gcBltPS_64_To_128_Mirror_Gen"),\
    _T("zzz_production_gcBltPS_Gen"),\
    _T("zzz_production_gcClearNoReplicatePS_Gen"),\
    _T("zzz_production_gcClearReplicatePS_Gen"),\
    _T("zzz_production_gcColorFillNoReplicatePS_Gen"),\
    _T("zzz_production_gcColorFillReplicatePS_Gen"),\
    _T("zzz_production_gcFastClearReplicatePS_Gen"),\
    _T("")
#else // !_DEBUG
#define IDR_VP_KERNEL_NAMES   \
    _T("000"),\
    _T("001"),\
    _T("002"),\
    _T("003"),\
    _T("004"),\
    _T("005"),\
    _T("006"),\
    _T("007"),\
    _T("008"),\
    _T("009"),\
    _T("010"),\
    _T("011"),\
    _T("012"),\
    _T("013"),\
    _T("014"),\
    _T("015"),\
    _T("016"),\
    _T("017"),\
    _T("018"),\
    _T("019"),\
    _T("020"),\
    _T("021"),\
    _T("022"),\
    _T("023"),\
    _T("024"),\
    _T("025"),\
    _T("026"),\
    _T("027"),\
    _T("028"),\
    _T("029"),\
    _T("030"),\
    _T("031"),\
    _T("032"),\
    _T("033"),\
    _T("034"),\
    _T("035"),\
    _T("036"),\
    _T("037"),\
    _T("038"),\
    _T("039"),\
    _T("040"),\
    _T("041"),\
    _T("042"),\
    _T("043"),\
    _T("044"),\
    _T("045"),\
    _T("046"),\
    _T("047"),\
    _T("048"),\
    _T("049"),\
    _T("050"),\
    _T("051"),\
    _T("052"),\
    _T("053"),\
    _T("054"),\
    _T("055"),\
    _T("056"),\
    _T("057"),\
    _T("058"),\
    _T("059"),\
    _T("060"),\
    _T("061"),\
    _T("062"),\
    _T("063"),\
    _T("064"),\
    _T("065"),\
    _T("066"),\
    _T("067"),\
    _T("068"),\
    _T("069"),\
    _T("070"),\
    _T("071"),\
    _T("072"),\
    _T("073"),\
    _T("074"),\
    _T("075"),\
    _T("076"),\
    _T("077"),\
    _T("078"),\
    _T("079"),\
    _T("080"),\
    _T("081"),\
    _T("082"),\
    _T("083"),\
    _T("084"),\
    _T("085"),\
    _T("086"),\
    _T("087"),\
    _T("088"),\
    _T("089"),\
    _T("090"),\
    _T("091"),\
    _T("092"),\
    _T("093"),\
    _T("094"),\
    _T("095"),\
    _T("096"),\
    _T("097"),\
    _T("098"),\
    _T("099"),\
    _T("100"),\
    _T("101"),\
    _T("102"),\
    _T("103"),\
    _T("104"),\
    _T("105"),\
    _T("106"),\
    _T("107"),\
    _T("108"),\
    _T("109"),\
    _T("110"),\
    _T("111"),\
    _T("112"),\
    _T("113"),\
    _T("114"),\
    _T("115"),\
    _T("116"),\
    _T("117"),\
    _T("118"),\
    _T("119"),\
    _T("120"),\
    _T("121"),\
    _T("122"),\
    _T("123"),\
    _T("124"),\
    _T("125"),\
    _T("126"),\
    _T("127"),\
    _T("128"),\
    _T("129"),\
    _T("130"),\
    _T("131"),\
    _T("132"),\
    _T("133"),\
    _T("134"),\
    _T("135"),\
    _T("136"),\
    _T("137"),\
    _T("138"),\
    _T("139"),\
    _T("140"),\
    _T("141"),\
    _T("142"),\
    _T("143"),\
    _T("144"),\
    _T("145"),\
    _T("146"),\
    _T("147"),\
    _T("148"),\
    _T("149"),\
    _T("150"),\
    _T("151"),\
    _T("152"),\
    _T("153"),\
    _T("154"),\
    _T("155"),\
    _T("156"),\
    _T("157"),\
    _T("158"),\
    _T("159"),\
    _T("160"),\
    _T("161"),\
    _T("162"),\
    _T("163"),\
    _T("164"),\
    _T("165"),\
    _T("166"),\
    _T("167"),\
    _T("168"),\
    _T("169"),\
    _T("170"),\
    _T("171"),\
    _T("172"),\
    _T("173"),\
    _T("174"),\
    _T("175"),\
    _T("176"),\
    _T("177"),\
    _T("178"),\
    _T("179"),\
    _T("180"),\
    _T("181"),\
    _T("182"),\
    _T("183"),\
    _T("184"),\
    _T("185"),\
    _T("186"),\
    _T("187"),\
    _T("188"),\
    _T("189"),\
    _T("190"),\
    _T("191"),\
    _T("192"),\
    _T("193"),\
    _T("194"),\
    _T("195"),\
    _T("196"),\
    _T("197"),\
    _T("198"),\
    _T("199"),\
    _T("200"),\
    _T("201"),\
    _T("202"),\
    _T("203"),\
    _T("204"),\
    _T("205"),\
    _T("206"),\
    _T("207"),\
    _T("208"),\
    _T("209"),\
    _T("210"),\
    _T("211"),\
    _T("212"),\
    _T("213"),\
    _T("214"),\
    _T("215"),\
    _T("216"),\
    _T("217"),\
    _T("218"),\
    _T("219"),\
    _T("220"),\
    _T("221"),\
    _T("222"),\
    _T("223"),\
    _T("224"),\
    _T("225"),\
    _T("226"),\
    _T("227"),\
    _T("228"),\
    _T("229"),\
    _T("230"),\
    _T("231"),\
    _T("232"),\
    _T("233"),\
    _T("234"),\
    _T("235"),\
    _T("236"),\
    _T("237"),\
    _T("238"),\
    _T("239"),\
    _T("240"),\
    _T("241"),\
    _T("242"),\
    _T("243"),\
    _T("244"),\
    _T("245"),\
    _T("246"),\
    _T("247"),\
    _T("248"),\
    _T("249"),\
    _T("250"),\
    _T("251"),\
    _T("252"),\
    _T("253"),\
    _T("254"),\
    _T("255"),\
    _T("256"),\
    _T("257"),\
    _T("258"),\
    _T("259"),\
    _T("260"),\
    _T("261"),\
    _T("262"),\
    _T("263"),\
    _T("264"),\
    _T("265"),\
    _T("266"),\
    _T("267"),\
    _T("268"),\
    _T("269"),\
    _T("270"),\
    _T("271"),\
    _T("272"),\
    _T("273"),\
    _T("274"),\
    _T("275"),\
    _T("276"),\
    _T("277"),\
    _T("278"),\
    _T("279"),\
    _T("280"),\
    _T("281"),\
    _T("282"),\
    _T("283"),\
    _T("284"),\
    _T("285"),\
    _T("286"),\
    _T("287"),\
    _T("288"),\
    _T("289"),\
    _T("290"),\
    _T("291"),\
    _T("292"),\
    _T("293"),\
    _T("294"),\
    _T("295"),\
    _T("296"),\
    _T("297"),\
    _T("298"),\
    _T("299"),\
    _T("300"),\
    _T("301"),\
    _T("302"),\
    _T("303"),\
    _T("304"),\
    _T("305"),\
    _T("306"),\
    _T("307"),\
    _T("308"),\
    _T("309"),\
    _T("310"),\
    _T("311"),\
    _T("312"),\
    _T("313"),\
    _T("314"),\
    _T("315"),\
    _T("316"),\
    _T("317"),\
    _T("318"),\
    _T("319"),\
    _T("320"),\
    _T("321"),\
    _T("322"),\
    _T("323"),\
    _T("324"),\
    _T("325"),\
    _T("326"),\
    _T("327"),\
    _T("328"),\
    _T("329"),\
    _T("330"),\
    _T("331"),\
    _T("332"),\
    _T("333"),\
    _T("334"),\
    _T("335"),\
    _T("336"),\
    _T("337"),\
    _T("338"),\
    _T("339"),\
    _T("340"),\
    _T("341"),\
    _T("342"),\
    _T("343"),\
    _T("344"),\
    _T("345"),\
    _T("346"),\
    _T("347"),\
    _T("348"),\
    _T("349"),\
    _T("350"),\
    _T("351"),\
    _T("352"),\
    _T("353"),\
    _T("354"),\
    _T("355"),\
    _T("356"),\
    _T("357"),\
    _T("358"),\
    _T("359"),\
    _T("360"),\
    _T("361"),\
    _T("362"),\
    _T("363"),\
    _T("364"),\
    _T("365"),\
    _T("366"),\
    _T("367"),\
    _T("368"),\
    _T("369"),\
    _T("370"),\
    _T("371"),\
    _T("372"),\
    _T("373"),\
    _T("374"),\
    _T("375"),\
    _T("376"),\
    _T("377"),\
    _T("378"),\
    _T("379"),\
    _T("380"),\
    _T("381"),\
    _T("382"),\
    _T("383"),\
    _T("384"),\
    _T("385"),\
    _T("386"),\
    _T("387"),\
    _T("388"),\
    _T("389"),\
    _T("390"),\
    _T("391"),\
    _T("392"),\
    _T("393"),\
    _T("394"),\
    _T("395"),\
    _T("396"),\
    _T("397"),\
    _T("398"),\
    _T("399"),\
    _T("400"),\
    _T("401"),\
    _T("402"),\
    _T("403"),\
    _T("404"),\
    _T("405"),\
    _T("406"),\
    _T("407"),\
    _T("408"),\
    _T("409"),\
    _T("410"),\
    _T("411"),\
    _T("412"),\
    _T("413"),\
    _T("414"),\
    _T("415"),\
    _T("416"),\
    _T("417"),\
    _T("418"),\
    _T("419"),\
    _T("420"),\
    _T("421"),\
    _T("422"),\
    _T("423"),\
    _T("424"),\
    _T("425"),\
    _T("426"),\
    _T("427"),\
    _T("428"),\
    _T("429"),\
    _T("430"),\
    _T("431"),\
    _T("432"),\
    _T("433"),\
    _T("434"),\
    _T("435"),\
    _T("436"),\
    _T("437"),\
    _T("438"),\
    _T("439"),\
    _T("440"),\
    _T("441"),\
    _T("442"),\
    _T("443"),\
    _T("444"),\
    _T("445"),\
    _T("446"),\
    _T("447"),\
    _T("448"),\
    _T("449"),\
    _T("450"),\
    _T("451"),\
    _T("452"),\
    _T("453"),\
    _T("454"),\
    _T("455"),\
    _T("456"),\
    _T("457"),\
    _T("458"),\
    _T("459"),\
    _T("460"),\
    _T("461"),\
    _T("462"),\
    _T("463"),\
    _T("464"),\
    _T("465"),\
    _T("466"),\
    _T("467"),\
    _T("468"),\
    _T("469"),\
    _T("470"),\
    _T("471"),\
    _T("472"),\
    _T("473"),\
    _T("474"),\
    _T("475"),\
    _T("476"),\
    _T("477"),\
    _T("478"),\
    _T("479"),\
    _T("480"),\
    _T("481"),\
    _T("482"),\
    _T("483"),\
    _T("484"),\
    _T("485"),\
    _T("486"),\
    _T("487"),\
    _T("488"),\
    _T("489"),\
    _T("490"),\
    _T("491"),\
    _T("492"),\
    _T("493"),\
    _T("494"),\
    _T("495"),\
    _T("496"),\
    _T("497"),\
    _T("498"),\
    _T("499"),\
    _T("500"),\
    _T("501"),\
    _T("502"),\
    _T("503"),\
    _T("504"),\
    _T("505"),\
    _T("506"),\
    _T("507"),\
    _T("508"),\
    _T("509"),\
    _T("510"),\
    _T("511"),\
    _T("512"),\
    _T("513"),\
    _T("514"),\
    _T("515"),\
    _T("516"),\
    _T("517"),\
    _T("518"),\
    _T("519"),\
    _T("520"),\
    _T("521"),\
    _T("522"),\
    _T("523"),\
    _T("524"),\
    _T("525"),\
    _T("526"),\
    _T("527"),\
    _T("528"),\
    _T("529"),\
    _T("530"),\
    _T("531"),\
    _T("532"),\
    _T("533"),\
    _T("534"),\
    _T("535"),\
    _T("536"),\
    _T("537"),\
    _T("538"),\
    _T("539"),\
    _T("540"),\
    _T("541"),\
    _T("542"),\
    _T("543"),\
    _T("544"),\
    _T("545"),\
    _T("546"),\
    _T("547"),\
    _T("548"),\
    _T("549"),\
    _T("550"),\
    _T("551"),\
    _T("552"),\
    _T("553"),\
    _T("554"),\
    _T("555"),\
    _T("556"),\
    _T("557"),\
    _T("558"),\
    _T("559"),\
    _T("560"),\
    _T("561"),\
    _T("562"),\
    _T("563"),\
    _T("564"),\
    _T("565"),\
    _T("566"),\
    _T("567"),\
    _T("568"),\
    _T("569"),\
    _T("570"),\
    _T("571"),\
    _T("572"),\
    _T("573"),\
    _T("574"),\
    _T("575"),\
    _T("576"),\
    _T("577"),\
    _T("578"),\
    _T("579"),\
    _T("580"),\
    _T("581"),\
    _T("582"),\
    _T("583"),\
    _T("584"),\
    _T("585"),\
    _T("586"),\
    _T("587"),\
    _T("588"),\
    _T("589"),\
    _T("590"),\
    _T("591"),\
    _T("592"),\
    _T("593"),\
    _T("594"),\
    _T("595"),\
    _T("596"),\
    _T("597"),\
    _T("598"),\
    _T("599"),\
    _T("600"),\
    _T("601"),\
    _T("602"),\
    _T("603"),\
    _T("604"),\
    _T("605"),\
    _T("606"),\
    _T("607"),\
    _T("608"),\
    _T("609"),\
    _T("610"),\
    _T("611"),\
    _T("612"),\
    _T("613"),\
    _T("614"),\
    _T("615"),\
    _T("616"),\
    _T("617"),\
    _T("618"),\
    _T("619"),\
    _T("620"),\
    _T("621"),\
    _T("622"),\
    _T("623"),\
    _T("624"),\
    _T("625"),\
    _T("626"),\
    _T("627"),\
    _T("628"),\
    _T("629"),\
    _T("630"),\
    _T("631"),\
    _T("632"),\
    _T("633"),\
    _T("634"),\
    _T("635"),\
    _T("636"),\
    _T("637"),\
    _T("638"),\
    _T("639"),\
    _T("640"),\
    _T("641"),\
    _T("642"),\
    _T("643"),\
    _T("644"),\
    _T("645"),\
    _T("646"),\
    _T("647"),\
    _T("648"),\
    _T("649"),\
    _T("650"),\
    _T("651"),\
    _T("652"),\
    _T("653"),\
    _T("654"),\
    _T("655"),\
    _T("656"),\
    _T("657"),\
    _T("658"),\
    _T("659"),\
    _T("660"),\
    _T("661"),\
    _T("662"),\
    _T("663"),\
    _T("664"),\
    _T("665"),\
    _T("666"),\
    _T("667"),\
    _T("668"),\
    _T("669"),\
    _T("670"),\
    _T("671"),\
    _T("672"),\
    _T("673"),\
    _T("674"),\
    _T("675"),\
    _T("676"),\
    _T("677"),\
    _T("678"),\
    _T("679"),\
    _T("680"),\
    _T("681"),\
    _T("682"),\
    _T("683"),\
    _T("684"),\
    _T("685"),\
    _T("686"),\
    _T("687"),\
    _T("688"),\
    _T("689"),\
    _T("690"),\
    _T("691"),\
    _T("692"),\
    _T("693"),\
    _T("694"),\
    _T("695"),\
    _T("696"),\
    _T("697"),\
    _T("698"),\
    _T("699"),\
    _T("700"),\
    _T("701"),\
    _T("702"),\
    _T("703"),\
    _T("704"),\
    _T("705"),\
    _T("706"),\
    _T("707"),\
    _T("708"),\
    _T("709"),\
    _T("710"),\
    _T("711"),\
    _T("712"),\
    _T("713"),\
    _T("714"),\
    _T("715"),\
    _T("716"),\
    _T("717"),\
    _T("718"),\
    _T("719"),\
    _T("720"),\
    _T("721"),\
    _T("722"),\
    _T("723"),\
    _T("724"),\
    _T("725"),\
    _T("726"),\
    _T("727"),\
    _T("728"),\
    _T("729"),\
    _T("730"),\
    _T("731"),\
    _T("732"),\
    _T("733"),\
    _T("734"),\
    _T("735"),\
    _T("736"),\
    _T("737"),\
    _T("738"),\
    _T("739"),\
    _T("740"),\
    _T("741"),\
    _T("742"),\
    _T("743"),\
    _T("744"),\
    _T("745"),\
    _T("746"),\
    _T("747"),\
    _T("748"),\
    _T("749"),\
    _T("750"),\
    _T("751"),\
    _T("752"),\
    _T("753"),\
    _T("754"),\
    _T("755"),\
    _T("756"),\
    _T("757"),\
    _T("758"),\
    _T("759"),\
    _T("760"),\
    _T("761"),\
    _T("762"),\
    _T("763"),\
    _T("764"),\
    _T("765"),\
    _T("766"),\
    _T("767"),\
    _T("768"),\
    _T("769"),\
    _T("770"),\
    _T("771"),\
    _T("772"),\
    _T("773"),\
    _T("774"),\
    _T("775"),\
    _T("776"),\
    _T("777"),\
    _T("778"),\
    _T("779"),\
    _T("780"),\
    _T("781"),\
    _T("782"),\
    _T("783"),\
    _T("784"),\
    _T("785"),\
    _T("786"),\
    _T("787"),\
    _T("788"),\
    _T("789"),\
    _T("790"),\
    _T("791"),\
    _T("792"),\
    _T("793"),\
    _T("794"),\
    _T("795"),\
    _T("796"),\
    _T("797"),\
    _T("798"),\
    _T("799"),\
    _T("800"),\
    _T("801"),\
    _T("802"),\
    _T("803"),\
    _T("804"),\
    _T("805"),\
    _T("806"),\
    _T("807"),\
    _T("808"),\
    _T("809"),\
    _T("810"),\
    _T("811"),\
    _T("812"),\
    _T("813"),\
    _T("814"),\
    _T("815"),\
    _T("816"),\
    _T("817"),\
    _T("818"),\
    _T("819"),\
    _T("820"),\
    _T("")
#endif // _DEBUG

#endif // __VPKRNHEADER_H__
