/*
* Copyright (c) 2017, Intel Corporation
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
* OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*/

////////////////////////////////////////////////////////////////////////////////
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!
// Generated by GenKrnBin.exe tool
////////////////////////////////////////////////////////////////////////////////
#ifndef __CODECKRNHEADER_H__
#define __CODECKRNHEADER_H__

#define IDR_CODEC_LINKFILE_VERSION 65536
#define IDR_CODEC_LINKFILE_HEADER 16

#define IDR_CODEC_ALLPACopy 0
#define IDR_CODEC_ALLPL2Copy 1
#define IDR_CODEC_ALLPL2ToNV12iScale 2
#define IDR_CODEC_ALLPL2ToPAiScale 3
#define IDR_CODEC_AllAVCEnc 4
#define IDR_CODEC_AllAVCEnc_FEI 5
#define IDR_CODEC_AllHEVCEnc 6
#define IDR_CODEC_AllMPEG2Enc 7
#define IDR_CODEC_AllVC1_NV12 8
#define IDR_CODEC_AllVP8Enc 9
#define IDR_CODEC_AllVP9Enc 10
#define IDR_CODEC_Downscale_Copy 11
#define IDR_CODEC_HEVC_COMBINED_KENREL_INTEL 12
#define IDR_CODEC_HEVC_FEI_COMBINED_KENREL_INTEL 13
#define IDR_CODEC_HME_DS_SCOREBOARD_KERNEL 14
#define IDR_CODEC_LinkFile 15
#define IDR_CODEC_VDENC_HME 16
#define IDR_CODEC_TOTAL_NUM_KERNELS 17

#if _DEBUG
#define IDR_CODEC_KERNEL_NAMES   \
    _T("ALLPACopy"),\
    _T("ALLPL2Copy"),\
    _T("ALLPL2ToNV12iScale"),\
    _T("ALLPL2ToPAiScale"),\
    _T("AllAVCEnc"),\
    _T("AllAVCEnc_FEI"),\
    _T("AllHEVCEnc"),\
    _T("AllMPEG2Enc"),\
    _T("AllVC1_NV12"),\
    _T("AllVP8Enc"),\
    _T("AllVP9Enc"),\
    _T("Downscale_Copy"),\
    _T("HEVC_COMBINED_KENREL_INTEL"),\
    _T("HEVC_FEI_COMBINED_KENREL_INTEL"),\
    _T("HME_DS_SCOREBOARD_KERNEL"),\
    _T("LinkFile"),\
    _T("VDENC_HME"),\
    _T("")
#else // !_DEBUG
#define IDR_CODEC_KERNEL_NAMES   \
    _T("000"),\
    _T("001"),\
    _T("002"),\
    _T("003"),\
    _T("004"),\
    _T("005"),\
    _T("006"),\
    _T("007"),\
    _T("008"),\
    _T("009"),\
    _T("010"),\
    _T("011"),\
    _T("012"),\
    _T("013"),\
    _T("014"),\
    _T("015"),\
    _T("016"),\
    _T("")
#endif // _DEBUG

#endif // __CODECKRNHEADER_H__
