/*
 * Copyright (c) 2024, Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * 'Software'), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

////////////////////////////////////////////////////////////////////////////////
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!
// Generated by KernelBinToSource.exe tool
////////////////////////////////////////////////////////////////////////////////

#ifndef __IGVPFC_444PL3_OUTPUT_XE2_H__
#define __IGVPFC_444PL3_OUTPUT_XE2_H__

#include "media_bin_mgr.h"
DECLARE_SHARED_ARRAY_SIZE_UINT32(IGVPFC_444PL3_OUTPUT_GENERATION_XE2_SIZE);
DECLARE_SHARED_ARRAY_UINT32(IGVPFC_444PL3_OUTPUT_GENERATION_XE2);

#if defined(MEDIA_BIN_SUPPORT)

#define IGVPFC_444PL3_OUTPUT_GENERATION_XE2_NAME "IGVPFC_444PL3_OUTPUT_XE2"

#if defined(MEDIA_BIN_DLL)
static bool registerIGVPFC_444PL3_OUTPUT_XE2 = RegisterMediaBin(IGVPFC_444PL3_OUTPUT_GENERATION_XE2_NAME, IGVPFC_444PL3_OUTPUT_GENERATION_XE2_SIZE, IGVPFC_444PL3_OUTPUT_GENERATION_XE2);

#endif  // defined(MEDIA_BIN_DLL)

#endif  // defined(MEDIA_BIN_SUPPORT)

#if !defined(MEDIA_BIN_DLL)
#include "igvpfc_444PL3_output_args.h"
// Following functions are always needed in media driver dll no matter media_bin_supported or not
extern void AddVpNativeKernelEntryToListFc_444pl3_outputXe2(vp::VpPlatformInterface &vpPlatformInterface);
#endif  // !defined(MEDIA_BIN_DLL)

#endif // __IGVPFC_444PL3_OUTPUT_XE2_H__
