/*
 * Copyright (c) 2024, Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * 'Software'), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

////////////////////////////////////////////////////////////////////////////////
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!
// Generated by KernelBinToSource.exe tool
////////////////////////////////////////////////////////////////////////////////

#ifndef __IGVPFC_444PL3_INPUT_ENUM_H__
#define __IGVPFC_444PL3_INPUT_ENUM_H__

enum ARGS_FC_444PL3_INPUT_IMAGEREAD
{
    FC_444PL3_INPUT_IMAGEREAD_INPUTPLANE0,
    FC_444PL3_INPUT_IMAGEREAD_INPUTPLANE1,
    FC_444PL3_INPUT_IMAGEREAD_INPUTPLANE2,
    FC_444PL3_INPUT_IMAGEREAD_OUTPUTPLANE,
    FC_444PL3_INPUT_IMAGEREAD_INPUTINDEX,
    FC_444PL3_INPUT_IMAGEREAD_OUTPUTINDEX,
    FC_444PL3_INPUT_IMAGEREAD_PLANEINDEX,
    FC_444PL3_INPUT_IMAGEREAD_ENQUEUED_LOCAL_SIZE,
    FC_444PL3_INPUT_IMAGEREAD_GLOBAL_ID_OFFSET,
    FC_444PL3_INPUT_IMAGEREAD_LOCAL_SIZE,
    FC_444PL3_INPUT_IMAGEREAD_MAX
};

#endif // __IGVPFC_444PL3_INPUT_ENUM_H__
