/*
 * Copyright (c) 2024, Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * 'Software'), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

////////////////////////////////////////////////////////////////////////////////
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!
// Generated by KernelBinToSource.exe tool
////////////////////////////////////////////////////////////////////////////////

#ifndef __IGVPFC_FP_ENUM_H__
#define __IGVPFC_FP_ENUM_H__

enum ARGS_FC_FP_FASTEXPRESS
{
    FC_FP_FASTEXPRESS_INPUTPL0,
    FC_FP_FASTEXPRESS_INPUTPL1,
    FC_FP_FASTEXPRESS_OUTPUTPL0,
    FC_FP_FASTEXPRESS_OUTPUTPL1,
    FC_FP_FASTEXPRESS_LAYERNUMBER,
    FC_FP_FASTEXPRESS_INLINE_SAMPLER_LINEAR_CLAMP_EDGE,
    FC_FP_FASTEXPRESS_INLINE_SAMPLER_NEAREST_CLAMP_EDGE,
    FC_FP_FASTEXPRESS_IMAGEPARAM,
    FC_FP_FASTEXPRESS_OUTPUTPARAM,
    FC_FP_FASTEXPRESS_PRIVATE_BASE_STATELESS,
    FC_FP_FASTEXPRESS_GLOBAL_SIZE,
    FC_FP_FASTEXPRESS_ENQUEUED_LOCAL_SIZE,
    FC_FP_FASTEXPRESS_GLOBAL_ID_OFFSET,
    FC_FP_FASTEXPRESS_LOCAL_SIZE,
    FC_FP_FASTEXPRESS_MAX
};

#endif // __IGVPFC_FP_ENUM_H__
