/*
 * Copyright (c) 2024, Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * 'Software'), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

////////////////////////////////////////////////////////////////////////////////
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!
// Generated by KernelBinToSource.exe tool
////////////////////////////////////////////////////////////////////////////////

#ifndef __IGVPFC_SCALE_ENUM_H__
#define __IGVPFC_SCALE_ENUM_H__

enum ARGS_FC_SCALE_PA_444D
{
    FC_SCALE_PA_444D_INPUT,
    FC_SCALE_PA_444D_OUTPUT,
    FC_SCALE_PA_444D_SHIFT,
    FC_SCALE_PA_444D_INPUTIMAGESMPL,
    FC_SCALE_PA_444D_OFFSET,
    FC_SCALE_PA_444D_BITNUM,
    FC_SCALE_PA_444D_ENQUEUED_LOCAL_SIZE,
    FC_SCALE_PA_444D_INPUT_IMAGE_HEIGHT,
    FC_SCALE_PA_444D_OUTPUT_IMAGE_HEIGHT,
    FC_SCALE_PA_444D_INPUT_IMAGE_WIDTH,
    FC_SCALE_PA_444D_OUTPUT_IMAGE_WIDTH,
    FC_SCALE_PA_444D_INPUTIMAGESMPL_SAMPLER_SNAP_WA,
    FC_SCALE_PA_444D_GLOBAL_ID_OFFSET,
    FC_SCALE_PA_444D_LOCAL_SIZE,
    FC_SCALE_PA_444D_MAX
};

#endif // __IGVPFC_SCALE_ENUM_H__
