/*
 * Copyright (c) 2024, Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * 'Software'), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

////////////////////////////////////////////////////////////////////////////////
// !!! WARNING - AUTO GENERATED FILE. DO NOT EDIT DIRECTLY. !!!
// Generated by KernelBinToSource.exe tool
////////////////////////////////////////////////////////////////////////////////

#ifndef __IGVPFC_420PL3_OUTPUT_ENUM_H__
#define __IGVPFC_420PL3_OUTPUT_ENUM_H__

enum ARGS_FC_420PL3_OUTPUT_IMAGEWRITE
{
    FC_420PL3_OUTPUT_IMAGEWRITE_INPUTPLY,
    FC_420PL3_OUTPUT_IMAGEWRITE_INPUTPLUV,
    FC_420PL3_OUTPUT_IMAGEWRITE_OUTPUTPLY,
    FC_420PL3_OUTPUT_IMAGEWRITE_OUTPUTPLU,
    FC_420PL3_OUTPUT_IMAGEWRITE_OUTPUTPLV,
    FC_420PL3_OUTPUT_IMAGEWRITE_WIDTH,
    FC_420PL3_OUTPUT_IMAGEWRITE_HEIGHT,
    FC_420PL3_OUTPUT_IMAGEWRITE_LUMAINDEX,
    FC_420PL3_OUTPUT_IMAGEWRITE_UPLINDEX,
    FC_420PL3_OUTPUT_IMAGEWRITE_VPLINDEX,
    FC_420PL3_OUTPUT_IMAGEWRITE_PRIVATE_BASE_STATELESS,
    FC_420PL3_OUTPUT_IMAGEWRITE_ENQUEUED_LOCAL_SIZE,
    FC_420PL3_OUTPUT_IMAGEWRITE_GLOBAL_ID_OFFSET,
    FC_420PL3_OUTPUT_IMAGEWRITE_LOCAL_SIZE,
    FC_420PL3_OUTPUT_IMAGEWRITE_MAX
};

#endif // __IGVPFC_420PL3_OUTPUT_ENUM_H__
